### ISSUE TITLE
xmake root 权限安装问题

### ISSUE THREAD

**Issue by 745275633** [tboox/xmake#111]
xmake 有没有办法强制在 root 权限下运行？

**Comment by TitanSnow** [comment]
See #61

**Comment by 745275633** [comment]
我需要使用 root 运行 xmake

**Comment by TitanSnow** [comment]
#61 described why running xmake as root is deprecated

xmake *can* run as root. See `xmake/core/main.lua` line 163:

```lua
    -- check run command as root
    if not option.get("root") then
        local ok, errors = main._check_root()
        if not ok then
            utils.error(errors)
            return -1
        end
    end
```

That is, when option `root` is got, xmake will accept to run as root.

But, the option `root` has not been add to `common option`. That means we cannot use `xmake --root`. That should be a mistake. @waruqi 

After I do this modify, xmake accepts `--root`

```diff
diff --git a/xmake/core/project/task.lua b/xmake/core/project/task.lua
index 35c051ef..7bc08d6c 100644
--- a/xmake/core/project/task.lua
+++ b/xmake/core/project/task.lua
@@ -145,7 +145,8 @@ function task._translate_menu(menu)
                                                               , "    1. The Given Command Argument"
                                                               , "    2. The Envirnoment Variable: XMAKE_PROJECT_DIR"
                                                               , "    3. The Current Directory"              })
-        table.insert(options, 10, {})
+        table.insert(options, 10, {nil,"root","k",nil,"awd"})
+        table.insert(options, 11, {})
 
     end
 
```

**But, there are some problems. After I try running xmake as root, `/dev/null` becomes unwritable for common users. That might be a bug**

**Comment by waruqi** [comment]
@745275633 我修改了下xmake，master上新版本支持临时允许root运行，通过命令： `sudo xmake --root f -c`, `sudo xmake --root` ，所有命令前加上 `--root`参数..

**Comment by waruqi** [comment]
@TitanSnow 

> But, the option root has not been add to common option. That means we cannot use xmake --root. That should be a mistake. @waruqi

I have modified it as common option.

> But, there are some problems. After I try running xmake as root, /dev/null becomes unwritable for common users. That might be a bug

I have fixed it.

**Comment by waruqi** [comment]
@745275633  see [#113](https://github.com/tboox/xmake/pull/113).
