### ISSUE TITLE
Why xmake auto link libm

### ISSUE THREAD

**Issue by 745275633** [tboox/xmake#120]
I see libm in ldd in binary and shared.
Or can I let xmake doesn't link libm

**Comment by TitanSnow** [comment]
More detail, please

**Comment by 745275633** [comment]
I create by `xmake create -l c++ -t 3`
build by `xmake`
and `ldd build/libtest.so` output
```
        linux-vdso.so.1 (0x00007fff043fe000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fb3a8772000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007fb3a845f000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fb3a8248000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007fb3a7ea4000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x000055fa13541000)
```

**Comment by TitanSnow** [comment]
Reproduced. It's g++'s default behavior not xmake's

```console
$ g++ -xc++ - -Wall -Wextra
int main(){return 0;}
$ ldd a.out
	linux-gate.so.1 (0xb77aa000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0xb7607000)
	libm.so.6 => /lib/libm.so.6 (0xb75ab000)
	libgcc_s.so.1 => /lib/libgcc_s.so.1 (0xb758d000)
	libc.so.6 => /lib/libc.so.6 (0xb73cd000)
	/lib/ld-linux.so.2 (0x8000f000)
```

**Comment by TitanSnow** [comment]
@745275633 I found something on [stackoverflow](https://stackoverflow.com/questions/1033898). The answer points out:

> Interestingly, the C++ runtime `libstdc++` requires `libm`, so if you compile a C++ program with GCC (`g++`), you will automatically get `libm` linked in.

So there must be `libm`. It's necessary and normal

If you actually mean to do it, you could try `-nodefaultlib`, but I don't except it to work
