### ISSUE TITLE
How to build .rc file?

### ISSUE THREAD

**Issue by lidroid** [tboox/xmake#121]
Generally, build icon to program via .rc file, but i don't find any sample about build .rc file, how to do it? thanks for your great work.

**Comment by TitanSnow** [comment]
@waruqi feature needed [Using RC (The RC Command Line)](https://msdn.microsoft.com/en-us/library/windows/desktop/aa381055(v=vs.85).aspx)

**Comment by waruqi** [comment]
@lidroid  @TitanSnow  Ok, I will support it in the these days.

**Comment by waruqi** [comment]
@lidroid @TitanSnow I have implemented this feature. You can fetch the lastest version on dev branch and try it.

**Comment by lidroid** [comment]
@waruqi how to build xmake on windows platform?

**Comment by TitanSnow** [comment]
@lidroid xmake builds xmake on Windows

```powershell
cd core
xmake
```

**Comment by lidroid** [comment]
@waruqi works fine. thanks for your great work!!!

**Comment by waruqi** [comment]
@lidroid 😄
