### ISSUE TITLE
`find_library` module

### ISSUE THREAD

**Issue by TitanSnow** [tboox/xmake#122]
Base features

- [x] find_library
  - [x] only find library file from the given pathes
- [x] find_package
  - [x] find includedir
  - [x] find library version
  - [x] find from `pkg-config` path
  - [x] find from some system dirs
  - [x] find link and linkdir by calling `detect.package.find_xxx` if exists
  - [x] find package from `~/.xmake/packages` in `repo` branch
  - [x] find link and linkdir by calling `find_library` from some default dirs
  - [x] attempt to compile and link to check package 

Ways to impl

* `pkg-config`
  I found `pkg-config` could be base of `find_library`. It supports these features
  * check if library exists
  ```console
  $ pkg-config python3 --exists
  # returncode 0 -- there is libpython3
  ```
  * get includedir of library
  ```console
  $ pkg-config python3 --cflags-only-I
  -I/usr/include/python3.5m -I/usr/include/i386-linux-gnu/python3.5m
  ```
  * get link flags
  ```console
  $ pkg-config python3 --libs         
  -lpython3.5m
  ```
  * get library version
  ```console
  $ pkg-config python3 --modversion
  3.5
  ```
  **Unluckily, it does not support even mac os**
  And, there are few library it could find. For example, on my machine
  ```console
  $ pkg-config --list-all
  tic                            tic - ncurses 6.0 add-on library
  lua51-c++                      Lua - Lua language engine
  poppler-data                   poppler-data - Encoding files for use with poppler
  yelp-xsl                       yelp-xsl - Yelp XSLT Stylesheets
  python-3.5m                    Python - Python library
  systemd                        systemd - systemd System and Service Manager
  fontutil                       FontUtil - Font utilities dirs
  usbutils                       usbutils - USB device database
  bash-completion                bash-completion - programmable completion for the bash shell
  lua-5.1-c++                    Lua - Lua language engine
  mobile-broadband-provider-info mobile-broadband-provider-info - Mobile Broadband Service Provider Information Database
  ibus-table                     IBus-Table - Table Based Input Method Framework for Intelligent Input Bus for Linux / Unix OS
  geoclue-2.0                    Geoclue - The Geoinformation Service
  lua5.1                         Lua - Lua language engine
  lua-5.1                        Lua - Lua language engine
  libquvi-scripts-0.9            libquvi-scripts - Scripts for libquvi
  iso-codes                      iso-codes - ISO country, language, script and currency codes and translations
  tinfo                          tinfo - ncurses 6.0 terminal interface library
  adwaita-icon-theme             gnome-icon-theme - A collection of icons used as the basis for GNOME themes
  udev                           udev - udev
  shared-mime-info               shared-mime-info - Freedesktop common MIME database
  expat                          expat - expat XML parser
  dleyna-renderer-1.0            dleyna-renderer - UPnP & DLNA renderer library
  xbitmaps                       X bitmaps - Bitmaps that are shared between X applications
  dleyna-connector-dbus-1.0      dleyna-connector-dbus - dLeyna dbus connector
  lua51                          Lua - Lua language engine
  python-3.5                     Python - Python library
  dleyna-renderer-service-1.0    dleyna-renderer-service - UPnP & DLNA service to discover and manipulate renderers
  dleyna-server-1.0              dleyna-server - UPnP & DLNA server library
  lua5.1-c++                     Lua - Lua language engine
  xkeyboard-config               XKeyboardConfig - X Keyboard configuration data
  dleyna-server-service-1.0      dleyna-server-service - UPnP & DLNA media content management
  python3                        Python - Python library
  xkbcomp                        xkbcomp - XKB keymap compiler
  ```

**Comment by waruqi** [comment]
@TitanSnow Right, I'm going to use `pkg-config` too. And we can also attempt to find libraries from other package manage software (.e.g homebrew)

**Comment by waruqi** [comment]
[#83](https://github.com/tboox/xmake/issues/83)

**Comment by waruqi** [comment]
I saw the `find_library` and `find_package` of cmake. It looks like this.

- `find_library` is only used to find a single library file. 
- `find_package` find a library and it's dependent libraries by given name (contains `includedir`, `linkdir` and `links`)
  -  uses `pkg-config` only to get the search path (`includedir` and `linkdir`) if exists, this is optional, we cannot use it's results directly because its package name is not normalized and the result may be wrong
  - uses `find_file` and `find_library` to find include and library files 
     - from the pathes of `pkg-config`
     - from some default pathes 
  
For example:  

`find_package("OpenSSL")` :
  - call it to search openssl if `Modules/FindOpenSSL.cmake` exists
  - get library info from `OpenSSLConfig.cmake` if exists
  - add library name directly

Our way looks might look like this:

`find_package("OpenSSL")` :
  - call it to search openssl if `detect.package.find_openssl` exists
  - find it from `~/.xmake/packages/openssl` (`xmake require openssl` in the `repo` branch)
  - uses `find_file` and `find_library` to find it from some of the known paths (`/usr/lib`, `pkg-config`)

**Comment by waruqi** [comment]
Usage of `find_package`:

```lua
target("test")
    before_build(function (target)

         -- imports
         import("lib.detect.find_package")

         -- find and add package
         target:add(find_package("openssl"))
         target:add(find_package("libpng", {version = "1.0.1"}))

         -- add flags to target dynamically
         target:add("links", "xxxx", "aaaa")
         target:add("linkdirs", "/usr/lib")
    end)
```

**Comment by TitanSnow** [comment]
Couldn't reproduce
```console
$ xmake --version
xmake v2.1.5.201706141243, A make-like build utility based on Lua
Copyright (C) 2015-2017 Ruki Wang, tboox.org, xmake.io
Copyright (C) 2005-2015 Mike Pall, luajit.org
                         _        
    __  ___ __  __  __ _| | ______ 
    \ \/ / |  \/  |/ _  | |/ / __ \
     >  <  | \__/ | /_| |   <  ___/
    /_/\_\_|_|  |_|\__ \|_|\_\____| 
                         by ruki, tboox.org
                                      
$ pkg-config zlib --libs --cflags
-lz
$ xmake l
> find_package=import("lib.detect.find_package")
> find_package("zlib")

> 
```

**Comment by waruqi** [comment]
@TitanSnow It works on my machines (linux, macOS and windows). Did you install it in the latest version in dev branch 8c26570e658b2a458db92fd2ffc8906e905c1ca1?

```console
$ xmake l lib.detect.find_package zlib

{
    links =
    {
        z
    }

,   linkdirs =
    {
        /usr/lib
    }

}
```

**Comment by TitanSnow** [comment]
Yes. I'll provide details later

**Comment by TitanSnow** [comment]
See [this build](https://travis-ci.org/TitanSnow/xmake/builds/242748756)

**Comment by waruqi** [comment]
@TitanSnow I have fixed it. 75a12f5e305adfa4fd7d3bb8abb13ec8460a4df8

**Comment by TitanSnow** [comment]
[python distutils](https://github.com/python/cpython/tree/master/Lib/distutils) contains several useful features like `find_library_file` ([ccompiler.py](https://github.com/python/cpython/blob/master/Lib/distutils/ccompiler.py#L803))

**Comment by waruqi** [comment]
@TitanSnow Ok, I will look at it. Thanks! 😸

**Comment by waruqi** [comment]
@TitanSnow I have finished `find_library` and `find_package` in version 2.1.5 and I will continue to improve it in next version. 😄
