### ISSUE TITLE
windows7+vs2015: LINK : fatal error LNK1221: a subsystem can't be inferred and must be defined

### ISSUE THREAD

**Issue by sophonia101** [tboox/xmake#126]
create a new project with xmake, and link other project complied with vs2015, get the link error: 
LINK : fatal error LNK1221: a subsystem can't be inferred and must be defined.
There is no place or flags to set the flag "/subsystem:".

在windows7下用xmake 创建新的c工程，编译链接外部动态库(由vs2015编译生成)，提示LNK1221的 错误，说明 flag“/subsystem”没有输入。

**Comment by waruqi** [comment]
You can write `add_ldflags("-subsystem:console")` or `add_ldflags("-subsystem:windows")` and try it again.

默认配置是没有配置`/subsystem:`的，也就是按`/subsystem:console`来链接，你可以尝试在`xmake.lua`手动设置下：`add_ldflags("-subsystem:console")` 或者 `add_ldflags("-subsystem:windows")` 再试试。。

尝试之前，先更新下安装包，重新安装下，我修复了一些其他的问题
