### ISSUE TITLE
win7+vs2015: export vs2015 solution with xmake, get the error about "MSB8036 Windows SDK version".

### ISSUE THREAD

**Issue by sophonia101** [tboox/xmake#127]
step1: create one vs2015 project with command: xmake project -k vs2015 -m "debug,release"
step2: compile with IDE vs2015, get the error message: 
Error	MSB8036	The Windows SDK version 10.0.10240.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".
step3: right-clicking the solution and "Retarget solution" can fix this issue.

用xmake生成vs2015工程后，在windows7+vs2015的环境下打开编译，提示关于“Retarget solution”的错误，重定位SDK version后可以解决此问题。
原因是xmake在导出时hardcode写入 windows SDK version 导致的。

**Comment by waruqi** [comment]
I have improved it and detect the vs sdk version automatically.

新的安装包，我通过尝试自动检测当前已安装的vs环境中sdk版本号，来创建工程，你可以再试下。
