### ISSUE TITLE
win7+vs2015: compile x64 project, get Error	LNK1112	module machine type 'x64' conflicts with target machine type 'X86'

### ISSUE THREAD

**Issue by sophonia101** [tboox/xmake#128]
step1: create one vs2015 project with command: xmake project -k vs2015 -m "debug,release"
step2: compile with IDE vs2015 with arch "x64", get the error message: 
Error	LNK1112	module machine type 'x64' conflicts with target machine type 'X86'
step3: open the project property in vs2015, fix the issue with changing the linker property from "-machine:x86 " to "-machine:x64" .

用xmake生成vs2015工程后，在windows7+vs2015的环境下打开编译，选择“x64”编译选项，提示：
LNK1112	module machine type 'x64' conflicts with target machine type 'X86'
原因是xmake在导出时x64的module配置错误，在vs里修改即可通过编译。

**Comment by waruqi** [comment]
I have fixed this problem. You can download [xmake-v2.1.5-dev](https://github.com/tboox/xmake/releases/download/v2.1.4/xmake-v2.1.5-dev.exe.zip) and try it again. 😄 

我已经修复这个问题了，你可以重新到release下面现在安装包试下， [xmake-v2.1.5-dev](https://github.com/tboox/xmake/releases/download/v2.1.4/xmake-v2.1.5-dev.exe.zip) 的安装包我已经更新过了。。
