### ISSUE TITLE
target 重新构建会执行不必要的构建步骤

### ISSUE THREAD

**Issue by llxwj** [tboox/xmake#129]
一个xmake.lua文件中指定了多个target, 第一次全部构建完成后,如果后续只对某个target所依赖的源码文件进行了修改,那么再次使用xmake构建时, 其他target的源码确实没有重新编译,但是target最终生成步骤(ar或ld)又执行了一次,重复构建应该是不必要的.

**Comment by waruqi** [comment]
在`dev`分支上已修复这个问题。。

**Comment by llxwj** [comment]
经测试表现已经很好了,但仍然存在问题,故障描述如下:
* xmale.lua中包含5个target
* 只修改了一个target所依赖的源码文件
* xmake构建后,被修改的源码文件执行编译并且重新生成了它所归属的target
* 同时另外一个无关的target也被重新生成,此target和被修改的源码文件没有任何依赖关系
* 重复修改,构建这个步骤,无关的target是同一个target.
* 其余3个target没有重新生成.

**Comment by waruqi** [comment]
好的。。我后两天继续改进下。。

**Comment by waruqi** [comment]
@llxwj 我改进了下。。你再试试

**Comment by llxwj** [comment]
@waruqi 刚才测试了一下,正常了.
