### ISSUE TITLE
vs2015项目生成问题

### ISSUE THREAD

**Issue by panhaowen** [tboox/xmake#130]
最近要为引擎写统一编译脚本，看到xmake我感到这就是我想要的，但是我写了一个构建脚本(用lua原生代码再次封装了xmake的API),其中set_basename(xx_$(mode)_$(arch)),objectdir(xx/projName) ,set_targetdir(xx/ProjName),类似这样的语法，但是在最终生成vs2015时,并未得到我想要的结果(什么都没改,貌似全是默认值),并且如果我使用绝对路径的话，生成的vs项目文件层级会有很多层“..”(猜测可能是相对路径这块没处理好)。如果有时间可以加我QQ376973750,我可以上传我的脚本给你查看，谢谢。

**Comment by waruqi** [comment]
你好 你可以加一下qq群 343118190 把demo发我下 我调下。。谢谢

**Comment by waruqi** [comment]
对于 `set_objectdir` 一直是ok的，而 `set_targetdir`和`set_basename`确实有问题，没有生效，现已修复，你可以试下，请从release上下载安装包：[xmake-v2.1.5-dev.exe.zip](https://github.com/tboox/xmake/releases/download/v2.1.4/xmake-v2.1.5-dev.exe.zip)

> 并且如果我使用绝对路径的话，生成的vs项目文件层级会有很多层“..”(猜测可能是相对路径这块没处理好)

对于这个问题，建议尽量不要在`xmake.lua`里面写绝对路径，这样也不方便工程的迁移，目前绝对路径转相对路径，确实没对 `..` 做压缩，所以会有些冗余，之后会改进。。

里面的所有路径配置建议设置为`xmake.lua`脚本的相对路径
