### ISSUE TITLE
iOS Frameworks路径问题

### ISSUE THREAD

**Issue by libyyu** [tboox/xmake#132]
在编译iOS项目的时候，项目中使用了一些framework，如JSONKit,iflyMSC等，使用如下方式：
#import "JSONKit.h"
#import "iflyMSC/IFlySpeechRecognizer.h"
在Xcode中提供了Framework SearchPath，编译没问题。但是用xmake，怎么设置搜索路径呢，
用了add_frameworks("JSonKit")还是不行，一直报这几个文件找不到。请问这个该怎么解决。谢谢。

fatal error: 'JSONKit.h' file not found  #import "JSONKit.h"

**Comment by waruqi** [comment]
@libyyu 你可以尝试先手动加 编译选项：`add_mxflags("-F/xxx/frameworkdir")` 和 `add_ldflags("-F/xxx/frameworkdir")` 试试。。。

后两天我会增加个 `add_frameworkdirs` 来支持下。。

**Comment by waruqi** [comment]
dev分支上 我已经把  `add_frameworkdirs("/xxx/frameworkdir", "/tmp/xxx")` 你可以试下。。
