### ISSUE TITLE
compile_commands.json

### ISSUE THREAD

**Issue by 745275633** [tboox/xmake#133]
Support generate `compile_commands.json`?

In cmake, it is `CMAKE_EXPORT_COMPILE_COMMANDS`

**Comment by waruqi** [comment]
You can write a custom script or plugin task to export it by calling `core.tool.compiler` module. for example:

```lua
target("xxx")
    after_build(function (target)
        import("core.tool.compiler")
        for sourcekind, sourcebatch in pairs(target:sourcebatches()) do
            for index, sourcefile in ipairs(sourcebatch.sourcefiles) do
                local command = compiler.compcmd(sourcefiles, sourcebatch.objectfiles[index], {target = target, sourcekind = sourcekind})
                print(command)
            end
        end
    end)
```

Or You can write a custom plugin named `export_cmds` and run this plugin to export it.

Define plugin task
```lua
target("export_cmds")
    set_category("plugin")
    on_run(function()
         -- export cmds
         -- TODO
    end)
    set_menu(...)
```

Run command:

```console
xmake export_cmds -o /tmp/xxxx.txt
```

You can see [write a custom plugin](http://xmake.io/#/plugins?id=quick-start) about the plugin development.

Related extension modules:

* [core.tool.compiler](http://xmake.io/#/manual?id=core-tool-compiler)
* [core.tool.linker](http://xmake.io/#/manual?id=core-tool-linker)
* [core.project.project](http://xmake.io/#/manual?id=project-target1)
* [core.project.task](http://xmake.io/#/manual?id=core-project-task)

**Comment by 745275633** [comment]
I try, but it is a error on `local command = compiler.compcmd(sourcefiles, sourcebatch.objectfiles[index], {target = target, sourcekind = sourcekind})`

```
error: /usr/share/xmake/core/base/os.lua:592: /usr/share/xmake/core/tool/compiler.lua:86: assertion failed!
stack traceback:
    [C]: in function 'assert'
    [/usr/share/xmake/core/tool/compiler.lua:86]: in function 'load'
    [...xmake/core/sandbox/modules/import/core/tool/compiler.lua:57]: in function 'compcmd'
    [/data/datsd/program/factorio/Factorio-Mod-info/xmake.lua:24]: in function 'script'
    [/usr/share/xmake/actions/build/builder.lua:55]: in function '_build_target'
    [/usr/share/xmake/actions/build/builder.lua:77]: in function '_build_target_and_deps'
    [/usr/share/xmake/actions/build/builder.lua:143]: in function 'build'
    [/usr/share/xmake/actions/build/main.lua:73]:

stack traceback:
    [C]: in function 'error'
    [/usr/share/xmake/core/base/os.lua:592]: in function 'raise'
    [/usr/share/xmake/core/sandbox/modules/os.lua:419]: in function 'raise'
    [/usr/share/xmake/actions/build/main.lua:82]: in function 'catch'
    [/usr/share/xmake/core/sandbox/modules/try.lua:104]: in function 'try'
    [/usr/share/xmake/actions/build/main.lua:69]:
    [C]: in function 'load'
    [/usr/share/xmake/core/project/task.lua:426]: in function 'run'
    [/usr/share/xmake/core/main.lua:203]:
```

**Comment by waruqi** [comment]
Please update xmake to master version and try it again. I will update document in the next version (v2.1.5).

**Comment by 745275633** [comment]
```
link libxmaker.a
make demo
make[3]: 警告: jobserver 不可用: 正使用 -j1。添加 “+” 到父 make 的规则。
ccache compile.r xmake.c
link demo.b
make[3]: *** [/home/datsd/.cache/pacaur/xmake-git/src/xmake/core/suffix.mak:304：demo.b] 错误 1
make[2]: *** [/home/datsd/.cache/pacaur/xmake-git/src/xmake/core/suffix.mak:304：SUB_PROS_demo_all] 错误 2
make[1]: *** [makefile:41：all] 错误 2
make: *** [makefile:49：build] 错误 2
==> 错误： 在 build() 中发生一个错误。
```

**Comment by waruqi** [comment]
Please run `./script/get.sh __local__` to compile and install xmake and run the following command to get verbose error info if fails:

```console
$ cd core
$ make output
```

**Comment by 745275633** [comment]
为什么我要使用 `script/get.sh`，错误提示和 `make build` 之后进入 `core` 执行 `make output` 一样。

[`make output` result](https://cfp.vim-cn.com/cbds2)

**Comment by waruqi** [comment]
这两个都可以。。只是安装位置不一样，`script/get.sh`会自动安装，并且不需要sudo，如果你之前一直是 `make build`的，那就还是用这个吧。。

执行`make output`后，还是上面的那些错误信息，没有更多提示信息吗？你这边是什么系统环境，之前的版本编译没有问题吗？

如果你现在的版本是2.1.4之前的老版本，可以先改成下面试下（主要就是`compiler.compcmd`后两个参数传参上在新版本有些变动，所以尽量用新版本）：

```lua
target("xxx")
    after_build(function (target)
        import("core.tool.compiler")
        for sourcekind, sourcebatch in pairs(target:sourcebatches()) do
            for index, sourcefile in ipairs(sourcebatch.sourcefiles) do
                local command = compiler.compcmd(sourcefile, sourcebatch.objectfiles[index], target, sourcekind)
                print(command)
            end
        end
    end)
```

**Comment by 745275633** [comment]
错误信息是 [`make output` result](https://cfp.vim-cn.com/cbds2)
`xmake --version` 的结果是 `v2.1.5.201706041804`

**Comment by waruqi** [comment]
或者这样吧 后两天 我写个导出工程所有信息到 文件的通用扩展模块， 里面包含工程所有target的各种属性和编译链接信息 。。

之前也有用户写vim插件跟xmake 交互，需要通过这种方式交互工程的配置信息。。所以独立封装和模块 应该还是蛮有用的。。

**Comment by 745275633** [comment]
之前一直是 `pacaur -Syu`, 用的 `xmake-git`

**Comment by 745275633** [comment]
不过为什么编译不了 xmake

**Comment by waruqi** [comment]
这个错误可能是你这gcc版本大于6.0 默认启用pie了 但是内置的tbox库是用老的gcc版本编译的 没启用pie 导致最后链接的时候不兼容了这个问题我至少应该修复过  我再看看如何解决

**Comment by 745275633** [comment]
老版本的代码可以的，你确定是 **2.1.4之前的老版本**?

**Comment by waruqi** [comment]
一开始贴的那段代码 是我最近刚重构compiler.compcmd 才做的修改 之前安装的2.1.5 master版本 也可能是看的方式

**Comment by 745275633** [comment]
`compile_commands.json` 的格式在 https://clang.llvm.org/docs/JSONCompilationDatabase.html，clang-tidy 会用到，导出 `compile_commands.json` 可以加入 xmake

**Comment by 745275633** [comment]
[Re: 你最近升级过gcc? 现在gcc版本多少？] Archlinux ^_^, gcc 版本 `7.1.1 20170630`

**Comment by waruqi** [comment]
好的。在2.1.5的新版本中，我会考虑加上这个导出的扩展接口，放置到 `modules` 目录下，通过`import`导入后使用就行了，不过需要稍微等上一会，最近刚重构好新版本，还有点不稳定，正在优化中。。

**Comment by waruqi** [comment]
> [Re: 你最近升级过gcc? 现在gcc版本多少？] Archlinux ^_^, gcc 版本 7.1.1 20170630

看来确实gcc版本太新了导致，之前只在gcc6上测试过， gcc7还没测试过，之后我看看怎么修复下。。

现在你可以先用我刚提供的老的代码方式先试试，也就最后两个参数的传参上有些变动，其他没有任何改动。。

**Comment by waruqi** [comment]
@745275633 我dev分支上，已经加上对 `compile_commands.json`的支持了，可以运行命令：

```console
$ xmake project -k compile_commands
```
在当前工程目录下生成`compile_commands.json`

或者指定输出目录：

```console
$ xmake project -k compile_commands -o /tmp/dir
```

或者指定工程目录：

```console
$ xmake -P projectdir project -k compile_commands -o /tmp/dir
```

`xmake project` 为工程生成插件，之前可以生成`makefile`, `vs201x`等各种IDE工程文件，现在增加对 clang的 `compile_commands.json`格式文件生成。。

如果要在 `xmake.lua` 进行调用，可以通过`core.project.task`模块：

```lua
target("xxx")
    after_build(function (target)
        import("core.project.task")
        task.run("project", {kind = "compile_commands", outputdir = "tmp/dir"})
    end)
```

**Comment by 745275633** [comment]
我需要回复吗？

2017-07-19 15:36 GMT+08:00 ruki <notifications@github.com>:

**Comment by waruqi** [comment]
@745275633 你这边测试可用吗？ok的话。。我就close 这个issues了。。

**Comment by 745275633** [comment]
我以为是你本地分支

---
编译错误，看起来和上次一样

**Comment by waruqi** [comment]
@745275633 哦 master分支我还没更新，还在dev分支里面，你之前那个编译错误问题 我这边还没环境，所以还没开始修，先把compile_commands的特性实现了，编译错误等我过两天装好环境再修下。。

你可以吧 所有lua脚本覆盖到安装目录下： `/usr/local/share/xmake`，来升级版本进行尝试。。或者临时切换脚本目录，切到新版本上去运行，例如：

```console
$ export XMAKE_PROGRAM_DIR=newver_xmake_projectdir/xmake
$ cd projectdir
$ xmake --version
$ xmake project -k compile_commands
```

**Comment by waruqi** [comment]
好的，后两天我会尝试修下这个编译问题。。

**Comment by 745275633** [comment]
加上 `CC=gcc` 之后前面的用了 `gcc`，

但是出错的这句 `clang -odemo.b xmake.o -m64     -s   -L../luajit -L../xmake -L/home/datsd/.cache/pacaur/xmake-git/xmake/core/pkg/base.pkg/lib/release/linux/x86_64 -L/home/datsd/.cache/pacaur/xmake-git/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64    -lxmaker -lluajitr -ltbox -lreadline -lm -ldl -lpthread  2> /tmp/xmake.out` 还是用的 `clang`

**Comment by 745275633** [comment]
加上 `CC=gcc` 之后前面的用了 `gcc`，

但是出错的这句 `clang -odemo.b xmake.o -m64     -s   -L../luajit -L../xmake -L/home/datsd/.cache/pacaur/xmake-git/xmake/core/pkg/base.pkg/lib/release/linux/x86_64 -L/home/datsd/.cache/pacaur/xmake-git/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64    -lxmaker -lluajitr -ltbox -lreadline -lm -ldl -lpthread  2> /tmp/xmake.out` 还是用的 `clang`

**Comment by 745275633** [comment]
我进入 `core/src/demo` 手动执行了 `gcc -odemo.b xmake.o -m64 -s -L../luajit -L../xmake -L/home/datsd/.cache/pacaur/xmake-git/xmake/core/pkg/base.pkg/lib/release/linux/x86_64 -L/home/datsd/.cache/pacaur/xmake-git/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64 -lxmaker -lluajitr -ltbox -lreadline -lm -ldl -lpthread 2> /tmp/xmake.out` （把 `clang` 换成了 `gcc`) 编译通过了。但是我怎么继续编译。

**Comment by waruqi** [comment]
`CC=gcc`只是替换了编译器，你可以再加上`LD=gcc`或者`LD=g++`替换下链接器。

```console
$ export CC=gcc
$ export LD=gcc
$ make build
$ sudo make install
```

**Comment by 745275633** [comment]
可以了（为什么默认是 `clang`）

---
`xmake project -k compile_commands` 报错 `error: the project kind(compile_commands) is not supported!`

**Comment by waruqi** [comment]
因为个人比较习惯clang 所以默认检测到clang后 就用clang编译xmake了

你确定下载的是dev分支的代码？看错误提示还是老版本 没这插件 master上还没更新哦

**Comment by 745275633** [comment]
喜欢 clang 还没让 clang 编译通过

---
是dev分支的代码，不过忘 pull 了。

---

xmake project -k compile_commands 是生成了 compile_commands.json，但是没我要的 `-std` 参数

**Comment by waruqi** [comment]
> 喜欢 clang 还没让 clang 编译通过
这个clang编译的错误之后我会修下的

> xmake project -k compile_commands 是生成了 compile_commands.json，但是没我要的 -std 参数

这个是根据xmake.lua的配置来的，你先确认下有没有设置类似：`add_cxflags("-std=c11")`，或者`set_languages("c11")`的配置。

如果有设置，然后可以运行下 `xmake -v` 编译，看看输出的详细编译参数里面有没有带上 `-std`？

**Comment by 745275633** [comment]
我在设置了 `set_languages("gnu++14")` 而不是 `gnuxx14`，现在行了

**Comment by waruqi** [comment]
当初就这么设计的，什么原因我也忘了，现在就不改了。。

**Comment by 745275633** [comment]
全加上

**Comment by 745275633** [comment]
全加上

**Comment by waruqi** [comment]
linux上我改了下，优先采用gcc来编译 core 来解决链接问题，已入master，2.1.6版本，你这编译安装应该不需要改CC, LD了
