### ISSUE TITLE
一个目标构建失败后,不做任何改动再次构建行为不正常.

### ISSUE THREAD

**Issue by llxwj** [tboox/xmake#135]
构建target失败后,不做任何相关依赖的源码文件和xmake.lua文件的改动,再次xmake,应该还是报此target构建失败的信息,但是实际使用时,就不再出现此target构建失败的信息了.

**Comment by waruqi** [comment]
我尝试修复了下，你再试试。。

**Comment by llxwj** [comment]
拉取最新代码编译测试,行为正常了.
