### ISSUE TITLE
依赖性检测问题 导致每次都重新编译所有target

### ISSUE THREAD

**Issue by ranwei1025** [tboox/xmake#137]
exe依赖于多个lib 反过来lib是独立的 现在只修改exe的xmake配置 可以肯定不会影响lib的配置 但每次都是全部再编译一遍 期望只对exe 重新编译和链接 而不是所有库

**Comment by waruqi** [comment]
已改进，请再试下。。

当`xmake.lua`发生变化后，现在会去检测每个文件最后的编译选项、链接选项是否改变，如果没变的话，就不需要重新build了。。
