### ISSUE TITLE
编译时候出现2个错误怎么能解决阿bad CPU type in executable: ./hello

### ISSUE THREAD

**Issue by tiger0011** [tboox/xmake#139]
第一个问题：bad CPU type in executable: ./hello

第二个问题：error: execv(build/hello) failed(-1)!

执行步骤；
xmake create -l c -P ./hello
cd hello
xmake
xmake r

**Comment by waruqi** [comment]
请加上`-v`重新编译下，给我看下详细的 编译参数信息：`$ xmake -r -v`
