### ISSUE TITLE
debug error use vsjitdebugger.exe

### ISSUE THREAD

**Issue by tangaoo** [tboox/xmake#141]
λ xmake r -d
error: execv(C:\windows\system32\vsjitdebugger.exe build\libc.exe) failed(-2147467260)!

**Comment by waruqi** [comment]
这边测试ok，你加载起来后 得点下 调试关联才行。。或者你可以指定加载其他调试器：

```console
$ xmake f --debugger=windbg.exe
$ xmake r -d
```

或者干脆直接打开调试器加载程序进行调试。。
