### ISSUE TITLE
os.getenv在环境变量中存在中文时获取到的值长度不对

### ISSUE THREAD

**Issue by xigalto** [tboox/xmake#142]
如题，应该是内部字符串计算长度的时候的问题，英文的是对的

**Comment by waruqi** [comment]
是windows还是其他系统下有问题？ 如果是windows，确实有点问题，我已经修复，可以尝试重新从release上下载安装2.1.6版本试试

**Comment by xigalto** [comment]
win10系统，我用的就是最新的2.1.6的。那应该是还没修复好这个问题

**Comment by waruqi** [comment]
能否具体描述下是什么问题？环境变量值是多少，通过getenv获取到的内容，长度是多少？期望长度值等。。我好针对性测试下

**Comment by xigalto** [comment]
key:IEO_SDK_PATH
value:E:\代码\self\LibHelper\
得到的实际内容是  E:\代码\self\LibHelpe
少了后面两个字节，所以我怀疑是你用unicode的方式得到的长度来截取了字符串的值。

**Comment by waruqi** [comment]
我这边再xp和win10上测试ok，你确定有更新最新的2.1.6版本？ 在你提issues反馈问题后，我修复了此问题，并且重传了2.1.6的安装包，需要重新安装下的。。

```console
C:> xmake l -c "print(os.getenv(\"TEST\"))"
E:\代码\self\LibHelper
```

**Comment by xigalto** [comment]
刚下载了最新的果然好了，是我没更新到的原因：）
