### ISSUE TITLE
assertion failed when first building

### ISSUE THREAD

**Issue by ssjia** [tboox/xmake#143]
D:\LunaEngine>xmake f -a x64 -m debug -c
checking for the Microsoft Visual Studio (x64) version ... 2017

D:\LunaEngine>xmake build --backtrace -v
configure
{
    arch = x64
,   ccache = true
,   mode = debug
,   plat = windows
,   kind = static
,   buildir = build
,   vs = 2017
,   clean = true
,   host = windows
}

checking for the cl.exe ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the ccache ... no
error: D:\Windows\xmake/core/sandbox/modules/string.lua:44: assertion failed!
stack traceback:
    [C]: in function 'assert'
    [D:\Windows\xmake/core/sandbox/modules/string.lua:44]: in function 'vformat'
    [D:\Windows\xmake\core\sandbox\modules\os.lua:302]: in function 'iorun'
    [D:\Windows\xmake\modules\detect\tools\find_cl.lua:46]:
    [C]: in function 'load'
    [...re\sandbox\modules\import\lib\detect\find_programver.lua:79]: in function 'find_programver'
    [D:\Windows\xmake\modules\detect\tools\find_cl.lua:55]: in function 'find_tool'
    [D:\Windows\xmake\modules\lib\detect\find_tool.lua:36]: in function '_find_from_modules'
    [D:\Windows\xmake\modules\lib\detect\find_tool.lua:80]: in function 'find_tool'
    [D:\Windows\xmake\modules\lib\detect\has_flags.lua:52]: in function 'has_flags'
    [D:\Windows\xmake/core/tool/builder.lua:74]: in function '_mapflag'
    [D:\Windows\xmake/core/tool/builder.lua:92]: in function '_mapflags'
    [D:\Windows\xmake/core/tool/builder.lua:233]: in function '_addflags_from_target'
    [D:\Windows\xmake/core/tool/compiler.lua:264]: in function 'compflags'
    [D:\Windows\xmake\actions\build\kinds\object.lua:160]: in function '_build_object'
    [D:\Windows\xmake\actions\build\kinds\object.lua:213]:

The project seems to be built successfully.

**Comment by waruqi** [comment]
Are you using the master version on windows? I have fixed this problem on master branch and please try it again.

By the way, you can run `xmake --backtrace -v` to build project without the `build` action.

**Comment by ssjia** [comment]
First time, I install by
`Invoke-Expression (Invoke-Webrequest 'https://raw.githubusercontent.com/tboox/xmake/master/scripts/get.ps1' -UseBasicParsing).Content`

Now, I pull the master branch and it works. Thanks 👍

**Comment by waruqi** [comment]
😄
