### ISSUE TITLE
bundle

### ISSUE THREAD

**Issue by libyyu** [tboox/xmake#147]
Mac下怎么编译.bundle库啊，unity下使用的是.bundle库而非dylib

**Comment by waruqi** [comment]
bundle打包暂时不支持，你可以自定义`on_package` 或者 `after_build`在生成完 dylib后，打包成bundle

```lua
target("xxx")
    after_build(function (target)
        -- 调用os.exec执行外部命令，进行bundle打包
    end)
```

对于具体如何打包bundle，你可以自己建个生成bundle的空xcode工程，看下编译输出的具体命令，或者百度下，然后在前面的脚本中，使用`os.exec`进行打包。。

**Comment by waruqi** [comment]
看了下 .bundle 就只是的文件夹，里面包含各种资源、info.plist等各种文件，你可以自己组织构造下，或者按照上面说的 自定义脚本上，自己构造。。

可参考xcode里面的构建方式。

![snip20171108_24](https://user-images.githubusercontent.com/151335/32538281-10dc3564-c42b-11e7-93d5-0f300f9031c0.png)

**Comment by waruqi** [comment]
我bundle支持上了，可以更新到dev分支试试

```lua
add_rules("mode.debug", "mode.release")

target("test")
    add_rules("xcode.bundle")
    add_files("src/test.m")
    add_installfiles("src/Info.plist")
    --set_values("xcode.codesign_identity", "Apple Development: xxx@gmail.com (T3NA4MRVPU)")
```

也可以通过模板创建空工程：

```console
xmake create -t bundle -l objc test
```

目前签名还没完全弄好，回头我加上，不过对于mac上使用目前应该没啥大问题，你可以先试试

**Comment by waruqi** [comment]
恩，我稍微改进了下，info.plist统一放置到 add_files里面去，add_installfiles用于resources文件的安装
