### ISSUE TITLE
the shflags "/DEF:xxx.def" don't work

### ISSUE THREAD

**Issue by lidroid** [tboox/xmake#153]
add .def file for export symbols with dll library, but checking for shflags failed: fatal error LNK1120: 1 个无法解析的外部命令

**Comment by waruqi** [comment]
you can download and install the dev vesion [xmake-v2.1.9-dev](https://github.com/tboox/xmake/releases/download/v2.1.8/xmake-v2.1.9-dev.exe) and add `force` argument to force to set shflags. It will skip checking.

```lua
add_shflags("/DEF:xxx.def", {force = true})
```

**Comment by lidroid** [comment]
@waruqi thanks, works fine.

**Comment by waruqi** [comment]
We can remove `{force = true}` in newest version now.

```lua
add_shflags("/DEF:xxx.def")
```

**Comment by waruqi** [comment]
现在dev上可以直接添加def文件了 `add_files("module.def")`
