### ISSUE TITLE
建议release时提供一个绿色版本

### ISSUE THREAD

**Issue by junhwong** [tboox/xmake#154]
建议release时提供一个zip的绿色版本，不然每次安装时杀毒软件提示修改注册表。。。
乍一看， 心慌！！！

**Comment by waruqi** [comment]
就是绿色的 仅仅只是解压了一下 然后设置下path全局环境变量 可能这一步被拦截了。。不放心的话 你可以看下安装脚本 [installer.nsi](https://github.com/tboox/xmake/blob/master/scripts/installer.nsi) 。被杀毒软件报正常的 。。需要到各大杀毒软件那申请过白。。很麻烦的。。

**Comment by junhwong** [comment]
嗯，明白。 
绿色版 可以只包含 xmake 自己，不用安装/卸载 ， path这些就自己设置就行了，升级下载一个覆盖就行了...

当然这只是一个建议。

**Comment by waruqi** [comment]
可以 后两天我可以上传一个zip包 用户自己设置path路径。。

**Comment by waruqi** [comment]
你试试下载这个[v2.1.9-dev.zip](https://github.com/tboox/xmake/releases/download/v2.1.8/xmake-v2.1.9-dev.zip)包，解压到自己的安装目录后，自己设置下全局path路径就行了。。

**Comment by junhwong** [comment]
我现在是安装好了的，配合 vscode 很好用。
只是这次升级使用脚本杀毒软件提示，才提的建议。
谢谢你 @waruqi  的贡献， xmake 很不错！

**Comment by waruqi** [comment]
嗯嗯。如果后续有使用上的问题，欢迎提issues 😄
