### ISSUE TITLE
如何添加类似/Zc:wchar_t的编译选项?

### ISSUE THREAD

**Issue by lubocheng** [tboox/xmake#156]
请问,编译C++代码时如何添加以下选项??测试add_cxxflags等接口不成功
![image](https://user-images.githubusercontent.com/3746672/35484219-f0617446-0487-11e8-87d9-b9d0df1b0521.png)

**Comment by waruqi** [comment]
我这边测试了下，能够正常加上：`add_cxflags("/Zc:wchar_t")`

你可以加上后，带上`-v`运行构建：`xmake -r -v`, 看看有没有正常传入cl.exe。。

```
checking for the flags(cl.exe) /Zc:wchar_t ... ok
[00%]: compiling.release src\main.c
cl.exe -c -Ox -fp:fast /Zc:wchar_t -nologo -Gd -MP4 -D_MBCS -D_CRT_SECURE_NO_WARNINGS -Fobuild\\.objs\\hello\\src\\main.c.obj src\\main.c
```

只要你的vc支持这个选项，基本上自动flags检测都会通过，然后传入cl.exe，如果检测不通过，可以装下2.19-dev版本，然后可以强制设置后再试试：`add_cxflags("/Zc:wchar_t", {force = true})`，这个不会启用flags自动检测。。

如果还不行，请贴下`xmake -v`后的详细log，我看看。。
