### ISSUE TITLE
Error In Generating Debug Symbols

### ISSUE THREAD

**Issue by HesamR** [tboox/xmake#157]
I'm trying to build my project but i'm getting an error.  xmake version: 2.1.9

**This is xmake.lua file:**

```
set_targetdir("$(projectdir)/Binaries/$(mode)/$(arch)")
set_objectdir("$(projectdir)/Intermediate/$(mode)/$(arch)")

if is_mode("debug") then
    set_symbols("debug")
    set_optimize("none")
end

if is_mode("release") then
    set_symbols("hidden")
    set_optimize("fastest")
    set_strip("all")
end`

target("Engine")
    set_kind("static")
    add_files("Source/Engine/Core/*.cpp")
```

**This is the Error :**

Source\Engine\Core\Core_1.cpp: fatal error C1041: cannot open program database 'C:\Projects\LevelUp\Binaries\debug\x86\Engine.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS

When I remove these lines I won't get the error anymore.

```
set_targetdir("$(projectdir)/Binaries/$(mode)/$(arch)")
set_objectdir("$(projectdir)/Intermediate/$(mode)/$(arch)")
```

**Comment by waruqi** [comment]
This is because the output directory of the pdb symbol file does not exist causing the cl.exe compiler cannot open and write this file directly.

I have fixed this problem, you can download [xmake-v2.1.9](https://github.com/tboox/xmake/releases/download/v2.1.9/xmake-v2.1.9.exe) and try it again.
