### ISSUE TITLE
why I got many " undefined reference to " during linking?

### ISSUE THREAD

**Issue by zzzh** [tboox/xmake#163]
After some efforts, I got my project cross-compiled in ubuntu, but can't pass link.
there are 2 folders in my project folder, one call lib and another test, there are more folders inside them, here's the xmake.lua I wrote:

target("lib")
    set_kind("static")
    add_files("lib/*.c", "lib/atcacert/*.c", "lib/basic/*.c", "lib/crypto/*.c", "lib/hal/*.c", "lib/host/*.c", "lib/jwt/*.c", "lib/tls/*.c")

target("test")
    set_kind("binary")
    add_files("test/*c", "lib/atcacert/*.c", "lib/jwt/*.c", "lib/tls/*.c")
    add_deps("lib")

also added --includedirs="lib" --linkdirs="lib" in xmake config command.

any ideas why I got many " undefined reference to " during linking?

**Comment by zzzh** [comment]
There were some errors in my xmake.lua, here's the changed version:

target("lib")
    set_kind("static")
    add_files("lib/*.c", "lib/atcacert/*.c", "lib/basic/*.c", "lib/crypto/*.c", "lib/crypto/hashes/*.c", "lib/hal/*.c", "lib/host/*.c", "lib/jwt/*.c", "lib/tls/*.c")
    add_linkdirs(".", "./atcacert", "./basic", "./crypto", "./crypto/hashes", "./hal", "./host",  "./jwt",  "./tls")

target("test")
    set_kind("binary")
    add_files("test/*c", "test/atcacert/*.c", "test/jwt/*.c", "test/tls/*.c")
    add_deps("lib")

here's the linking output:
[100%]: linking.release test
error: output/.objs/test/test/cmd-processor.c.o: In function `do_randoms':
cmd-processor.c:(.text+0x6c0): undefined reference to `atcab_bin2hex'
output/.objs/test/test/cmd-processor.c.o: In function `info':
cmd-processor.c:(.text+0x8e8): undefined reference to `atcab_bin2hex'
output/.objs/test/test/cmd-processor.c.o: In function `sernum':
cmd-processor.c:(.text+0x92c): undefined reference to `atcab_bin2hex'
output/.objs/test/test/atca_tests_helper.c.o: In function `TEST_atca_helper_base64_encode_':
atca_tests_helper.c:(.text+0x452): undefined reference to `atcab_b64rules_default'
atca_tests_helper.c:(.text+0x456): undefined reference to `atcab_b64rules_default'
output/.objs/test/test/atca_tests_helper.c.o: In function `TEST_atca_helper_base64_encode_to_dirty_buffer_':
atca_tests_helper.c:(.text+0x4ee): undefined reference to `atcab_b64rules_default'
atca_tests_helper.c:(.text+0x4f2): undefined reference to `atcab_b64rules_default'
output/.objs/test/test/atca_tests_helper.c.o: In function `TEST_atca_helper_base64_decode_':
atca_tests_helper.c:(.text+0x58a): undefined reference to `atcab_b64rules_default'
output/.objs/test/test/atca_tests_helper.c.o:atca_tests_helper.c:(.text+0x58e): more undefined references to `atcab_b64rules_default' follow
output/.objs/test/test/atca_tests_helper.c.o: In function `TEST_atca_helper_base64_url_encode_':
atca_tests_helper.c:(.text+0xb86): undefined reference to `atcab_b64rules_urlsafe'
atca_tests_helper.c:(.text+0xb8a): undefined reference to `atcab_b64rules_urlsafe'
output/.objs/test/test/atca_tests_helper.c.o: In function `TEST_atca_helper_base64_url_decode_':
atca_tests_helper.c:(.text+0xc2a): undefined reference to `atcab_b64rules_urlsafe'
atca_tests_helper.c:(.text+0xc2e): undefined reference to `atcab_b64rules_urlsafe'
output/.objs/test/test/atcacert/test_atcacert_client.c.o: In function `TEST_atcacert_client_atcacert_client__init_':
test_atcacert_client.c:(.text+0x650): undefined reference to `atcab_bin2hex'
test_atcacert_client.c:(.text+0x6bc): undefined reference to `atcab_bin2hex'
test_atcacert_client.c:(.text+0x728): undefined reference to `atcab_bin2hex'
test_atcacert_client.c:(.text+0x7c6): undefined reference to `atcab_bin2hex'
test_atcacert_client.c:(.text+0x864): undefined reference to `atcab_bin2hex'
output/.objs/test/test/atcacert/test_atcacert_client.c.o:test_atcacert_client.c:(.text+0xeb6): more undefined references to `atcab_bin2hex' follow
output/liblib.a(atca_helpers.c.o): In function `atcab_base64encode':
atca_helpers.c:(.text+0x9a6): undefined reference to `atcab_b64rules_default'
atca_helpers.c:(.text+0x9aa): undefined reference to `atcab_b64rules_default'
output/liblib.a(atca_helpers.c.o): In function `atcab_base64decode':
atca_helpers.c:(.text+0x9d6): undefined reference to `atcab_b64rules_default'
atca_helpers.c:(.text+0x9da): undefined reference to `atcab_b64rules_default'
output/liblib.a(atca_jwt.c.o): In function `atca_jwt_init':
atca_jwt.c:(.text+0xc8): undefined reference to `atcab_b64rules_urlsafe'
atca_jwt.c:(.text+0xcc): undefined reference to `atcab_b64rules_urlsafe'
output/liblib.a(atca_jwt.c.o): In function `atca_jwt_finalize':
atca_jwt.c:(.text+0x244): undefined reference to `atcab_b64rules_urlsafe'
atca_jwt.c:(.text+0x248): undefined reference to `atcab_b64rules_urlsafe'
atca_jwt.c:(.text+0x318): undefined reference to `atcab_b64rules_urlsafe'
output/liblib.a(atca_jwt.c.o):atca_jwt.c:(.text+0x31c): more undefined references to `atcab_b64rules_urlsafe' follow
collect2: error: ld returned 1 exit status

**Comment by zzzh** [comment]
Any ideas on it?

**Comment by waruqi** [comment]
In which library are these symbols defined?

**Comment by zzzh** [comment]
yeah, I think so

**Comment by waruqi** [comment]
> any ideas why I got many " undefined reference to " during linking?

This has nothing to do with xmake. You can add `-v` to get detail link command to debug. for example: 

```console
$ xmake -v
```
And use `nm liblib.a | grep "undef symbol"`  to verify that the symbol definition exists.
