### ISSUE TITLE
bug in plugin system, or by design?

### ISSUE THREAD

**Issue by wangii** [tboox/xmake#166]
I tried to create a plugin in the simplest form:
```lua

task("h2")

    set_category("plugin")

    on_run(function ()

        print("h2 $(buildir)")

    end)
task_end()
```

two problems:
- without set_menu it just doesn't work `xmake h2`
- $(buildir) not working, $(projectdir) does though.

**Comment by waruqi** [comment]
You need to set the options menu to enable command line execution, otherwise it can be called only as an internal task within the project file (xmake.lua)

```lua
task("h2")

    set_category("plugin")

    on_run(function ()

        print("h2 $(buildir)")

    end)

    set_menu {
                -- usage
                usage = "xmake h2 [options]"

                -- description
            ,   description = "xxxxxxxxx!"

                -- options
            ,   options = {}
            }
```

**Comment by waruqi** [comment]
You can see: http://xmake.io/#/plugins?id=quick-start

**Comment by wangii** [comment]
got it. thanks!
