### ISSUE TITLE
error: cannot get program for __rule_yasmd

### ISSUE THREAD

**Issue by sunqi1993** [tboox/xmake#170]
## xmake.lua
```
rule("yasmd")
    set_extensions(".S")
    on_build_file(
                function (target, sourcefile)
                    os.vrun("yasm -Iinclude -f bin -o %s %s",
                    path.join(target:targetdir(),path.basename(sourcefile)..".bin"),sourcefile)
                end)

target("loader")
    set_kind("static")
    -- add_rules("yasmd")
    add_files("loader.S",{rule="yasmd"})

target("mbr")
    set_kind("static")
    -- add_rules("yasmd")
    add_files("mbr.S",{rule="yasmd"})

```
## project structure
.
├── include
│   └── boot.inc
├── loader.S
├── mbr.S
└── xmake.lua

## source code
[boot.zip](https://github.com/tboox/xmake/files/1953664/boot.zip)

**Comment by waruqi** [comment]
I have fixed this problem, please download [xmake-v2.2.1-dev](https://github.com/tboox/xmake/releases/download/v2.1.9/xmake-v2.2.1-dev.exe) or checkout dev branch and try it again.
