### ISSUE TITLE
使用xmake r 每次都会运行生成工程中全部的moc文件

### ISSUE THREAD

**Issue by KellyGodLv** [tboox/xmake#171]
应该在文件修改后才重新生产moc文件,加快编译过程

**Comment by waruqi** [comment]
好的，之后我改进下

**Comment by waruqi** [comment]
我改进了下，你再试试，[xmake-v2.2.1-dev](https://github.com/tboox/xmake/releases/download/v2.1.9/xmake-v2.2.1-dev.exe)
