### ISSUE TITLE
Does xmake have more detailed documentation on generating visual studio project files?

### ISSUE THREAD

**Issue by j7252008** [tboox/xmake#175]
I want to set more detail options such as lib(dynamic) path and create VS filter folder.

**Comment by waruqi** [comment]
You can see [https://xmake.io/#/plugins?id=generate-visualstudio-project](https://xmake.io/#/plugins?id=generate-visualstudio-project).

xmake focus on building project directly, so there are not too many VS-related special configurations for .vcproj file. 

You can add `add_linkdirs("xxx")` to add search directory for linking static/dynamic library.

But we can not configure vs filter folder now.

**Comment by j7252008** [comment]
Thank you for your help,I means set path of  lib(dynamic),not in same directory with dll. By the way, I think xmake work with editor such as vscode is powerful and cool,especially on linux . Let me explain why I ask for .vcproj file cinfigurations, when we develop on windows， we choose ide like VS，we need to init .vcxproj file to default（because some beginner always make mistake on  config）,but i'll try to recommend xmake in our project.

**Comment by waruqi** [comment]
> I means set path of lib(dynamic),not in same directory with dll.

I'm sorry, I still don't know what you mean. Can you explain it in detail?

**Comment by j7252008** [comment]
You know on windows,  dynamic library will generate two files, .lib and .dll,   .lib file path can be set on VS,called Import library， It's postion in VS is Link->Advance. so I mean this path can be set different with .dll file. I read manual but I can't find it

**Comment by waruqi** [comment]
You can add `add_linkdirs("xxxx/libdir")` for the .lib file.
