### ISSUE TITLE
Build SDL 2 for mobile!

### ISSUE THREAD

**Issue by hamad-almamari** [tboox/xmake#176]
Hello I just like how this project is easy .
But can any one provide an example to build SDL 2 for mobile targets.

I can not find any info at the web site.

Also how we can sp app icon and android promises (The manifest file )

In direct simple Q . Can I use xmake to build c mobile apps/games

**Comment by waruqi** [comment]
Do you want to build the libsdl source code, or compile the project using the libsdl?

If you just want to compile the project using the libsdl, you can add `add_links("sdl")` in the xmake.lua file.

```lua
target("test")
    set_kind("binary")
    add_files("src/*.c")
    add_links("sdl")
    add_linkdirs("xxx")
```

**Comment by hamad-almamari** [comment]
What about app icon ? and android promises?
