### ISSUE TITLE
msvc和set_optimize的问题

### ISSUE THREAD

**Issue by actboy168** [tboox/xmake#181]
对于msvc，optimize对应的关系为
```
"none"        = "-Od"
"faster"      = "-Ox"
"fastest"     = "-Ox -fp:fast"
"smallest"    = "-O1"
"aggressive"  = "-Ox -fp:fast"
```
没有一个对应O2。O2是visual studio提供的release默认值，也是我认为最合适的选项

**Comment by waruqi** [comment]
我可以把 fastest改成 -O2，或者你这帮忙提交个pr吧

**Comment by actboy168** [comment]
也许可以把faster改成O2，考虑到gcc的faster对应的O2也是大多数release版本的首选选项，这样可以保持一致。

**Comment by actboy168** [comment]
我的意思是对于大多数人，gcc会用O2作为发布版本，msvc也是用O2作为发布版本。我现在是这样写
```
    if is_plat("windows") then
        add_cflags("-O2")
        add_cxxflags("-O2")
    else
        set_optimize("faster")
    end
```

**Comment by waruqi** [comment]
release版本是否用O2 跟set_optimize没有必然关系，fastest 在msvc下 更适合用O2表示，而不是faster，而且在release下set_optimize设置 对用户来讲 已经是摒弃了flags细节，是不需要关心内部到底是O2还是O3，只需要知道当前设置是fastest就足够了。

用户想要强行使用O2作为release，通过set_optimize来操作 本身就是不可控的了，这个属于用户级别的需求了

如果必须要在release下确保使用O2，建议通过add_cxflags("-O2")会更稳妥些。所以你刚贴的设置就这么使用就行了

**Comment by actboy168** [comment]
Ox确实比O2更快，根据
https://msdn.microsoft.com/en-us/library/59a3b321.aspx
https://msdn.microsoft.com/en-us/library/8f8h5cxt.aspx

O2比Ox多了/Gs /GF /Gy三个选项，Gs是一个运行时的安全检查，有性能的损耗
https://msdn.microsoft.com/en-us/library/9598wk25.aspx

**Comment by waruqi** [comment]
嗯，看文档 确实Ox更快 ，那就fastest继续Ox吧，faster改成O2好了，我后两天改下。

**Comment by waruqi** [comment]
这个我也改好了，你试试：https://github.com/tboox/xmake/releases/download/v2.2.1/xmake-v2.2.2-dev.exe

**Comment by actboy168** [comment]
谢谢
