### ISSUE TITLE
_CRT_SECURE_NO_WARNINGS定义冲突

### ISSUE THREAD

**Issue by actboy168** [tboox/xmake#182]
我发现xmake会强制定义_CRT_SECURE_NO_WARNINGS宏，假如我的代码中已经自己定义了_CRT_SECURE_NO_WARNINGS就会冲突。虽然我可以通过改代码的方式来避免这个问题，但我认为xmake不应该这样做？

**Comment by waruqi** [comment]
理论上 是默认加个定义越少越好，但是之前考虑是因为默认不加这些的话，大部分用户编译win项目的时候，都会出各种警告错误，并不是所有用户都会去自己手动设置这些东西。

这个我先考虑下吧，我需要保证默认编译，用户不做任何设置的情况下也能正常编译。

**Comment by waruqi** [comment]
这个我默认去掉了，你试试吧：https://github.com/tboox/xmake/releases/download/v2.2.1/xmake-v2.2.2-dev.exe

**Comment by actboy168** [comment]
谢谢
