### ISSUE TITLE
无法在mingw中使用-static-libgcc

### ISSUE THREAD

**Issue by actboy168** [tboox/xmake#185]
`xmake -v`会看到

```
checking for the flags(g++) -static-libgcc ... no
check error: nul.exe: final close failed: File truncated
collect2.exe: error: ld returned 1 exit status
```

**Comment by waruqi** [comment]
默认会自动检测设置到 add_cxflags add_ldflags的中的flags，如果检测到当前编译器、链接器不支持，就会自动忽略，可能是检测失败了(目前是通过尝试link去检测的，是会有一些误判)

如果确定当前linker是支持这个flags，可以加个force，强制设置：`add_ldflags("-static-libgcc", {force = true})`

**Comment by actboy168** [comment]
嗯，可以了。谢谢
