### ISSUE TITLE
I would like to see this debut in LuaConsole

### ISSUE THREAD

**Issue by tilkinsc** [tboox/xmake#189]
I have my own build situation, but this project is magnificent. I would like to have this project as one of my build options in the program http://github.com/tilkinsc/LuaConsole , or better yet a feature. I am toying around with a few ideas and one of them is to have a preprocessor added to lua (like gcc's) and have yet to integrate lua compiler into my app. Take a look at [build.lua](https://github.com/tilkinsc/LuaConsole/blob/master/build.lua) and [build_func.lua](https://github.com/tilkinsc/LuaConsole/blob/master/build_func.lua) for more information on why I am interested.

**Comment by waruqi** [comment]
Sorry, I do not understand what you want to do, is to use xmake to build your project? You can add xmake.lua in the root directory of your project.
