### ISSUE TITLE
能否让构建目标的顺序与includes的调用顺序一致？（+os.trycp路径问题）

### ISSUE THREAD

**Issue by xigalto** [tboox/xmake#195]
如下脚本，xmake版本是2.2.1
includes("src/xmake.lua")
includes("examples/test1/xmake.lua")
includes("examples/test2/xmake.lua")
我的本意是顺序执行完src及test1、test2，我不想用add_deps的方式，因为我的target使用了set_basename，这样导致add_deps引用的内容找不到。

另外发现个bug os.trycp("...","...") 当第二个参数为类似 "xxxx/xxx1/xxx2/"这样的目录时，如果xxx1不存在，xxx2会被创建成一个文件，从而导致拷贝文件失败

**Comment by waruqi** [comment]
> 我的本意是顺序执行完src及test1、test2，我不想用add_deps的方式，因为我的target使用了set_basename，这样导致add_deps引用的内容找不到。

includes仅仅只是 包含引用xmake.lua，不用于控制构建顺序，target的构建顺序只能通过 add_deps方式来控制

设置set_basename后add_deps无法link到的问题，我记得之前是修复了的（请看：[#177](https://github.com/tboox/xmake/issues/177)），你看看是否为最新master版本，win上看看是否为 https://github.com/tboox/xmake/releases/download/v2.2.1/xmake-v2.2.2-dev.exe 版本

如果确实新版本还有问题，我之后再调试下，这个只是bug，修复了就好，不必为此修改其他接口。

> 另外发现个bug os.trycp("...","...") 当第二个参数为类似 "xxxx/xxx1/xxx2/"这样的目录时，如果xxx1不存在，xxx2会被创建成一个文件，从而导致拷贝文件失败

这个问题，我后两天有时间看看，另外： 建议不同bug和问题，尽量拆分成两个 issues 来提交维护，这样方便日后跟进问题进展。

**Comment by waruqi** [comment]
> 另外发现个bug os.trycp("...","...") 当第二个参数为类似 "xxxx/xxx1/xxx2/"这样的目录时，如果xxx1不存在，xxx2会被创建成一个文件，从而导致拷贝文件失败

这个问题，我刚测了下，这边ok，你是win还是linux?  xmake版本号多少?

**Comment by xigalto** [comment]
是win，版本是2.2.1，可能不是最新的，我去看下。之所以弄成在这里提了下trycp的问题是我觉得只要你知道他存在就可以了，这个问题可以通过先mkdir的方式解决。我去弄个最新的版本试试

**Comment by waruqi** [comment]
哦 可能是win下 你用了反斜杠分隔符 所以会有这问题，可以先改成`xxx\\fff\\`试试，回头我对win下的处理再改进下

另外只要是不同问题 ，尽量单独issues，方便讨论和维护，哪怕只是个小问题

**Comment by waruqi** [comment]
关于win下路径问题，我改进了下，`xxx/fff/`应该也可以了，你可以试试 https://github.com/tboox/xmake/releases/download/v2.2.1/xmake-v2.2.2-dev.exe

**Comment by xigalto** [comment]
可以了，拷贝和依赖的问题已解决，就是拷贝的时候有个检测可以加一下，如果目标路径末尾不带/或者\\，可以给他加一下

**Comment by waruqi** [comment]
> 就是拷贝的时候有个检测可以加一下，如果目标路径末尾不带/或者\，可以给他加一下

不带 `/` 和 `\\`，有可能是文件copy，不能自动追加，目前是根据源文件是否为 dir/file，来自动处理目的路径是否为dir/file
