### ISSUE TITLE
全局的on_install没有了么？

### ISSUE THREAD

**Issue by xigalto** [tboox/xmake#196]
现在这个只能放到target中才能正常进入，我想所有target编译完之后做某些事情该用什么？after_build好像也不能放到全局中

**Comment by waruqi** [comment]
全局支持的 回头我看下

**Comment by waruqi** [comment]
我这边测了下，是ok的，你先确定下，看看是否在 after_build/on_install前面，有未结束的 option()/target() 定义，如果有的话，那么这个就不是全局设置，需要先 option_end()/target_end()结束下才行。。

还是不行的话，请贴下xmake.lua或者给个测试demo，我调下。

**Comment by xigalto** [comment]
刚才去试了下，的确又可以了，应该是我忘记加target_end()了。
