### ISSUE TITLE
使用命令生成vs项目时，如果包含路径中有中文路径，生成的项目中包含路径是乱码

### ISSUE THREAD

**Issue by xigalto** [tboox/xmake#197]
如题，如果使用add_includedirs、add_linkdirs之类添加了包含中文的路径，生成的vs项目中的包含目录、导入库目录的路径会显示为乱码，然后编译的时候就会个乱七八糟的错误，重新修改乱码路径为正常的就不会报错了。

**Comment by xigalto** [comment]
项目文件转换成UTF8的就没毛病了，可能需要创建文件的时候处理下文件格式

**Comment by waruqi** [comment]
确实有问题，应该是win上读取的中文路径，默认是gb2312编码的，然后就直接写入vcproj工程文件了，需要在写入后对工程文件做下转换才行。

这个之后我改进下

**Comment by waruqi** [comment]
我还没修复，就暂时先不用close掉，等修复验证没问题后，再close

**Comment by xigalto** [comment]
嗯，已经ok了。
