### ISSUE TITLE
os.cp,os.trycp中的**通配符，保存文件的时候不会按照原有目录结构拷贝

### ISSUE THREAD

**Issue by xigalto** [tboox/xmake#200]
os.cp,os.trycp中的**通配符，保存文件的时候不会按照原有目录结构拷贝，这个觉得可以改进下。

**Comment by waruqi** [comment]
? 目前仅copy文件本身到目的路径，目的路径不做嵌套层次处理，这些接口的行为方式 不能随意改动，否则会出现向下兼容性问题

**Comment by xigalto** [comment]
嗯了解了，我自己遍历下拷贝好了，这个也是突发奇想做了下这个：）
