### ISSUE TITLE
c++的入口函数用什么方式修改？

### ISSUE THREAD

**Issue by xigalto** [tboox/xmake#202]
用这个add_ldflags("/ENTRY:xxccc")好像没法改变入口函数，我看了下命令行这个没有加到链接选项里，但是设置子系统的/SUBSYSTEM可以正常，ENTRY是不能用这个接口添加还是里面过滤了？

**Comment by waruqi** [comment]
默认有flags自动检测，检测不通过就会忽略，可能这个flags检测失败了 我后面改进下，你可以强制设置下

```lua
add_ldflags("/ENTRY:xxccc", {force = true})
```

**Comment by xigalto** [comment]
嗯，的确是的，刚看到更新日志里有force相关的，然后就看到你也回复了。
