### ISSUE TITLE
生成的vs项目包含目录及库目录路径中有多余的\

### ISSUE THREAD

**Issue by xigalto** [tboox/xmake#203]
附加包含目录应该是c:\xxx 实际保存后是c:\\xxx
附加链接库目录应该是c:\xxxx 实际保存后是c:\\\\xxxx
可能是保存的时候没有去除多余的转义符，建议去掉下。

**Comment by waruqi** [comment]
目前 有对vs项目编译 和 显示 有实际影响吗？

**Comment by xigalto** [comment]
没有影响，这个明天我去阅读下源码，有几个地方稍微要优化下，如果可能到时我改了提交下。

**Comment by waruqi** [comment]
嗯 没影响的话 不改也没啥关系，如果要改的话 你可以用path.translate对路径格式化下

**Comment by waruqi** [comment]
https://github.com/tboox/xmake/pull/205
