### ISSUE TITLE
set_objectdir内置变量的疑问

### ISSUE THREAD

**Issue by xigalto** [tboox/xmake#206]
如下面的示例代码，每个target并不会产生不同的objectdir，即便将set_objectdir放置到target内set_kind后仍然是只有一个值，这个是个bug还是故意这样设置的呢？
`
set_targetdir("$(projectdir)/bin/$(arch)/")
set_objectdir("$(projectdir)/temp/projectname/$(kind)/")
    
target("static")
    set_kind("static")
    -- ...
target_end()

target("shared")
    set_kind("shared")
    -- ...
target_end()
`

**Comment by waruqi** [comment]
目前 `$(kind)` 仅用于 `$ xmake f -k static` 时候的切换，所有 `$(xxx)` 变量其实就是读取的当前工程`$ xmake f `配置

以及用于通过配置修改target的kind

```lua
target("xxxx")
    set_kind("$(kind)")
```

目前就是这么设计的，`$(kind)`是全局配置值，暂时没法根据不同target的kind，自由设置`$(kind)`

**Comment by xigalto** [comment]
但是有点矛盾的地方，如果set_kind无法动态改变当前的编译目标类型的话，那在target中使用set_kind就应该不生效才对。事实是在target中调用set_kind是有效的，能改变目标的生成类型，但是如果使用is_kind来检测的话就无效，这2者之间是不是有域的冲突？
target("xxxx")
    set_kind("shared")
    -- is_kind("shared")返回非，但是实际产生的目标的确是动态库

**Comment by waruqi** [comment]
不是这意思，我是说 is_kind() 还是  `$(kind)` 目前仅支持获取对 `$ xmake f -k [static|shared]`的命令号配置的值，`set_kind("$(kind)")`也是。。。

但是 set_kind("shared") 是直接写死的配置，存于target对象中，暂时不支持 `is_kind()`  `$(kind)` ，因为这两个接口 是直接从 config 中读取的。。
