### ISSUE TITLE
windows中rc文件编译有问题

### ISSUE THREAD

**Issue by xigalto** [tboox/xmake#212]
生成vsproject后
rc的生成文件后缀名是.obj，应该是res。为obj时在vs201x中编译是可以通过的，但是在200x中不行，链接的时候仍然是找的.res，所以会通不过

命令行编译的时候，似乎并没有对rc进行link，不知道是不是我搞错了，我试过几次命令行编译都不行，然后直接加到vsproject中才生效。

**Comment by waruqi** [comment]
命令行编译是可以的，有对rc的完整支持和link，xmake.exe在win的程序本身就是 xmake编译并且link上rc的logo的。。

如果你这不行，可以给个测试demo，我回头调试下。。

**Comment by xigalto** [comment]
[testgrid.zip](https://github.com/tboox/xmake/files/2344356/testgrid.zip)
这个demo用vs打开是可以正常编译并运行的，但是用xmake不行。

**Comment by xigalto** [comment]
[xmake.zip](https://github.com/tboox/xmake/files/2344360/xmake.zip)
对应的mfcrule脚本，替换xmake安装目录下的

**Comment by waruqi** [comment]
好的，我回头调下，mfc这个就不要贴这里了，贴到相关issue里面去吧。。

**Comment by waruqi** [comment]
你给的demo，依赖mfc环境，但是我这暂时没装mfc，测试不了，你可以试试我给你的demo，是可以正常编译link rc文件的。。
[testrc.zip](https://github.com/tboox/xmake/files/2345110/testrc.zip)

另外工程测试目录下也有个完整的例子，是支持 rc 编译的，你也可以试试 https://github.com/tboox/xmake/tree/master/tests/projects/winsdk/usbview

**Comment by waruqi** [comment]
那是编译报错，link报错，还是运行错误呢？有没有错误信息？

**Comment by xigalto** [comment]
刚我看了下usbview这个项目，这个的rc的确没毛病，不过这个用的是win32的库，没有用到mfc相关的。
报错是运行时候crash，位置就是创建对话框的时候挂掉的。

**Comment by waruqi** [comment]
那这个应该跟rc本身的支持没关系，多半还是mfc的环境没支持好导致编译rc的时候，某些mfc相关的defines没设置导致部分资源没编译进去吧。。

我觉得只要把mfc的规则支持完整 应该可以同时解决掉这个问题

**Comment by xigalto** [comment]
嗯我再看下，估计有些是vs编译的时候有默认值，xmake编译的时候没加进去
