### ISSUE TITLE
Need ability to specify ".deps" directory

### ISSUE THREAD

**Issue by rivy** [tboox/xmake#223]
While experimenting with customizing the output directories, I was unable to find an option to change the ".deps" directory. I expected something similar to `set_targetdir( ... )`. Am I missing it somewhere? Or is it not built-in yet?

Thanks.

**Comment by waruqi** [comment]
I have added `set_dependir` api to set the .deps directory for targets.

```lua
set_dependir("$(buildir)/xxx/xxx/.deps")
```

**Comment by rivy** [comment]
It looks good from my local testing.
Thanks!
