### ISSUE TITLE
Add ability to specify new global default for `buildir`

### ISSUE THREAD

**Issue by rivy** [tboox/xmake#224]
I'd like to have the ability to set the build directory name (currently, "build") to a different default, globally.

I usually use a more visibly different directory for builds, such as "#build", so that it doesn't look like a normal repository directory. This is especially problematic for me with the "build" default, which I use commonly in repositories for build scripts.

I know that it can be set on a per configuration basis via `xmake config -o "#build"`, but that means that I have to use that construction instead of just using `xmake` every time I reconfigure the build. So, I'd like to change the *default* value, globally. I envision something like `xmake global --buildir=#build`.

Alternatively, being able to set it within the "xmake.lua" script, being over-ridden by a command line directive such as `xmake config -o "other_build_dir"` would also be a usable alternative. I can almost accomplish this using:

```lua
local build_dir = "#build"
set_targetdir( build_dir.."/bin" )
set_objectdir( build_dir.."/obj" )
set headerdir( build_dir.."/include" ) 
-- .deps location is not settable
```

but it is tedious, error-prone, currently not completely working, and, I believe, overrides user preference (when specifying `-o alt_build_dir`).

**Comment by waruqi** [comment]
I have added `set_config()` api to set the default configuration in xmake.lua. 

```lua
set_config("buildir", "#build")
```

And we can still override the default build directory manually.

```console
$ xmake f -o #build
```

You can update master version or download https://github.com/tboox/xmake/releases/download/v2.2.1/xmake-v2.2.2-dev.exe and try it again.

**Comment by rivy** [comment]
👍 

I'll give it some initial attention tomorrow.

Thanks for the rapid response!

**Comment by rivy** [comment]
It looks good from my local testing.
Both in-script use and command line override work correctly.
Thanks!
