### ISSUE TITLE
windows7 xmake build bad argument error

### ISSUE THREAD

**Issue by fuyunbo** [tboox/xmake#226]
你好，我在windows7系统上使用xmake create test2工程，然后运行xmake build提示如下错误
   error: bad argument #2 to 'gsub' (string/function/table expected)
请问一下这种问题该如何解决呢？

**Comment by waruqi** [comment]
xmake 版本号多少？ 执行下 `xmake  -v --backtrace` 给我看下输出

**Comment by fuyunbo** [comment]
$ xmake -v --backtrace
configure
{
    arch = x86
,   ccache = true
,   cxx = cl.exe
,   mode = debug
,   host = windows
,   ar = link.exe -lib
,   ld = link.exe
,   kind = static
,   buildir = build
,   vs = 2010
,   cc = cl.exe
,   plat = windows
}

warning: cannot match target(libharu).add_files("thirdparty\libharu\src\hpdf_fontdef_base1.c") at E:\workspace\ECGReport\thirdparty\libharu\xmake.lua:9
checking for the flags(cl.exe) -Zi -FS -FdC:\Users\ADMINI~1\AppData\Local\Temp\.xmake\181015\_412BB60A22476D44A55BBD1EC245354E.pdb ... no
check error: D:\Program Files (x86)\xmake/core/base/os.lua:705: cl: 命令行 error D8021 :无效的数值参数“/FS”

stack traceback:
    [C]: in function 'error'
    [D:\Program Files (x86)\xmake/core/base/os.lua:705]: in function 'raise'
    [D:\Program Files (x86)\xmake\core\sandbox\modules\os.lua:327]: in function 'iorunv'
    [... Files (x86)\xmake\modules\detect\tools\cl\has_flags.lua:79]:
[01%]: compiling.debug thirdparty\libharu\src\hpdf_image_png.c
cl.exe -c -Zi -Fdbuild\\windows\\x86\\debug\\libharu.pdb -Od -Ithirdparty\\\\libharu\\\\include -Ithirdparty\\\\libharu\\\\win32\\\\include -DLIBHPDF_HAVE_NOPNGLIB -DLIBHPDF_HAVE_NOZLIB -DLIBHPDF_HAVE_NOPNGLIB=1 -DLIBHPDF_HAVE_NOZLIB=1 -nologo -Fobuild\\.objs\\libharu\\windows\\x86\\debug\\thirdparty\\libharu\\src\\hpdf_image_png.c.obj thirdparty\\libharu\\src\\hpdf_image_png.c
checking for the flags(cl.exe) -Zi -FS -FdC:\Users\ADMINI~1\AppData\Local\Temp\.xmake\181015\_F1805880180C5F4A9913E7C152AD74EF.pdb ... no
check error: D:\Program Files (x86)\xmake/core/base/os.lua:705: cl: 命令行 error D8021 :无效的数值参数“/FS”

stack traceback:
    [C]: in function 'error'
    [D:\Program Files (x86)\xmake/core/base/os.lua:705]: in function 'raise'
    [D:\Program Files (x86)\xmake\core\sandbox\modules\os.lua:327]: in function 'iorunv'
    [... Files (x86)\xmake\modules\detect\tools\cl\has_flags.lua:79]:
[00%]: compiling.debug thirdparty\libharu\src\hpdf_image_ccitt.c
cl.exe -c -Zi -Fdbuild\\windows\\x86\\debug\\libharu.pdb -Od -Ithirdparty\\\\libharu\\\\include -Ithirdparty\\\\libharu\\\\win32\\\\include -DLIBHPDF_HAVE_NOPNGLIB -DLIBHPDF_HAVE_NOZLIB -DLIBHPDF_HAVE_NOPNGLIB=1 -DLIBHPDF_HAVE_NOZLIB=1 -nologo -Fobuild\\.objs\\libharu\\windows\\x86\\debug\\thirdparty\\libharu\\src\\hpdf_image_ccitt.c.obj thirdparty\\libharu\\src\\hpdf_image_ccitt.c
checking for the flags(cl.exe) -Zi -FS -FdC:\Users\ADMINI~1\AppData\Local\Temp\.xmake\181015\_3B7F05BAE1895746B0A7042B1CED78D8.pdb ... no
check error: D:\Program Files (x86)\xmake/core/base/os.lua:705: cl: 命令行 error D8021 :无效的数值参数“/FS”

stack traceback:
    [C]: in function 'error'
    [D:\Program Files (x86)\xmake/core/base/os.lua:705]: in function 'raise'
    [D:\Program Files (x86)\xmake\core\sandbox\modules\os.lua:327]: in function 'iorunv'
    [... Files (x86)\xmake\modules\detect\tools\cl\has_flags.lua:79]:
[00%]: compiling.debug thirdparty\libharu\src\hpdf_encoder_jp.c
cl.exe -c -Zi -Fdbuild\\windows\\x86\\debug\\libharu.pdb -Od -Ithirdparty\\\\libharu\\\\include -Ithirdparty\\\\libharu\\\\win32\\\\include -DLIBHPDF_HAVE_NOPNGLIB -DLIBHPDF_HAVE_NOZLIB -DLIBHPDF_HAVE_NOPNGLIB=1 -DLIBHPDF_HAVE_NOZLIB=1 -nologo -Fobuild\\.objs\\libharu\\windows\\x86\\debug\\thirdparty\\libharu\\src\\hpdf_encoder_jp.c.obj thirdparty\\libharu\\src\\hpdf_encoder_jp.c
checking for the flags(cl.exe) -Zi -FS -FdC:\Users\ADMINI~1\AppData\Local\Temp\.xmake\181015\_5BB9689C56B9524A8E88B16E8CE2EA58.pdb ... no
check error: D:\Program Files (x86)\xmake/core/base/os.lua:705: cl: 命令行 error D8021 :无效的数值参数“/FS”

stack traceback:
    [C]: in function 'error'
    [D:\Program Files (x86)\xmake/core/base/os.lua:705]: in function 'raise'
    [D:\Program Files (x86)\xmake\core\sandbox\modules\os.lua:327]: in function 'iorunv'
    [... Files (x86)\xmake\modules\detect\tools\cl\has_flags.lua:79]:
[01%]: compiling.debug thirdparty\libharu\src\hpdf_u3d.c
cl.exe -c -Zi -Fdbuild\\windows\\x86\\debug\\libharu.pdb -Od -Ithirdparty\\\\libharu\\\\include -Ithirdparty\\\\libharu\\\\win32\\\\include -DLIBHPDF_HAVE_NOPNGLIB -DLIBHPDF_HAVE_NOZLIB -DLIBHPDF_HAVE_NOPNGLIB=1 -DLIBHPDF_HAVE_NOZLIB=1 -nologo -Fobuild\\.objs\\libharu\\windows\\x86\\debug\\thirdparty\\libharu\\src\\hpdf_u3d.c.obj thirdparty\\libharu\\src\\hpdf_u3d.c
error: D:\Program Files (x86)\xmake/core/base/os.lua:705: D:\Program Files (x86)\xmake/core/base/os.lua:705: D:\Program Files (x86)\xmake/core/base/os.lua:705: D:\Program Files (x86)\xmake/core/base/os.lua:705: D:\Program Files (x86)\xmake/core/base/os.lua:705: hpdf_image_png.c
thirdparty\libharu\src\hpdf_image_png.c(23) : fatal error C1083: 无法打开包括文件:“png.h”: No such file or directory
stack traceback:
    [C]: in function 'error'
    [D:\Program Files (x86)\xmake/core/base/os.lua:705]: in function 'raise'
    [D:\Program Files (x86)\xmake\core\sandbox\modules\os.lua:327]:

stack traceback:
    [C]: in function 'error'
    [D:\Program Files (x86)\xmake/core/base/os.lua:705]: in function 'raise'
    [D:\Program Files (x86)\xmake\modules\core\tools\cl.lua:415]: in function 'catch'
    [D:\Program Files (x86)\xmake\core\sandbox\modules\try.lua:104]: in function 'try'
    [D:\Program Files (x86)\xmake\modules\core\tools\cl.lua:390]: in function '_compile1'
    [D:\Program Files (x86)\xmake\modules\core\tools\cl.lua:444]:
    [C]: in function 'compile'
    [D:\Program Files (x86)\xmake\actions\build\kinds\object.lua:141]: in function '_build_object'
    [D:\Program Files (x86)\xmake\actions\build\kinds\object.lua:160]:

stack traceback:
        [C]: in function 'error'
        D:\Program Files (x86)\xmake/core/base/os.lua:705: in function 'raise'
        D:\Program Files (x86)\xmake/core/sandbox/modules/utils.lua:166: in function 'assert'
        D:\Program Files (x86)\xmake\actions\build\kinds\object.lua:141: in function '_build_object'
        D:\Program Files (x86)\xmake\actions\build\kinds\object.lua:160: in function <D:\Program Files (x86)\xmake\actions\build\kinds\object.lua:154>
stack traceback:
    [C]: in function 'error'
    [D:\Program Files (x86)\xmake/core/base/os.lua:705]: in function 'raise'
    [...ogram Files (x86)\xmake\core\sandbox\modules\process.lua:150]: in function 'runjobs'
    [D:\Program Files (x86)\xmake\actions\build\kinds\object.lua:154]: in function '_build_each_objects'
    [D:\Program Files (x86)\xmake\actions\build\kinds\object.lua:321]: in function 'build'
    [D:\Program Files (x86)\xmake\actions\build\kinds\static.lua:36]: in function '_build_from_objects'
    [D:\Program Files (x86)\xmake\actions\build\kinds\static.lua:162]: in function 'build'
    [D:\Program Files (x86)\xmake\actions\build\build.lua:60]: in function 'script'
    [D:\Program Files (x86)\xmake\actions\build\build.lua:130]: in function '_build_target'
    [D:\Program Files (x86)\xmake\actions\build\build.lua:152]: in function '_build_target_and_deps'
    [D:\Program Files (x86)\xmake\actions\build\build.lua:148]: in function '_build_target_and_deps'
    [D:\Program Files (x86)\xmake\actions\build\build.lua:224]: in function 'build'
    [D:\Program Files (x86)\xmake\actions\build\main.lua:59]:

stack traceback:
    [C]: in function 'error'
    [D:\Program Files (x86)\xmake/core/base/os.lua:705]: in function 'raise'
    [D:\Program Files (x86)\xmake\actions\build\main.lua:68]: in function 'catch'
    [D:\Program Files (x86)\xmake\core\sandbox\modules\try.lua:104]: in function 'try'
    [D:\Program Files (x86)\xmake\actions\build\main.lua:57]:
    [C]: in function 'load'
    [D:\Program Files (x86)\xmake/core/base/task.lua:496]: in function 'run'
    [D:\Program Files (x86)\xmake/core/main.lua:224]:

**Comment by fuyunbo** [comment]
$ xmake -v --backtrace
checking for the architecture ... x64
error: D:\Program Files (x86)\xmake/core/base/os.lua:705: ...m Files (x86)\xmake\modules\detect\sdks\find_vstudio.lua:98: bad argument #2 to 'gsub' (string/function/table expected)
stack traceback:
    [C]: in function 'gsub'
    [...m Files (x86)\xmake\modules\detect\sdks\find_vstudio.lua:98]: in function '_load_vcvarsall'
    [...m Files (x86)\xmake\modules\detect\sdks\find_vstudio.lua:194]: in function 'find_vstudio'
    [D:\Program Files (x86)\xmake\platforms\windows\check.lua:42]: in function '_check_vsenv'
    [D:\Program Files (x86)\xmake\platforms\windows\check.lua:96]: in function 'checker'
    [...ogram Files (x86)\xmake\platforms\windows\..\checker.lua:99]: in function 'check'
    [D:\Program Files (x86)\xmake\platforms\windows\check.lua:218]: in function 'check'
    [...make\core\sandbox\modules\import\core\project\config.lua:120]: in function 'check'
    [D:\Program Files (x86)\xmake\actions\config\main.lua:250]:
    [C]: in function 'load'
    [D:\Program Files (x86)\xmake/core/base/task.lua:496]: in function 'run'
    [...86)\xmake\core\sandbox\modules\import\core\base\task.lua:67]: in function 'run'
    [D:\Program Files (x86)\xmake\actions\build\main.lua:47]:
    [C]: in function 'load'
    [D:\Program Files (x86)\xmake/core/base/task.lua:496]: in function 'run'
    [D:\Program Files (x86)\xmake/core/main.lua:224]:

stack traceback:
    [C]: in function 'error'
    [D:\Program Files (x86)\xmake/core/base/os.lua:705]: in function 'raise'
    [...86)\xmake\core\sandbox\modules\import\core\base\task.lua:69]: in function 'run'
    [D:\Program Files (x86)\xmake\actions\build\main.lua:47]:
    [C]: in function 'load'
    [D:\Program Files (x86)\xmake/core/base/task.lua:496]: in function 'run'
    [D:\Program Files (x86)\xmake/core/main.lua:224]:

**Comment by fuyunbo** [comment]
上面那个工程我上周刚开始的时候也是没有问题的，后面创建了另一个工程编译报了backtrace错误以后再次运行那个工程就也报错误了，但是刚刚运行也确实是又只有编译错误了

**Comment by fuyunbo** [comment]
我更新了版本也不行，我在想这个与vs的版本有关系吗，我计算机现在安装了vs2010和vs2015两个版本

**Comment by waruqi** [comment]
这个 可能需要你这帮忙在xmake的安装目录脚本 xmake/modules/detect/sdks/find_vstudio.lua 中加些print 给我看下输出才行了。。

大概在下面这个位置加些print：

```lua
function _load_vcvarsall(vcvarsall, arch)

    -- ...

    -- fix UCRTVersion 
    --
    -- @note vcvarsall.bat maybe detect error if install WDK and SDK at same time (multi-sdk version exists in include directory).
    --
    local UCRTVersion = variables["UCRTVersion"]
    -- 在这里帮忙打印一些变量值
    print("UCRTVersion", UCRTVersion)
    print("WindowsSDKVersion", WindowsSDKVersion)
    if UCRTVersion and UCRTVersion ~= WindowsSDKVersion and WindowsSDKVersion ~= "" then
        local lib = variables["lib"]
        if lib then
            lib = lib:gsub(UCRTVersion, WindowsSDKVersion)  -- 此处就是出现bad argument问题的地方
            variables["lib"] = lib
        end
        local include = variables["include"]
        if include then
            include = include:gsub(UCRTVersion, WindowsSDKVersion)
            variables["include"] = include
        end
        UCRTVersion = WindowsSDKVersion
        variables["UCRTVersion"] = UCRTVersion
    end
```

然后可以在一个非xmake工程目录下（避免缓存影响），执行`xmake l detect.sdks.find_vstudio` 给我看下输出结果

**Comment by fuyunbo** [comment]
我刚刚把计算机重新启动了一下，现在好像都正常了，按照之前的方式重新操作了几遍都不能重现了，应该是更新最新版本后重启计算机就解决了

**Comment by waruqi** [comment]
额。理论上xmake的安装更新跟重启没什么关系才对。 = =

**Comment by fuyunbo** [comment]
那就不清楚了，我之前重新启动了很多次也不行，今天就更新了你给的最新版本，然后重启了一下居然就可以了，先这样把，后续如果再重现出来了，我在按照你上面的方法打印log给你。谢谢了

**Comment by waruqi** [comment]
好的 不客气
