### ISSUE TITLE
xcode_sdkver wrong after update xcode

### ISSUE THREAD

**Issue by ldust** [tboox/xmake#227]
i had fixed it by deleting the .make dir, it seem the config cache is out of date.
i don't know this is a bug of xmake or not.

**Comment by waruqi** [comment]
It is not a bug. xmake will cache the detection result. If you updated the xcode envirnoment, you need clear the config cache to force to re-detect it manually.

You can run `xmake f -c` to clear config cache and re-config project. Or delete .xmake directory directly.

**Comment by ldust** [comment]
OK thanks.
