### ISSUE TITLE
select toolchain like cmake -t "v140"?

### ISSUE THREAD

**Issue by xtvjxk123456** [tboox/xmake#229]
what about selecting toolchain like cmake -t flag?

**Comment by waruqi** [comment]
I have supported this feature, you can install and try it. https://github.com/tboox/xmake/releases/download/v2.2.2/xmake-v2.2.2.exe

```console
$ xmake f --vs_toolchain=14.0
$ xmake
```

**Comment by xtvjxk123456** [comment]
xmake project do not generate a solution with right vs toolset
