### ISSUE TITLE
Q: can the compiler and version be detected and used to construct target directories?

### ISSUE THREAD

**Issue by rivy** [tboox/xmake#232]
I'm using:

```lua
set_project("hello")
cc = os.getenv("CC") or get_config("cc") or "CC"
build_dir = table.concat( {"$(buildir)", table.concat({"$(plat)","$(mode)",cc,"$(arch)"}, ".")}, "/" )
set_targetdir( build_dir.."/bin" )
set_dependir( build_dir.."/deps" )
set_objectdir( build_dir.."/obj" )
set_headerdir( build_dir.."/include" )
```

in the global portion of an *xmake.lua* file to set the build target folder for targets. I'd like to incorporate the currently used compiler (`cl`, `clang`, or `gcc`, for example) and it's version into the build directory construction. The above construction always ends up using "CC", unless I specifically use `xmake --cc=XXX`.

If I use a similar construction within a target on_load() function, `get_config("cc")` does return the compiler name, but, it seems like I only get the real compiler name for the second and following passes. It's empty at first, unless I set it at the initial command line, then does work. So, using "target:set("targetdir", vformat( build_dir.."/bin" ))" within on_load() then gives me two separate build directories and a second build pass.

I'm sorry to post this as an issue, but I'm not sure where else to discuss it.

Thanks.

**Comment by waruqi** [comment]
I can't fully support it for the time being, I will try to improve it in the next version.

**Comment by waruqi** [comment]
We cannot call `get_config("cc")` to get real compiler name in description scope when running `xmake f -c` to configure without cache.

Because I did the optimization to delay the detection of the actual compiler tool used.

But you can update the `dev` branch version and try the following configs:

```lua
build_dir = path.join("$(buildir)", table.concat({"$(plat)","$(mode)","$(cc)","$(arch)"}, "."))
set_targetdir(path.join(buildir, "bin"))
```

**Comment by rivy** [comment]
That's working.

Thanks.
