### ISSUE TITLE
用xmake f --qt=~/Qt5.11.0执行xmake生成的qt工程出错

### ISSUE THREAD

**Issue by zkqgxlbjx** [tboox/xmake#236]
错误信息如下：
checking for the architecture ... x86_64
error: cannot import module: detect.sdks.find_qt, cannot import module: core.base.winos, not found!

qt creator是使用bin安装包安装的，其安装目录是默认的。

**Comment by waruqi** [comment]
你可以更新到最新master版本再试试，我已经修复了。。

**Comment by zkqgxlbjx** [comment]
感谢你的付出，项目已经能够成功编译。
