### ISSUE TITLE
Add cparser compiler detection

### ISSUE THREAD

**Issue by nkindt** [tboox/xmake#239]
CParser is a pretty good C99 compiler with aggressive code optimizations. Would be great to have it in xmake.
https://github.com/libfirm/cparser

**Comment by waruqi** [comment]
This looks like a great compiler, I will consider supporting it in the next release.

**Comment by nkindt** [comment]
Great, thanks!

**Comment by waruqi** [comment]
I have supported this compiler, you can update the master version to try it. https://github.com/tboox/xmake/releases/download/v2.2.2/xmake-v2.2.3-dev.exe

**Comment by nkindt** [comment]
Ok, will test as soon as possible.

**Comment by nkindt** [comment]
I would need to test it on Linux (cparser doesn't work on Windows) and have troubles doing a fresh compile. Compiling 2.2.3 works fine but gives the same issue as the Debian package installation:

`not found main script: /home/nk/.local/share/xmake/core/_xmake_main.lua`

If i do the bash magic it gets all mixed up and things get worse:
```
sudo bash <(curl -fsSL https://raw.githubusercontent.com/tboox/xmake/master/scripts/get.sh)
bash: /dev/fd/63: No such file or directory
nk@h530 ~ $ curl: (23) Failed writing body (2175 != 2759)
```
Could you advice on how to compile and run 2.2.3 properly or give a ready binary?

**Comment by waruqi** [comment]
Deb package seems to have some problems, I will fix it.

You can try running `bash <(wget https://raw.githubusercontent.com/tboox/xmake/master/scripts/get.sh -O -)` to install it and you need not add `sudo`.

Or you can clone source code to compile and install it. You can docs https://xmake.io/#/home?id=compilation

**Comment by nkindt** [comment]
Executing the above command gets me here:
```
...
installing to /home/nk/.local ...
plat: linux
arch: x86_64
rm: cannot remove '/home/nk/.local/share/xmake/core': Permission denied
rm: cannot remove '/home/nk/.local/share/xmake/scripts': Permission denied
rm: cannot remove '/home/nk/.local/share/xmake/templates': Permission denied
rm: cannot remove '/home/nk/.local/share/xmake/plugins': Permission denied
rm: cannot remove '/home/nk/.local/share/xmake/languages': Permission denied
rm: cannot remove '/home/nk/.local/share/xmake/platforms': Permission denied
rm: cannot remove '/home/nk/.local/share/xmake/rules': Permission denied
rm: cannot remove '/home/nk/.local/share/xmake/xmake': Permission denied
rm: cannot remove '/home/nk/.local/share/xmake/modules': Permission denied
rm: cannot remove '/home/nk/.local/share/xmake/actions': Permission denied
rm: cannot remove '/home/nk/.local/share/xmake/repository': Permission denied
makefile:61: recipe for target 'install' failed
make: *** [install] Error 1
Install Fail
```

**Comment by waruqi** [comment]
You can remove the previous installed files and reinstall it.

```console
$ sudo rm -rf /home/nk/.local/share/xmake/
$ sudo rm /home/nk/.local/bin/xmake
$ bash <(wget https://raw.githubusercontent.com/tboox/xmake/master/scripts/get.sh -O -) 
```

**Comment by nkindt** [comment]
Was a bit busy, everything seems to work, thanks!
