### ISSUE TITLE
lib.detect.find_package 配合 vcpkg 无法使用

### ISSUE THREAD

**Issue by shilf** [tboox/xmake#242]
1.已经成功安装vcpkg，并且通过vcpkg安装zlib
2.已经执行vcpkg integrate install 此命令
3.import("lib.detect.find_package")
   target:add(find_package("zlib"))没有效果
4.import("lib.detect.find_package")
   local package = find_package("zlib")
   print(package)没有输出
是在windows 10  64位企业版
请问如何解决此问题

**Comment by waruqi** [comment]
可以先执行下 xmake f -c -v 贴下输出信息给我看下。

**Comment by shilf** [comment]
checking for the architecture ... x64
error: runv(vswhere.exe -?) failed(-1)!
checking for the vswhere.exe ... C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
checking for the cl.exe ... ok
checking for the Microsoft Visual Studio (x64) version ... 2017
checking for the vcpkg directory ... C:\Program Files\cmder\tools\vcpkg
checking for the pkg-config ... no
checking for the zlib ... no

**Comment by shilf** [comment]
C:\Program Files (x86)\Microsoft Visual Studio\Installer\
里面有vswhere.exe 而且运行正常

**Comment by shilf** [comment]
C:\Program Files\cmder\tools\vcpkg\packages\zlib_x86-windows 下面是zlib安装的包

**Comment by shilf** [comment]
C:\Users\shilf\Desktop\Test\hello
λ xmake f -c -v
checking for the architecture ... x64
error: runv(vswhere.exe -?) failed(-1)!
checking for the vswhere.exe ... C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
checking for the cl.exe ... ok
checking for the Microsoft Visual Studio (x64) version ... 2017
checking for the vcpkg directory ... C:\Program Files\cmder\tools\vcpkg
checking for the pkg-config ... no
checking for the paho-mqtt ... no
configure
{
    arch = x64
,   ccache = true
,   mode = release
,   host = windows
,   plat = windows
,   kind = static
,   buildir = build
,   vs = 2017
,   clean = true
,   vcpkg = C:\Program Files\cmder\tools\vcpkg
}

**Comment by waruqi** [comment]
看信息vcpkg检测到了 默认是x64编译 会去检测x64的zlib库，看你装的是x86的zlib包，你是要编译x86还是x64程序呢？

如果是x64程序，你需要装下x64的zlib库试试

如果是x86程序，你需要切换到x86来编译 
xmake f -a x86 -c 看看能否检测到zlib

**Comment by waruqi** [comment]
另外 对于zlib，直接使用xmake 2.2.2自带的包管理就好 不需要vcpkg 只需要

```lua
add_requires("zlib")
target("test")
  add_files("src/*.c")
  set_kind("binary")
  add_packages("zlib")
```

然后执行xmake编译即可

**Comment by shilf** [comment]
远程依赖模式好多包没有，vcpkg管理的包相对比较多

**Comment by waruqi** [comment]
那就先按照我刚说的方式 确认下 arch的匹配问题

**Comment by shilf** [comment]
现在已经找到是arch的问题，已经能够从vcpkg中找到我要的paho-mqtt包，不过paho-mqtt包的头文件MQTTClient.h中的DLLExport好像xmake编译错误

**Comment by shilf** [comment]
#if defined(WIN32) || defined(WIN64)
  #define DLLImport __declspec(dllimport)
  #define DLLExport __declspec(dllexport)
#else
  #define DLLImport extern
  #define DLLExport __attribute__ ((visibility ("default")))
#endif

**Comment by shilf** [comment]
是不是WIN32，WIN64，xmake无法识别

**Comment by waruqi** [comment]
这个跟xmake没关系，xmake不会自己追加任何defines，如果编译器没有内置定义win32 win64宏，或者相关include头文件中也没有定义，那你就自己定义下 add_defines("WIN64")

**Comment by shilf** [comment]
谢谢，已经编译成功了。准备用vscode结合xmake开发。
xmake run 的时候缺少相应的dll库，除了手动拷贝到build的相应子目录，xmake提供其他方式吗？

**Comment by waruqi** [comment]
如果是通过add_deps("xxx") 关联的target动态库，xmake run的时候 会自动追加对应的path路径，直接加载成功。

如果是add_links关联的第三方动态库，你可以设置before_run ，里面添加path路径就行了，os.addenv("PATH", "xxx/dll_dir")

**Comment by waruqi** [comment]
前两天不方便敲代码，下面的例子就可以在xmake run的时候，添加dll的加载路径

```lua
target("test")
    before_run(function (target)
        os.addenv("PATH", "xxx/dll_dir")
    end)
```

下面的例子，通过add_deps关联的动态库，xmake run是可以自动加载上的，不需要额外的时候，它对不同台都处理过了，win上自动追加path，linux/mac下自动追加rpath
```lua
target("test")
    set_kind("shared")
    add_files("src/*.c")

target("demo")
    set_kind("binary")
    add_deps("test")
    add_files("src/*.c")
```

**Comment by shilf** [comment]
error: unknown source file: ..\..\source\fib\FibSubscribeApi.h
c++,编译出现这样的问题，有这个文件，路径也对，错误信息太少了

**Comment by shilf** [comment]
还有xmake run 启动如何添加启动参数，vscode调试时如何添加启动参数

**Comment by waruqi** [comment]
> error: unknown source file: ....\source\fib\FibSubscribeApi.h
> c++,编译出现这样的问题，有这个文件，路径也对，错误信息太少了

add_files仅用于添加源文件，.h文件不用添加，如果需要include相关头文件，可以通过add_includedirs，添加头文件搜索目录

**Comment by waruqi** [comment]
> 还有xmake run 启动如何添加启动参数，vscode调试时如何添加启动参数

见：https://github.com/tboox/xmake-vscode/issues/3#issuecomment-433896829  

这个跟此issues话题无关，请到上面的issues里面去讨论吧。。

**Comment by shilf** [comment]
好的

**Comment by shilf** [comment]
如何手动增加相应的lib库，现在一直报LNK2001错误

**Comment by waruqi** [comment]
？报什么错？请提供详细 xmake.lua设置以及错误信息。。

add_links
