### ISSUE TITLE
xmake project -k makefile

### ISSUE THREAD

**Issue by shilf** [tboox/xmake#244]
使用这个命令生成makefile文件，然后使用vc6.0的nmake编译错误
NMAKE : fatal error U1077: 'cl.exe' : return code '0x2'
Stop.

是不是要换成vs2017的nmake才可以，然后xmake是不是也是先生成makefile在nmake的呢？

**Comment by waruqi** [comment]
是在vs提供的 command prompt  操作的么？ vc6 太老了。。我基本上没怎么处理过。。不清楚是否支持。。建议还是用vs200x之后的版本吧

**Comment by shilf** [comment]
用xmake这个命令可以很好的生成可执行文件，但是nmake还是不行。用的是vs15.0的command prompt

**Comment by waruqi** [comment]
可以提供相关demo工程 我调下

**Comment by shilf** [comment]
[subMq.zip](https://github.com/tboox/xmake/files/2529790/subMq.zip)

**Comment by waruqi** [comment]
好的 回头有时间我看下
