### ISSUE TITLE
build failed for a project of c++17

### ISSUE THREAD

**Issue by georgetso** [tboox/xmake#246]
the project: https://github.com/danielshaving/redis-cpp17
the impacted lines in xmake.lua:

> set_languages("cxx17")
> add_cxflags("-std=c++17")

error info:
the ^ mark point to the < mark before any
> error: ./all.h:42:10: fatal error: 'any' file not found
> #include \<any\>
>                  ^~~~~
> 1 error generated.

**Comment by waruqi** [comment]
please let me see the xmake.lua

**Comment by georgetso** [comment]
-- add rules: debug/release
add_rules("mode.debug", "mode.release")

-- define target
target("redis")

    -- set kind
    set_kind("static")

    -- add files
    add_files("timerqueue.cc")
    add_files("socket.cc")
    add_files("tcpconnection.cc")
    add_files("select.cc")
    add_files("poll.cc")
    add_files("tcpclient.cc")
    add_files("cluster.cc")
    add_files("zmalloc.cc")
    add_files("redis.cc")
    add_files("rediscli.cc")
    add_files("connector.cc")
    add_files("tcpserver.cc")
    add_files("rdb.cc")
    add_files("replication.cc")
    add_files("buffer.cc")
    add_files("channel.cc")
    add_files("util.cc")
    add_files("threadpool.cc")
    add_files("hiredis.cc")
    add_files("redlock.cc")
    add_files("session.cc")
    add_files("eventloop.cc")
    add_files("epoll.cc")
    add_files("log.cc")
    add_files("object.cc")
    add_files("acceptor.cc")

-- define target
target("main")

    -- set kind
    set_kind("binary")

    -- add files
    add_files("main.cc")

    -- add deps
    add_deps("redis")

-- define target
target("sds")

    -- set kind
    set_kind("binary")

    -- add files
    add_files("sds.cc")

    -- add deps
    add_deps("redis")

--
-- FAQ
--
-- You can enter the project directory firstly before building project.
--   
--   $ cd projectdir
-- 
-- 1. How to build project?
--   
--   $ xmake
--
-- 2. How to configure project?
--
--   $ xmake f -p [macosx|linux|iphoneos ..] -a [x86_64|i386|arm64 ..] -m [debug|release]
--
-- 3. Where is the build output directory?
--
--   The default output directory is `./build` and you can configure the output directory.
--
--   $ xmake f -o outputdir
--   $ xmake
--
-- 4. How to run and debug target after building project?
--
--   $ xmake run [targetname]
--   $ xmake run -d [targetname]
--
-- 5. How to install target to the system directory or other output directory?
--
--   $ xmake install 
--   $ xmake install -o installdir
--
-- 6. Add some frequently-used compilation flags in xmake.lua
--
-- @code 
--    -- add macro defination
--    add_defines("NDEBUG", "_GNU_SOURCE=1")
--
--    -- set warning all as error
--    set_warnings("all", "error")
--
--    -- set language: c99, c++11
   set_languages("c++17")
--
--    -- set optimization: none, faster, fastest, smallest 
--    set_optimize("fastest")
--    
--    -- add include search directories
--    add_includedirs("/usr/include", "/usr/local/include")
--
--    -- add link libraries and search directories
--    add_links("tbox", "z", "pthread")
--    add_linkdirs("/usr/local/lib", "/usr/lib")
--
--    -- add compilation and link flags
   add_cxflags("-std=c++17")
--    add_cxflags("-stdnolib", "-fno-strict-aliasing")
--    add_ldflags("-L/usr/local/lib", "-lpthread", {force = true})
--
-- @endcode
--
-- 7. If you want to known more usage about xmake, please see http://xmake.io/#/home
--

**Comment by georgetso** [comment]
[xmake.lua.zip](https://github.com/tboox/xmake/files/2532420/xmake.lua.zip)

**Comment by georgetso** [comment]
great solution!
