### ISSUE TITLE
請問environment.leave內的代碼是否有問題?

### ISSUE THREAD

**Issue by orzuk-lmj** [tboox/xmake#251]
底下這行代碼是在leave的時候呼叫，最後傳入的卻是enter
https://github.com/tboox/xmake/blob/master/xmake/core/platform/environment.lua#L132

local maps = {toolchains = environment._leave_toolchains, `run = environment._enter_run`}
請問是否應該是 `run = environment._leave_run`

**Comment by waruqi** [comment]
是的，你可以帮忙提交一个pr去修复下，或者等我明天改下。

**Comment by waruqi** [comment]
我已经修复了，在dev分支上。。
