### ISSUE TITLE
无法辨认的仿真模式: armelf_linux_eabi

### ISSUE THREAD

**Issue by lianluoo** [tboox/xmake#256]
$ xmake create android_demo2
create android_demo2 ...
create ok!

$ xmake f -p android --ndk=/opt/android-ndk/
checking for the architecture ... armv7-a
checking for the NDK directory ... /opt/android-ndk/
checking for the SDK version of NDK ... 28
checking for the toolchains version of NDK ... 4.9

$ xmake
[00%]: compiling.release src/main.c
[100%]: linking.release android_demo2
error: /..//bin/ld: 无法辨认的仿真模式: armelf_linux_eabi
支持的仿真： elf_x86_64 elf32_x86_64 elf_i386 elf_iamcu elf_l1om elf_k1om i386pep i386pe
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by waruqi** [comment]
你这用的是ndk r几版本？xmake版本多少？

**Comment by lianluoo** [comment]
@waruqi
ndk是r16
xmake是v2.2.2.201811051242

**Comment by lianluoo** [comment]
@waruqi
ndk r18
xmake v2.2.2.201811051242

**Comment by waruqi** [comment]
初步看了下 新版本ndk确实有这问题 后两天我查下原因 改进下

**Comment by waruqi** [comment]
我看了下，ndk r17之后，变动了很多，尤其是把默认的gcc改成了llvm/clang编译器已经相关toolchains，但是文件名还是armeabi-xxx-gcc，我做了些改进和支持，已经提交到 dev分支

改进内容如下：

- [x]: 支持r17之后arm-linux-androideabi-gcc (llvm/clang)编译器探测和识别，切换到clang编译模式
- [x]: gnu-libstdc++目录下的stl库r17之后已经被弃用，因此增加对llvm-libc++的支持
- [x]: r19 beta上windows ndk的gcc.exe改成了gcc.cmd，因此也做了支持

但是你遇到的这个问题，暂时解决不了，似乎是r17/r18版本gcc/g++作为linker时候，链接时候有bug（也有可能是我没处理好），链接的时候默认没切到arm-linux-androideabi-ld上去。

目前的解决办法：

1. 切换到ndk r19 beta1最新版本，linux/macos上你遇到的这个link问题已经没有了，似乎已经被修复了。
2. 回退到ndk r16之前版本，目前r16之前的版本 xmake都是完美支持的。

注：不管是选择哪种方式，都先更新下dev分支的xmake版本，再使用，因为对新版本ndk，还做了很多其他的改进支持

具体android ndk新版本支持力度的跟进，你可以看下： #258

**Comment by waruqi** [comment]
你更新下master版本试试吧，你说的这个问题我解决了，目前linux/macos下, ndk全版本都支持了，之前确实xmake处理上存在一些问题。。

而r17以上windows版本，目前还有些问题，后面我会继续改进支持下，但应该不影响你现在的使用了。

**Comment by lianluoo** [comment]
赞 ~\(≧▽≦)/~
