### ISSUE TITLE
MacOSX下链接第三方已编译好的动态库时，能否自动给第三方库加上rpath

### ISSUE THREAD

**Issue by fasiondog** [tboox/xmake#262]
场景如下：
1、自己编译了boost库。
2、假定编译完安装：xmake install -o install/hikyuu
3、上面会把自己编译的依赖的boost，如 libboost_python36.dylib一起拷贝到install/hikyuu目录下
4、但libboost_python36.dylib里没有@rpath，得自己手工install_name_tool更改。目前只能通过after build加脚本修改。

**Comment by waruqi** [comment]
用xmake编译的dylib库是有内置@rpath的，第三方库如果没有的话，添加add_rpathdirs确实会失效，下个版本我尝试改进下对第三方库加载的支持。。

**Comment by waruqi** [comment]
我思考了下，这个可能还是需要用户去处理才行，因为：

1. 通过 `add_links("boost_python36")` 链接动态库后，链接器确实能找到实际链接的dylib，但是xmake找起来有可能会不准，也比较繁琐，只有找到实际的dylib后，才能注入@rpath/
2. 另外xmake在用户不知道的情况下自动篡改添加@rpath，修改dylib会导致一些隐性问题
3. 每次编译都去通过install_name_tool去-add_rpath=一个新路径，会有重复，还需要做去重逻辑处理

实际上，对第三方dylib的处理，只需要处理一次@rpath添加就行了，即使用户手动在命令行下敲一遍：

```console
$ install_name_tool -add_rpath @rpath/libboost_python36.dylib  xxx/libboost_python36.dylib
```

这个库就已经是可自动适配不同加载路径了，因为有了：

```console
$ otool -L xxx/libboost_python36.dylib
@rpath/libboost_python36.dylib
```

这个时候只要吧这个库内置在工程里面，每次编译的时候，通过add_rpathdirs就可以随意切换加载目录了

```lua
target("test")
    add_links("boost_python36")
    add_linkdirs("xxx")
    add_rpathdirs("@loader_path")
```

例如上面的代码编译的test可执行文件，只要跟dylib安装在同一个目录，都会加载成功
