### ISSUE TITLE
xmake的lua script最方便的debug工具是什麼?

### ISSUE THREAD

**Issue by orzuk-lmj** [tboox/xmake#268]
請問以目前來說，對xmake的lua script最方便的debug工具是什麼?
因為 import 不同於 require 運作方式的差異，讓 vscode + luaide-lite 之類的 IntelliSense 解析功能失效了。

**Comment by waruqi** [comment]
这块我倒是没怎么关注过，一般都是vim+xmake直接就这么用了，不怎么用vscode，所以一些ide上的特性需求和痛点可能关注的不多。。

对于script调试，我一般建议还是直接print，这是最方便直接的，而且xmake的script中的print是扩展过的，对于table/object都可以很方便的dump出来。。

对于一些modules可以通过xmake lua插件，进行快速加载调试，或者交互式调试：

```console
$ xmake l xxx.lua
$ xmake l lib.detect.find_package xxx
$ xmake lua
> local find_tool = import("lib.detect.find_tool")
> find_tool("gcc")
> local a = 10
> a
```

IntelliSense失效问题，暂时支持不了，等以后有时间，可以考虑增强下xmake-vscode插件来内置支持。。

**Comment by orzuk-lmj** [comment]
舉個例子來說，我開啟了 --verbose 後，它提供的額外訊息不足以幫助我追蹤執行過程。
我在自己建立的xmake.lua中設置了
``` lua
-- add target
target("test")
    -- set kind
    set_kind("binary")
    ...
```
因為上面都已經設置了 kind 等於 binary，但是執行後印出來的結果卻是 `kind = static`，實在非常不理解。
``` lua
configure
{
    arch = x64
,   ccache = true
,   mode = debug
,   host = windows
,   plat = windows
,   kind = static
,   buildir = ..\_build\vs2015-x64-debug
,   vs_sdkver = 10.0.10586.0
,   vs = vs2015
,   vs_toolset = 14.0
}
```
所以只好在xmake原代碼中加入很多的print去追蹤，但因為沒辦法逐步除錯，看不到 callstack ，也沒有 IntelliSense ，這樣的狀況下我在如此深層的代碼中轉暈頭了。

我一路追蹤到 `function config.dump()` 和 `function config.set(name, value, opt)` 並且一路上放了很多print，可是 config.set 實在有太多地方呼叫到它，實在很難知道哪邊把 kind 設置為 static 。

求解惑。。

**Comment by waruqi** [comment]
> 舉個例子來說，我開啟了 --verbose 後，它提供的額外訊息不足以幫助我追蹤執行過程。

目前新版本提供了 `xmake -D` 参数来进一步提供更加详细的诊断信息，比如：flags的检测错误，栈回溯等等，也可以配合`-v`获取更多调试信息：`xmake -v -D`

> 因為上面都已經設置了 kind 等於 binary，但是執行後印出來的結果卻是 kind = static，實在非常不理解。

这个 `xmake f --kind=xxx`配置参数，目前仅仅用于控制 `set_kind("$(kind)")` 等内置 `$(kind)`变量的值，用于动态切换shared/static库编译，但是如果`set_kind("binary")`已经写死了target类型，是没法通过`xmake f --kind`修改的。。

对于使用和语法上不明白的地方，可以先通过文档中检索下，是支持全文检索的，比如搜索: kind 看下相关文档说明：
https://xmake.io/#/zh/manual?id=is_kind

如果文档描述不清楚或者没写明的地方，可以直接提issues来问，我一般都会即时回复和说明的。。

> 所以只好在xmake原代碼中加入很多的print去追蹤，但因為沒辦法逐步除錯，看不到 callstack ，也沒有 IntelliSense ，這樣的狀況下我在如此深層的代碼中轉暈頭了。

如果实在需要分析源码来了解机制的话，一般建议还是print，我自己基本上也都是print的，lua的调试工具没怎么用过，而且一般也就我一个人在维护代码，所以也没怎么关注源码的ide调试支持。。

> 我一路追蹤到 function config.dump() 和 function config.set(name, value, opt) 並且一路上放了很多print，可是 config.set 實在有太多地方呼叫到它，實在很難知道哪邊把 kind 設置為 static 。

config这块确实算是xmake里面比较核心也比较复杂的模块了，处理起来细节比较多，如果用户没设置`xmake f --kind=`的话，默认会有个默认值static，在config/xmake.lua的菜单中定义。

```lua
    set_menu {
                ,   {'k', "kind",       "kv", "static",     "Compile for the given target kind." 
```

**Comment by waruqi** [comment]
关于源码分析这块，之前我也写过一些文章，简单做过一些阐述，也可以看看：https://tboox.org/cn/2017/09/28/xmake-sourcecode-arch/
