### ISSUE TITLE
xmake project 執行時是否會讀取 xmake config 設定好的資料?

### ISSUE THREAD

**Issue by orzuk-lmj** [tboox/xmake#272]
首先執行一次 xmake config -a x86 設定資料，緊接著執行 xmake project 建立專案
``` lua
-- \xmake\bin\plugins\project\vstudio\impl\vs201x_vcxproj.lua
-- make Configurations
function _make_configurations(vcxprojfile, vsinfo, target, vcxprojdir)
    print("***** _make_configurations : arch = " .. config.get("arch"))
```
印出結果
``` lua
***** _make_configurations : arch = x64
```

**Comment by waruqi** [comment]
xmake project会同时对每个mode生成支持 x64/x86的vcproj工程，方便用户在vs内部快速切换编译

你可以看下https://github.com/tboox/xmake/blob/master/xmake/plugins/project/vstudio/impl/vs201x.lua里面make function部分

**Comment by orzuk-lmj** [comment]
我理解xmake project會同時生成x64/x86，也認同方便切換的功能。但是依然想詢問xmake project 執行時是否會讀取 xmake config 設定好的資料? 這關係到接下來能否順利自定義新的 project plugin 去支持 orbis + durango 。 希望能得到更進一步的解說，感謝 XD

**Comment by waruqi** [comment]
xmake project 里面会预先加载一次，在 https://github.com/tboox/xmake/blob/master/xmake/plugins/project/main.lua 里面，通过运行 `task.run("config")` ，调用`xmake config` 配置任务，里面会去通过`config.load()`加载缓存配置，之后为了同时切换x64/x86，会内部改下arch到config.

如果在自己的插件里面，可以参考更加简单些的其他插件代码，例如：https://github.com/tboox/xmake/blob/master/xmake/plugins/repo/main.lua

```lua
function main()

    -- 加载工程缓存配置
    config.load()

    -- 根据当前用户设置的平台，加载平台相关设置
    platform.load(config.plat())

    -- 之后就可以通过project.target/targets访问各个target对象，获取各种信息了
```

**Comment by orzuk-lmj** [comment]
非常感謝能給予如此詳細的回答。
我在嘗試的過程中還遇到了兩個問題：
- target:isphony() 的是什麼樣子的概念意義?
- 在project plugin裡面，我看到了 [project.modes()](https://github.com/tboox/xmake/blob/master/xmake/plugins/project/vstudio/impl/vs201x.lua#L183) ，這時候的 project.XXX 貌似和[ core.platform.platform](https://github.com/tboox/xmake/blob/master/xmake/core/platform/platform.lua#L324)不太一樣。
    ``` lua
    -- https://github.com/tboox/xmake/blob/master/xmake/plugins/project/vstudio/impl/vs201x.lua#L183
    vsinfo.modes = project.modes()
    ```
    如果希望能在plugin中project.modes()同位置的地方取得 [platform.archs()](https://github.com/tboox/xmake/blob/master/xmake/core/platform/platform.lua#L324) 我該如何做?
    ``` lua
    -- https://github.com/tboox/xmake/blob/master/xmake/core/platform/platform.lua#L324
    function platform.archs(plat)
    ```

**Comment by waruqi** [comment]
> target:isphony() 的是什麼樣子的概念意義?

关于这个，主要是用于设置一个空target，不作为任何target类型来编译程序，自身target没有任何源码编译，可以用来关联一些dep targets 或者自定义一些on_run脚本等 

更详细的说明可以看下 #68  

> 在project plugin裡面，我看到了 project.modes() ，這時候貌似無法直接取得 project.archs()

archs在 platform模块里面，modes是在 project xmake.lua中通过set_modes设置的，所以需要project来获取，因为编译模式仅对project生效
