### ISSUE TITLE
xmake能不能把c++的依赖管理做的和npm一样好啊，其他语言的工具已经够好了，xmake没必要支持了，把c++做好就可以了

### ISSUE THREAD

**Issue by shilf** [tboox/xmake#277]

**Comment by waruqi** [comment]
依赖管理刚弄完没多久，虽然初步可用，但细节处理以及包仓库完善还有不少工作量，后面会不断改进完善的。

关于语言，xmake初衷就是重点做c/c++编译的，对其他语言的支持也是为了与c/c++进行混合编译，这个也是必须的，像我这的一些项目经常需要混合一些objc或者asm代码在里面。

但是也不是所有语言xmake都会去支持，只有与c/c++ native兼容的语言我才会去支持，就是为了混合编译

**Comment by shilf** [comment]
我觉得要和vcpkg完美结合，最好能通过xmake让vcpkg的ports下面代码版本即时更新

**Comment by waruqi** [comment]
现在已经支持集成使用vcpkg的包了，但目前的重点还是完善自有的包管理

**Comment by shilf** [comment]
你说的是不是远程依赖模式呢

**Comment by shilf** [comment]
这个模式很不错，不过目前包太少了，能不能先做到和vcpkg一样的包数量

**Comment by shilf** [comment]
远程依赖模式，能否有个命令让我们查看一下我们想要安装的包是否存在，例如vcpkg search

**Comment by Ultraman95** [comment]
xmake require --search xxx

**Comment by waruqi** [comment]
？
