### ISSUE TITLE
設置--plat=mingw 的時候，warnings的指令出錯

### ISSUE THREAD

**Issue by orzuk-lmj** [tboox/xmake#281]
以下都是透過rule加載。

- 如果設置 `target:set("warnings", "all")` 就可以正常運作
- 但是如果設置其他選項，例如說 more/ less 都會造成錯誤。
    ```
    target:set("warnings", "more")
    error: g++: error: unrecognized command line option '-W3'; did you mean '-W'?
 
    target:set("warnings", "less")
    error: g++: error: unrecognized command line option '-W1'; did you mean '-W'?
    ```
- 這個問題是在嘗試 `set_pcxxheader("private/PrecompiledHeader.h")` 的時候發生的。一開始我設置了警告視同錯誤 target:set("warnings", {"all", "error"})，就會發生底下的錯誤。
    ```
    [  0%]: compiling.debug PrecompiledHeader.h
    error: PrecompiledHeader.h:18:9: error: #pragma once in main file [-Werror]
    ```
    PrecompiledHeader.h 的內容很簡單：
    ``` cpp
    #pragma once
    #include <stdlib.h>
    #include <stdio.h>
    #include <iostream>
    ```
- 想請問有沒有什麼簡單的辦法，讓xmake執行過程中顯示 warning 訊息。通常平時都關著，偶爾會檢查一下，我現在用警告視同錯誤來顯示，但這樣就看不到詳細的警告訊息，例如明確指出某個`訊息由 -Wunknown-pragmas 產生`。
- 關閉特定警告的方法不曉得哪一個比較好，目前我使用 `target:add("cxflags", "-Wno-unknown-pragmas")` 正確嗎?

**Comment by waruqi** [comment]
> 但是如果設置其他選項，例如說 more/ less 都會造成錯誤。
可能是mingw下gcc版本低，-W1 -W3不支持。

> 想請問有沒有什麼簡單的辦法，讓xmake執行過程中顯示 warning 訊息。

加上 -w参数执行编译就行了，`xmake -w`

> 關閉特定警告的方法不曉得哪一個比較好，目前我使用 target:add("cxflags", "-Wno-unknown-pragmas") 正確嗎?

是的

**Comment by waruqi** [comment]
恩，这个确实是bug，已经修复，你可以更新下dev分支试试：xmake update dev
