### ISSUE TITLE
在rule 的 on_install 腳本域如何取得 install dir ?

### ISSUE THREAD

**Issue by orzuk-lmj** [tboox/xmake#283]
- 在自定義 rule 的 on_install(function (target) 中，我該如何取得類似 package:installdir 的路徑? 
- 如果可以的話，希望能取得 xmake install -o XXXX 所指定的目錄
- 如何取得 exe 配對的 pdb 路徑?

**Comment by waruqi** [comment]
你可以更新下dev代码试试，我增加了`target:installdir()`并且额外添加了一个api `set_installdir`用于设置每个target的安装目录

```lua
target("test")
    set_installdir("/usr/local")
```

installdir的获取优先顺序：target.set_installdir > xmake install -o xxx > env(INSTALLDIR or DESTDIR) > platform.set_installdir

**Comment by waruqi** [comment]
> 有個比較不方便的小問題回饋是，在windows或mingw的 shared 編譯後，dll 所對應的 .lib 和 .a 的路徑取得稍微麻煩了點。可以的話如果能內建API取得就更好了。

这个暂时只能用户来处理了，因为这个获取，是平台相关的，只有win需要这么获取，不好做内建Api，而且用户处理也不是特别繁琐：

```lua
path.basename(filepath) .. ".lib" 就行了
```
