### ISSUE TITLE
在獨立檔案的 rule 中，如果要呼叫其他自訂義函數，其內部的 import 該如何正確處理?

### ISSUE THREAD

**Issue by orzuk-lmj** [tboox/xmake#285]
新建一個 common.lua 
``` lua 
local common = common or {}
function common.func()
    import("core.base.option")
    local verbose = option.get("verbose") or ""
    print("verbose = " .. verbose)
end

rule("libgdk.install")
    on_install(function (target)
        
        -- import another module
        import("core.base.option")
        import("core.project.config")

        -- call function
        common.func()

    end)
```
執行時會出錯，並且沒有辦法顯示更進一步出錯的位置，**僅有簡單訊息難以追蹤**。
``` 
error: installation failed, may permission denied!
checkinfo: runv(sudo.exe -h) failed(-1)!
checking for the sudo ... no
```

- 會想要分割內容成小的工具函數，方便未來複用和整理。
- 想詢問是否用錯方式，得用類似的 sandbox 包裝嗎?

**Comment by waruqi** [comment]
> 執行時會出錯，並且沒有辦法顯示更進一步出錯的位置，僅有簡單訊息難以追蹤。

看完整错误信息，可以敲：xmake -v -D

> 會想要分割內容成小的工具函數，方便未來複用和整理。

可以在xmake.lua所在目录下，放置脚本文件，例如：aaa/bbb/ccc.lua

可以在on_install里面通过import导入后使用

```lua
on_install(function (target)
    import("aaa.bbb.ccc")

    -- do ccc.main()
    ccc()

     -- do other_api function
     ccc.other_api()
end
```

ccc.lua 可以设置main主入口直接调用，也可以设置其他接口，作为模块调用

```lua
function other_api()
end

-- 可以传递参数：ccc(...)
function main(...)
end
```

也可以指定一个脚本文件作为on_install，例如：

```lua
on_install("install")
on_install("xxx.yyy.install")
```

格式参考import，相当于设置install.lua和xxx/yyy/install.lua

**Comment by orzuk-lmj** [comment]
> 
> 
> > 執行時會出錯，並且沒有辦法顯示更進一步出錯的位置，僅有簡單訊息難以追蹤。
> 
> 看完整错误信息，可以敲：xmake -v -D
> 

這裡可能有些特殊吧，我的確已經使用了 xmake install -v -D 了。但回饋的訊息只有：
```
error: installation failed, may permission denied!
checkinfo: runv(sudo.exe -h) failed(-1)!
checking for the sudo ... no
```

**Comment by waruqi** [comment]
> 可能是這裡有些特殊，我的確已經使用了 xmake install -v -D 了。但回饋的訊息只有：

错误显示不全的问题，我已经修复，加上 `-v` 就能看到错误信息。

> 這讓我在有點長的代碼中逐行排除，才定位到其實是 import 的使用方法錯誤了。

这是因为你在脚本域调用描述域定义的function，首先需要理解下xmake的描述域和脚本域规则：

1. xmake的描述域仅用于简单的配置描述，简化复杂性，是项目描述可读性更好
2. 描述域可定义function，但是内部不支持import去导入模块使用
3. 脚本域才可以使用import，去加载处理一些复杂的构建逻辑，将工程的可读性和复杂性进行分离

因此，不建议在on_install等脚本域中去直接调用描述域function，甚至去import，如果脚本复杂，可以直接让on_install去加载指定模块文件，on_install("xxx.xxx.install")

关于作用域说明，可以参考下文章：https://tboox.org/cn/2016/10/26/api-scope/
