### ISSUE TITLE
xmake install 過程能不能手動設置關閉編譯?

### ISSUE THREAD

**Issue by orzuk-lmj** [tboox/xmake#290]
為了方便 xmake 管理專案，使用了 bat/ bash 腳本來做自動設置。
執行流程通常都是：
1. xmake config ...
2. xmake project ... 然後 msbuild 命令
3. xmake build ...  (2和3會倚賴自定義目的二選一)
4. xmake install ...

可是最後的 install 偏偏會額外多執行一次 build，這額外多花了些編譯時間，還會讓 after_build 腳本多執行一次。請問是否有設置可以讓 install 過程不要再次build ??
- on_install 會在 rule 和 target 中自定義
- on_build、after_build 會使用在 phony 目標，用來跑一些腳本。
- 使用 mingw 有觀察到 [ 25%]: compiling.debug XXXXXX 這類的訊息出現在 install 指令執行時。
- windows 則是 phony 的 on_build 在 install 時候又重複執行了。

建議讓 install 的時候只跑 on_install 和一些必要的事件，讓安裝流程去跑 on_build 滿詭異的。

**Comment by waruqi** [comment]
嗯，这块确实可以build隔离下会更好些。其实感觉run应该隔离下。。

隔离后，如果内置的install和run的target file文件还没生成过，就提示用户需要先去build

**Comment by orzuk-lmj** [comment]
感謝，測試OK運作正常
