### ISSUE TITLE
請求解惑，關於set_values後，rule取得values問題

### ISSUE THREAD

**Issue by orzuk-lmj** [tboox/xmake#292]
腳本內容：
``` lua
rule("gk.winmain")
    on_load(function (target)
        local winmain = target:values("winmain")
        if winmain ~= nil then
            print("<winmain> = [%s]", winmain)
        else
            print("<winmain> = [nil]")
        end

        if winmain then
            target:add("ldflags", "/subsystem:windows")
        else
            target:add("ldflags", "/subsystem:console")
        end
    end
rule_end() 

target("test")
    add_rules("gk.winmain")
    set_values("winmain", true)
```
不論是 xmake config、 xmake build、xmake install ，執行結果都帶有底下的訊息： 
``` lua
<winmain> = [true]
<winmain> = [nil]
<winmain> = [nil]
configure
{
    winmain = false
    winxp = false
    ccache = true
    mode = debug
    plat = windows
    vs = 2015
    kind = static
    buildir = ..\_build\vs2015-x64-debug
    vs_sdkver = 10.0.10240.0
    host = windows
    arch = x64
}
```

- 主要的疑問是，連續打印出三次 winmain ，但是後兩次的值為 nil ，這是為什麼?

**Comment by orzuk-lmj** [comment]
找到原因了，把build完整刪掉，再次執行就正常了。因為不久前正在測試三個target，估計可能是因為我的某些操作讓build內的資料出錯，完整刪掉build之後就無法重現了，我多試試。。。

**Comment by orzuk-lmj** [comment]
初步定位到問題，估計是我設置的XMAKE_CONFIGDIR問題，我很頻繁的使用 bat/bash 去設置這個環境變量，並且把 phoney target 作為類似macro的主要腳本，內容放了xmake XXX ... 之類的東西用來簡化在bat/bash要執行的指令，在這些過程中環境變數出了些錯誤，路徑指向錯了。

在這個過程中，在某一個程度上，靠環境變數XMAKE_CONFIGDIR很容易會有階層狀態問題，有辦法並存添加類似 xmake --configdir=yyyyy  這樣子的指令語法嗎?

**Comment by waruqi** [comment]
XMAKE_CONFIGDIR主要用于设置特定工程的配置缓存目录，放在`xmake g --configdir`设置到全局并不妥当

而在`xmake f --configdir`设置，就会出现先有鸡还是先有蛋问题，因为configdir自身的存储读取也是在本地工程缓存下的。。

因此，通过环境变量设置，目前看是最为合适的，我不建议用户在使用过程中，频繁修改这个配置，固定一处缓存位置，那就一直就用这个位置来存储就行了。。

如果非要频繁变更，建议在设置前先进行原始环境的保存，以便之后恢复，xmake内部的环境变量切换，都是这么处理的，这样更加的安全些，不会污染其他环境。。

```lua
-- 保存原始环境
local olddir = os.getenv("XMAKE_CONFIGDIR")

-- 环境切换
os.setenv("XMAKE_CONFIGDIR", "xxxx")

-- 恢复之前的环境
os.setenv("XMAKE_CONFIGDIR", olddir)
```

**Comment by orzuk-lmj** [comment]
>
> XMAKE_CONFIGDIR主要用于设置特定工程的配置缓存目录，放在`xmake g --configdir`设置到全局并不妥当

我也認同這點，configdir僅用於指定工程

> 
> 而在`xmake f --configdir`设置，就会出现先有鸡还是先有蛋问题，因为configdir自身的存储读取也是在本地工程缓存下的。。

這部分有些不太理解，例如用 xmake f --force_configdir=XXX 在命令啟動的時候就已經決定了用來儲存和讀取的路徑，在這次命令的過程中 configdir 都固定保持著 XXX。然後若 --force_configdir 沒有被命令設置的話，就取得環境變量，若還是沒有環境變量，就直接使用預設值。 這樣的作法會有衝突嗎?

**Comment by waruqi** [comment]
> 這部分有些不太理解，例如用 xmake f --force_configdir=XXX 在命令啟動的時候就已經決定了用來儲存和讀取的路徑，在這次命令的過程中 configdir 都固定保持著 XXX，force_configdir不被儲存

如果 不去存储configdir，那么仅在xmake f这个action执行周期内下生效，如果单独执行xmake build或者xmake install/run这种，就没法使用之前` xmake f --force_configdir=XXX`命令设置的值，还是走的环境变量。。

所以  xmake f --force_configdir=XXX 就永远影响不了 xmake build/install/run/package这些action。。

除非每个action都传参，xmake build --configdir=... ; xmake run --configdir=...

**Comment by orzuk-lmj** [comment]
能理解你的意思了，cmake 使用默認的 current working directory 來當作build所在，所以也要不斷切換目錄，但只要切換過後，就可以簡單的下 cmake 的 build/install指令。

**Comment by waruqi** [comment]
xmake使用项目根xmake.lua所在的目录作为working dir，来存储.xmake配置，以及默认的build目录，这样的好处是，如果用户临时切换到项目自目录下，也可以像在根目录下一样执行xmake build等命令，即使当前目录下没有xmake.lua，这个行为类似git

而且这样，用户不停的切目录，去xmake build，避免到处生成.xmake等隐藏的配置目录，污染工程，导致混乱也是很有必要的，也方便用户去维护唯一的一处.xmake目录所在。

所以我不建议用户到处切目录，到处切换存储.xmake的位置，这样散乱的.xmake不易维护，也会污染整个工程目录

如果非要切换，还是建议通过XMAKE_CONFIGDIR变量设置

**Comment by orzuk-lmj** [comment]
理解，非常感謝解答。
