### ISSUE TITLE
Mac上使用mingw编译报错error: cc1plus: 对不起，尚未实现：未编译入对 64 位模式的支持

### ISSUE THREAD

**Issue by jiagushuai** [tboox/xmake#293]

**Comment by waruqi** [comment]
你更新了下dev分支版本 `xmake update dev`，试试，不行的话，加上-v编译下，给我看下详细信息，`xmake -v`

**Comment by jiagushuai** [comment]
Mac上的将v2.2.2更新到v2.2.3之后执行`xmake update dev`，一直卡在下载
```
gushuai:hello jl$ xmake update dev
update version: dev ..
  => download https://gitee.com/tboox/xmake.git .. ok
  => installing to /usr/local/Cellar/xmake/2.2.3/share/xmake .. \
```

**Comment by waruqi** [comment]
看log，下载已经完成了，正在安装中，不行的话，可以直接源码下载安装。

不过最近我正在重构改进mingw以及交叉工具链的检测和构建，要不等我这两天改进完，你再试试吧。。

**Comment by waruqi** [comment]
我改进了下mingw的检测和配置过程，并且提供`xmake f/g --mingw=xxx`来独立设置mingw sdk的根目录，当然之前的--sdk也有效，但以后主要用于其他通用交叉工具链设置

并且随着windows x64的普及，我默认mingw arch切到了x86_64下。

对于macos下，mingw sdk根目录会去自动探测 /usr/local/opt/mingw-w64/ 。。

因此在mac下，只需要执行：

```console
$ xmake f -p mingw -c # 加 -c强制重新检测，清掉之前检测的配置缓存
$ xmake
```

你可以执行 `xmake update dev`更新下试试，如果不行可以在编译时候加 -v 编译，提供给我详细的编译信息，我好分析下。。

目前我这边mac下测试是ok的，跟你这环境相同。。

**Comment by jiagushuai** [comment]
执行`xmake update dev`还是卡在第二步安装，xmake编译还是报错
```
gushuai:hello jl$ xmake f -p mingw -c
checking for the architecture ... i386
gushuai:hello jl$ xmake -v
configure
{
    host = macosx
,   arch = i386
,   ccache = true
,   kind = static
,   buildir = build
,   clean = true
,   mode = release
,   plat = mingw
}

checking for the g++ ... /usr/bin/g++
checking for the c++ compiler (cxx) ... g++
checking for the ccache ... no
checking for the /usr/bin/g++ ... ok
checking for the flags(g++) -O3 ... ok
checking for the shared library linker (sh) ... g++
[ 50%]: linking.release hello.dll
/usr/bin/g++ -o build/mingw/i386/release/hello.dll build/.objs/hello/mingw/i386/release/src/interface.cpp.o -s -fvisibility=hidden -shared -Wl,--out-implib,build/mingw/i386/release/hello.a
error: ld: warning: option -s is obsolete and being ignored
ld: unknown option: --out-implib
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jiagushuai** [comment]
Mac在哪看log啊

**Comment by waruqi** [comment]
> 看log，下载已经完成了，正在安装中（想要看具体进度可以加-v， xmake update -v dev），不行的话，可以直接源码下载安装。

根据前面的提示操作，更新失败，就加-v查
看详细log

xmake update -v dev

安装是需要一点时间的，不一定就是卡住，请耐性等待安装完成，加-v可以看详细进度信息

**Comment by jiagushuai** [comment]
`xmake update dev`执行更新OK，mingw编译结果跟刚才不一样，但是还是报错
```
gushuai:hello jl$ xmake update dev
update version: dev ..
  => download https://gitee.com/tboox/xmake.git .. ok
  => installing to /usr/local/Cellar/xmake/2.2.3/share/xmake .. -
  => install to /usr/local/Cellar/xmake/2.2.3/share/xmake .. ok
xmake v2.2.3.201811281708, A cross-platform build utility based on Lua
Copyright (C) 2015-2018 Ruki Wang, tboox.org, xmake.io
Copyright (C) 2005-2015 Mike Pall, luajit.org
                         _        
    __  ___ __  __  __ _| | ______ 
    \ \/ / |  \/  |/ _  | |/ / __ \
     >  <  | \__/ | /_| |   <  ___/
    /_/\_\_|_|  |_|\__ \|_|\_\____| 
                         by ruki, tboox.org
    
    👉  Manual: https://xmake.io/#/home
    🙏  Donate: https://xmake.io/pages/donation.html#donate
    
gushuai:hello jl$ xmake f -p mingw -c
checking for the architecture ... x86_64
checking for the mingw directory ... /usr/local/opt/mingw-w64
gushuai:hello jl$ xmake -v
configure
{
    arch = x86_64
    ccache = true
    mode = release
    plat = mingw
    bin = /usr/local/opt/mingw-w64/bin
    mingw = /usr/local/opt/mingw-w64
    kind = static
    buildir = build
    host = macosx
    cross = i686-w64-mingw32-
    clean = true
}
checking for the i686-w64-mingw32-g++ ... /usr/local/opt/mingw-w64/bin/i686-w64-mingw32-g++
checking for the c++ compiler (cxx) ... i686-w64-mingw32-g++
checking for the ccache ... no
checking for the /usr/local/opt/mingw-w64/bin/i686-w64-mingw32-g++ ... ok
checking for the flags(i686-w64-mingw32-g++) -O3 ... ok
[  0%]: compiling.release src/interface.cpp
/usr/local/opt/mingw-w64/bin/i686-w64-mingw32-g++ -c -fvisibility=hidden -O3 -m64 -o build/.objs/hello/mingw/x86_64/release/src/interface.cpp.o src/interface.cpp
error: cc1plus: 对不起，尚未实现：未编译入对 64 位模式的支持
```

**Comment by waruqi** [comment]
我看了下，可能有两个问题导致：

1. 你这执行更新安装到/usr/local下需要权限提示用户确认，我这边处理上有点问题，所以你这看着像是安装卡主了。。这块我之后改进下

2. 可能找错了arch对应的mingw/g++导致，我后两天改进后你再试试

**Comment by jiagushuai** [comment]
我用`xmake update -v dev`命令安装的时候就不会遇到卡住停顿的问题。
嗯嗯，那我后面再测试mingw

**Comment by waruqi** [comment]
这两个问题我都修复了，你可以再更新下 xmake update -v dev试试

对于update更新安装卡住问题，我也修复了，不过需要先加-v更新一次后，才生效

**Comment by jiagushuai** [comment]
编译生成ok，但是用mingw生成的exe依赖libstdc++-6.dll，需要-static参数，才可以不依赖libstdc++-6.dll。xmake的话对应是在哪里配置呢

**Comment by jiagushuai** [comment]
`gushuai:hello shandikeji$  xmake -r -v
checking for the mingw directory ... /usr/local/opt/mingw-w64
configure
{
    ccache = true
    host = macosx
    mingw = /usr/local/opt/mingw-w64
    buildir = build
    arch = x86_64
    mode = release
    ld = /usr/local/opt/mingw-w64/bin/x86_64-w64-mingw32-g++
    cxx = /usr/local/opt/mingw-w64/bin/x86_64-w64-mingw32-g++
    cross = x86_64-w64-mingw32-
    kind = static
    clean = true
    bin = /usr/local/opt/mingw-w64/bin
    plat = mingw
    sh = /usr/local/opt/mingw-w64/bin/x86_64-w64-mingw32-g++
}
checking for the ccache ... no
checking for the /usr/local/opt/mingw-w64/bin/x86_64-w64-mingw32-g++ ... ok
checking for the flags(x86_64-w64-mingw32-g++) -O3 ... ok
[  0%]: compiling.release src/interface.cpp
/usr/local/opt/mingw-w64/bin/x86_64-w64-mingw32-g++ -c -fvisibility=hidden -O3 -m64 -o build/.objs/hello/mingw/x86_64/release/src/interface.cpp.o src/interface.cpp
checking for the flags(x86_64-w64-mingw32-g++) -E -MM ... ok
[ 50%]: linking.release hello.dll
/usr/local/opt/mingw-w64/bin/x86_64-w64-mingw32-g++ -o build/mingw/x86_64/release/hello.dll build/.objs/hello/mingw/x86_64/release/src/interface.cpp.o -s -fvisibility=hidden -m64 -shared -Wl,--out-implib,build/mingw/x86_64/release/hello.a
[ 50%]: compiling.release src/test.cpp
/usr/local/opt/mingw-w64/bin/x86_64-w64-mingw32-g++ -c -fvisibility=hidden -O3 -m64 -o build/.objs/hello_demo/mingw/x86_64/release/src/test.cpp.o src/test.cpp
checking for the flags(x86_64-w64-mingw32-g++) -Wl,-rpath=@loader_path ... no
checking for the flags(x86_64-w64-mingw32-g++) -Xlinker -rpath -Xlinker @loader_path ... no
[100%]: linking.release hello_demo.exe
/usr/local/opt/mingw-w64/bin/x86_64-w64-mingw32-g++ -o build/mingw/x86_64/release/hello_demo.exe build/.objs/hello_demo/mingw/x86_64/release/src/test.cpp.o -Lbuild/mingw/x86_64/release -s -fvisibility=hidden -lhello -static -m64
error: /usr/local/Cellar/mingw-w64/5.0.4_1/toolchain-x86_64/bin/x86_64-w64-mingw32-ld: 找不到 -lhello
collect2: 错误：ld 返回 1

**Comment by jiagushuai** [comment]
![image](https://user-images.githubusercontent.com/29997741/50212512-31720d00-03b6-11e9-9773-c6814f28825d.png)

**Comment by jiagushuai** [comment]
放在target("hello")里面就可以正常编译，但是生成的exe还是依赖libstdc++-6.dll

**Comment by waruqi** [comment]
报错是因为你的动态库没设置导出符号，默认编译仅生成.dll 不生成对应的.lib，所以没法link的

而且你要static静态链接，就不应该设置set_kind 去设置生成shared动态库，应该生成set_kind static

至于放在hello正常编译，是因为add_ldflags仅对binary target生效，所以放根目录可以，你放到hello下，去影响shared动态库，等于没生效

**Comment by jiagushuai** [comment]
我是用`xmake create -l c++ -t shared hello`生成的动态库项目
window下默认编译是有生成.lib的，在Mac上的mingw编译就生成.a
1.为什么说动态库没设置导出符号不生成对应的.lib呢？同份代码Windows直接编译不是有生成.lib?
2.那动态库项目的话，用mingw编译怎么设置生成的exe不依赖libstdc++-6.dll呢

**Comment by waruqi** [comment]
win的动态库生成，需要设置导出函数，才会自动生成dll对应的lib文件用于link，win下编译也是的

如果xmake提供的模板工程，默认内部我已经设置过了，这边测试编译没问题，你这为啥会link not find我回头看看

不依赖libstd++ dll这个本身跟xmake没啥关系了，你google找找 第一页就有解决方案

add_ldflags_("-static-libstdc++", {force = true})

相关文章: https://blog.csdn.net/cuijinquan/article/details/18480847

**Comment by jiagushuai** [comment]
嗯嗯，是xmake的模板工程，thanks

**Comment by waruqi** [comment]
可以了么？

**Comment by jiagushuai** [comment]
还有在Mac用mingw编译是没有生成lib文件但是生成.a文件这个问题，导致后面编译出错

**Comment by jiagushuai** [comment]
![image](https://user-images.githubusercontent.com/29997741/50258271-d5e96300-0439-11e9-8f9b-3f2dab19ddfa.png)

**Comment by waruqi** [comment]
因为你加了 -static，对于 link动态库，不需要设置这个的，你设置了反而会干扰，这个flags是用于 link静态库的。。你删了就好

**Comment by jiagushuai** [comment]
但是我在Windows上编译是通过的，
设置`-static`用mingw生成的exe才不会依赖libstdc++-6.dll，libgcc_s_dw2-1.dll.
尝试过设置add_ldflags("-static-libstdc++"),add_ldflags("-static-libgcc")但是报错缺少libwinpthread-1.dll暂解决不了。
![image](https://user-images.githubusercontent.com/29997741/50259360-bf91d600-043e-11e9-9a8e-e5ed75087b10.png)

**Comment by jiagushuai** [comment]
同样的xmake.lua文件

**Comment by jiagushuai** [comment]
会报错哦，只用add_ldflags("-static-libstdc++", "-static-libgcc", {force = true})的话
![image](https://user-images.githubusercontent.com/29997741/50259869-e3eeb200-0440-11e9-9a13-9316b88d3da6.png)

**Comment by jiagushuai** [comment]
Windows这边是可以
![image](https://user-images.githubusercontent.com/29997741/50260199-3d0b1580-0442-11e9-9d32-97869d6dfade.png)

**Comment by waruqi** [comment]
你更新下 xmake update dev试试吧。我改了下。。

**Comment by jiagushuai** [comment]
更新之后重新编译执行还是报错，缺少libwinpthread-1.dll
mingw这边编译还是生成.a而不是.lib，这个会有影响吗
```
gushuai:hello jl$ xmake update dev
update version: dev ..
  => download https://gitee.com/tboox/xmake.git .. ok \
  => install to /usr/local/share/xmake .. ok \
xmake v2.2.3.201812191625, A cross-platform build utility based on Lua
Copyright (C) 2015-2018 Ruki Wang, tboox.org, xmake.io
Copyright (C) 2005-2015 Mike Pall, luajit.org
                         _        
    __  ___ __  __  __ _| | ______ 
    \ \/ / |  \/  |/ _  | |/ / __ \
     >  <  | \__/ | /_| |   <  ___/
    /_/\_\_|_|  |_|\__ \|_|\_\____| 
                         by ruki, tboox.org
    
    👉  Manual: https://xmake.io/#/home
    🙏  Donate: https://xmake.io/pages/donation.html#donate
    
gushuai:hello jl$ xmake -r -v
configure
{
    host = macosx
    mingw = /usr/local/opt/mingw-w64
    buildir = build
    arch = x86_64
    mode = release
    plat = mingw
    cxx = /usr/local/opt/mingw-w64/bin/x86_64-w64-mingw32-g++
    bin = /usr/local/opt/mingw-w64/bin
    sh = /usr/local/opt/mingw-w64/bin/x86_64-w64-mingw32-g++
    kind = static
    ld = /usr/local/opt/mingw-w64/bin/x86_64-w64-mingw32-g++
    cross = x86_64-w64-mingw32-
    clean = true
    ccache = true
}
[  0%]: compiling.release src/interface.cpp
/usr/local/opt/mingw-w64/bin/x86_64-w64-mingw32-g++ -c -fvisibility=hidden -O3 -m64 -o build/.objs/hello/mingw/x86_64/release/src/interface.cpp.o src/interface.cpp
[ 50%]: linking.release hello.dll
/usr/local/opt/mingw-w64/bin/x86_64-w64-mingw32-g++ -o build/mingw/x86_64/release/hello.dll build/.objs/hello/mingw/x86_64/release/src/interface.cpp.o -s -fvisibility=hidden -m64 -shared -Wl,--out-implib,build/mingw/x86_64/release/hello.a
[ 50%]: compiling.release src/test.cpp
/usr/local/opt/mingw-w64/bin/x86_64-w64-mingw32-g++ -c -fvisibility=hidden -O3 -m64 -o build/.objs/hello_demo/mingw/x86_64/release/src/test.cpp.o src/test.cpp
[100%]: linking.release hello_demo.exe
/usr/local/opt/mingw-w64/bin/x86_64-w64-mingw32-g++ -o build/mingw/x86_64/release/hello_demo.exe build/.objs/hello_demo/mingw/x86_64/release/src/test.cpp.o -Lbuild/mingw/x86_64/release -s -fvisibility=hidden -lhello -static-libstdc++ -static-libgcc -m64
build ok!👌

```

**Comment by waruqi** [comment]
刚更新的dev版本，已经全改成lib了。。a9f3eac5faf29e1a60b68ec2ac7ec791ef7549ee

你没更新成功吧。。你重新打开个终端，或者 source ~/.xmake/profile下后再试试

**Comment by jiagushuai** [comment]
1.更新之后正常生成lib文件，使用`-static`编译OK正常使用，不依赖gcc动态库文件，问题解决👌
2.只使用`add_ldflags("-static-libstdc++", "-static-libgcc", {force = true})`编译通过但是运行还是报错缺少libwinpthread-1.dll。
3.更新使用命令`sudo xmake update -v dev`看到有个Permission denied

```
installing to /Users/shandikeji/.local ...
plat: macosx
arch: x86_64
ok!
./scripts/get.sh: line 144: /Users/shandikeji/.bash_profile: Permission denied
xmake v2.2.3.201812201055, A cross-platform build utility based on Lua
Copyright (C) 2015-2018 Ruki Wang, tboox.org, xmake.io
Copyright (C) 2005-2015 Mike Pall, luajit.org
                         _        
    __  ___ __  __  __ _| | ______ 
    \ \/ / |  \/  |/ _  | |/ / __ \
     >  <  | \__/ | /_| |   <  ___/
    /_/\_\_|_|  |_|\__ \|_|\_\____| 
                         by ruki, tboox.org
    
    👉  Manual: https://xmake.io/#/home
    🙏  Donate: https://xmake.io/pages/donation.html#donate
    
  => install to ~/.local/bin .. ok    
xmake v2.2.3.201812201055, A cross-platform build utility based on Lua
Copyright (C) 2015-2018 Ruki Wang, tboox.org, xmake.io
Copyright (C) 2005-2015 Mike Pall, luajit.org
                         _        
    __  ___ __  __  __ _| | ______ 
    \ \/ / |  \/  |/ _  | |/ / __ \
     >  <  | \__/ | /_| |   <  ___/
    /_/\_\_|_|  |_|\__ \|_|\_\____| 
                         by ruki, tboox.org
    
    👉  Manual: https://xmake.io/#/home
    🙏  Donate: https://xmake.io/pages/donation.html#donate
    
```

**Comment by waruqi** [comment]
> 更新使用命令sudo xmake update -v dev

更新不需要sudo的。。直接执行 xmake update dev 就行了

**Comment by jiagushuai** [comment]
我是看到有个安装过程有个Permission denied，后面就用sudo再执行了一遍，这个Permission denied不影响是吗

**Comment by waruqi** [comment]
> 只使用add_ldflags("-static-libstdc++", "-static-libgcc", {force = true})编译通过但是运行还是报错缺少libwinpthread-1.dll。

这个是mingw的问题，不是xmake的问题了，你可以继续用-static，或者网上找下其他其他解决办法，仅对pthread进行 static link

**Comment by jiagushuai** [comment]
嗯嗯OK👌

**Comment by waruqi** [comment]
> 我是看到有个安装过程有个Permission denied，后面就用sudo再执行了一遍，这个Permission denied不影响是吗

如果没加sudo，看到这个提示，是老版本的问题，最新版本已经不会提示这个了。。除非必要，永远不要使用sudo去执行xmake
