### ISSUE TITLE
Proposal for Linuxbrew support

### ISSUE THREAD

**Issue by chenzhekl** [tboox/xmake#295]
Now that xmake already supports `homebrew`, how about further supporting `Linuxbrew`? It provides users the ability to install libraries to `HOME` without polluting the system. I know `vcpkg` can handle most of the package management task. But the binary distribution (bottles) provided by `Linuxbrew` is a huge time saving, and worth supporting.

**Comment by waruqi** [comment]
Do you mean the remote package management provied by xmake? Or lib.detect.find_package? ...

**Comment by chenzhekl** [comment]
Sorry for the confusion. I mean `lib.detect.find_package`. Probably I can send a PR for it.

**Comment by chenzhekl** [comment]
@waruqi care to comment?

**Comment by waruqi** [comment]
ok
