### ISSUE TITLE
CUDA target doesn't respect external packages' `add_includedirs`

### ISSUE THREAD

**Issue by chenzhekl** [tboox/xmake#296]
Per the title, when compiling `*.cu` files with `nvcc`, include directories set by external packages are not added as `-Ixxx` to the compiler flags.

**Comment by waruqi** [comment]
This should be no problem. I have tested it before.

You can try compiling this example. https://github.com/tboox/xmake/tree/master/tests/projects/cuda/console

If there is still this problem, I'll look at it later.

**Comment by chenzhekl** [comment]
@waruqi Thank you for such a quick fix! I'll test it tomorrow in the lab.

**Comment by chenzhekl** [comment]
Works as expected now.
