### ISSUE TITLE
最新dev分支 mingw static format 的問題

### ISSUE THREAD

**Issue by orzuk-lmj** [tboox/xmake#300]
更新了最新的 dev 分支，注意到 mingw 的 static 改動：
``` lua
set_formats {static = "$(name).lib", object = "$(name).obj", shared = "$(name).dll", binary = "$(name).exe", symbol = "$(name).pdb"}
```
根據 [wiki描述](http://www.mingw.org/wiki/specify_the_libraries_for_the_linker_to_use)： 
> Also note that the library names "lib\<name>.a" and "lib\<name>.lib" are not equivalent; if you have a library named according to the aberrant "lib\<name>.lib" convention, it will not be found by an "-l\<name>" specification -- if you cannot rename the library, you must use the form "-llib\<name>" instead.

- 這裡有了些疑問，想請問為什麼會想改成這種? 使用 lib\<name>.a 貌似可以繼續沿用 -l\<name> ，可以維持host在mac/linux 下的默認習慣。

**Comment by waruqi** [comment]
是可以沿用，但是可执行文件和动态库已经是.dll .exe，为了保证一致性，我就全改成win format了毕竟最终是要提供给win下运行的
