### ISSUE TITLE
option 啟用的判斷

### ISSUE THREAD

**Issue by orzuk-lmj** [tboox/xmake#308]
有時候 option 會很多，但是會在某些條件下才打算暴露出來，例如說有些選項在 linux 下根本不需要被設置，有些則是某 arch 才需要被設置。

``` lua
if is_plat("windows") then
    option("winxp")
    ...
    option_end()
end
```

- 上述的腳本沒法正常運作，想請問有什麼替代方法?

**Comment by waruqi** [comment]
这个目前的设计没办法的，is_plat is_arch这种本身就是从config里面取的，依赖xmake config命令的配置

而option就是用来定义config的参数配置的，因此config依赖option的定义

这就出现鸡生蛋的问题了。。

目前你只能通过is_host来判断，这个是直接获取的当前pc系统的host值，不依赖config

例如: is_host("windows")

**Comment by orzuk-lmj** [comment]
感謝~ 目前選擇用名字近似arch和plat 的option 來管理 option ，透過 dep 相關設置決定是否啟用選項群。

**Comment by waruqi** [comment]
用option管理option?
