### ISSUE TITLE
mac上编译mingw时生成.a文件而不是.lib文件

### ISSUE THREAD

**Issue by jiagushuai** [tboox/xmake#312]
+ 使用xmake的模板工程，已经使用`xmake update`更新，编译生成是.a文件
![image](https://user-images.githubusercontent.com/29997741/50531908-0de45a80-0b4c-11e9-8546-de0d60f86539.png)

**Comment by waruqi** [comment]
xmake update 更新的线上正式版本，也就是 2.2.3版本，这个.a问题是master/dev版本才刚修复的，你执行`xmake update`相当于回滚到v2.2.3版本上去了。。

得执行：`xmake update dev` 或者 `xmake update master` 更新dev/master分支版本

**Comment by jiagushuai** [comment]
有试过master和dev版本的，也一样
+ dev版本的
![image](https://user-images.githubusercontent.com/29997741/50532051-88ae7500-0b4e-11e9-870b-c684332c8059.png)
+ master版本的
![image](https://user-images.githubusercontent.com/29997741/50532063-c4e1d580-0b4e-11e9-8b71-600ed82961e0.png)

**Comment by waruqi** [comment]
看你的版本， v2.2.3.20181219  还是 12月19号的版本了，你装完得执行下 source ~/.xmake/profile 重新加载下新版本的环境，或者重新打开个 终端执行下xmake试试

**Comment by jiagushuai** [comment]
重新开个终端，执行过后还是一样
![image](https://user-images.githubusercontent.com/29997741/50532527-71bf5100-0b55-11e9-8576-48453c1bf9a7.png)

**Comment by waruqi** [comment]
你这个是执行了xmake update dev后的版本么？你这边肯定还是用的老版本的，最新代码里面都没处理.a的相关代码了。。

我看了下，master分支应该还没merge过去改动，是.a的，dev分支肯定是.lib了的。。

你可以到这里看下代码，是否已经是.lib了：
https://github.com/tboox/xmake/blob/04aca8108118992c4962bff9862b34ff8d4384a1/xmake/modules/core/tools/gcc.lua#L313

你本机安装目录下，~/.local//share/xmake/modules/core/tools/gcc.lua文件可以跟上面的文件diff下，确认是否已经更新到最新。

**Comment by jiagushuai** [comment]
确实是执行了`xmake update dev`后的版本，也执行了source
我这边的gcc.lua的没有lib，跟上面的文件不一样
![image](https://user-images.githubusercontent.com/29997741/50532921-5fe0ac80-0b5b-11e9-8c3e-9c5dd497d64d.png)

**Comment by jiagushuai** [comment]
另外我想问下，编译的时候链接加入chkstk.obj文件,obj后缀的要如何添加呢

**Comment by waruqi** [comment]
那就说明你这还是没装成功dev分支的版本，本机的还是老版本，你可以加 -v ，确实拉取dev代码安装是否成，xmake update -v dev

**Comment by waruqi** [comment]
> 另外我想问下，编译的时候链接加入chkstk.obj文件,obj后缀的要如何添加呢

其他不相关的问题，请另开issues反馈。

**Comment by jiagushuai** [comment]
我执行'xmake update -v dev'过后，hello的项目成功编译运行生成lib
但是同台电脑的另一个项目仍旧生成.a文件而不是.lib文件
![image](https://user-images.githubusercontent.com/29997741/50533194-9fa99300-0b5f-11e9-9299-6c680e9c4f82.png)

**Comment by waruqi** [comment]
之前开的终端得重新加载下

**Comment by jiagushuai** [comment]
重开终端之后执行`source ~/.xmake/profile`结果正常生成lib文件。
每次更新xmake版本之后都要重开终端并加载吗？

**Comment by jiagushuai** [comment]
我要执行`xmake update -v dev`之后再执行``才能编译生成.lib文件。另外再开一个终端的话，编译是.a文件
![image](https://user-images.githubusercontent.com/29997741/50534352-5add2680-0b76-11e9-8e73-3b82bd63517a.png)

**Comment by jiagushuai** [comment]
我重开窗口之后要执行`source ~/.xmake/profile`，xmake的版本才会变成最新的
![image](https://user-images.githubusercontent.com/29997741/50534442-988e7f00-0b77-11e9-8a90-e4d6c2138bee.png)

**Comment by waruqi** [comment]
你可以看下 ~/.bash_profile 文件里面有没有成功写入这个配置，如果有的话，每次新开终端，都是会自动 `source ~/.xmake/profile`的

```console
ruki:~ ruki$ cat ~/.bash_profile 
[[ -s "$HOME/.xmake/profile" ]] && source "$HOME/.xmake/profile" # load xmake profile
```

**Comment by jiagushuai** [comment]
没有这个，那我要添加手动添加到~/.bash_profile里面吗

**Comment by waruqi** [comment]
你自己追加下吧，因为之前你这老版本的xmake update dev里面的安装逻辑确实没有追加这个，新版本才会自动追加的。
