### ISSUE TITLE
怎么把chkstk.obj一起链接编译呢，在xmake中要如何表示

### ISSUE THREAD

**Issue by jiagushuai** [tboox/xmake#313]
在Mac上使用mingw链接msvc生成的库时常常产生这样的链接错误：
```
undefined reference to `_chkstk'
```
mingw在链接时不能找到chkstk的定义，所以找到vs中的chkstk.obj将其一起链接

**Comment by waruqi** [comment]
add_files("chkstk.obj")

**Comment by jiagushuai** [comment]
但是在hello项目中报了个警告
![image](https://user-images.githubusercontent.com/29997741/50533218-3a09d680-0b60-11e9-9c2e-ae2f6bc1bdb8.png)
+ 在另一个项目中报了另外一个警告
![image](https://user-images.githubusercontent.com/29997741/50533231-910fab80-0b60-11e9-9c50-2484daa3f90a.png)

**Comment by jiagushuai** [comment]
第一次报错是hello项目de的文件路径写错，修改之后编译报错为
![image](https://user-images.githubusercontent.com/29997741/50533265-42aedc80-0b61-11e9-9587-05e62b2d8aec.png)

**Comment by jiagushuai** [comment]
在xmake.lua中加入文件chkstk.obj，但是报错，为什么找不到呢
![image](https://user-images.githubusercontent.com/29997741/50533911-f9fe2000-0b6e-11e9-97c7-035f997b867e.png)

**Comment by jiagushuai** [comment]
我添加的chkstk.obj是符合平台,成功编译运行的了
![image](https://user-images.githubusercontent.com/29997741/50533926-23b74700-0b6f-11e9-96e3-67cb37be6694.png)

**Comment by waruqi** [comment]
> 在xmake.lua中加入文件chkstk.obj，但是报错，为什么找不到呢
> ![image](https://user-images.githubusercontent.com/29997741/50533911-f9fe2000-0b6e-11e9-97c7-035f997b867e.png)

请确认当前xmake.lua目录下，存在chkstk.o文件

**Comment by jiagushuai** [comment]
我执行`source ~/.xmake/profile`之后就编译成功了
