### ISSUE TITLE
在Mac上编译mingw引用第三方链接库的问题

### ISSUE THREAD

**Issue by jiagushuai** [tboox/xmake#314]
在项目中使用openssl和iconv等第三方库。
如果用mingw编译的话，需要专门编译mingw平台的openssl和iconv是吗？

**Comment by waruqi** [comment]
是的，或者你可以找官方编译好的，win版本的库就行

**Comment by jiagushuai** [comment]
1.官方编译好的Windows版本库可以用于Mac上的mingw使用吗？
2.我看了vcpkg的openssl版本较低，所以想自己下载编译官网最新版本的话，应该在mingw平台上编译是吗。

**Comment by waruqi** [comment]
> 1.官方编译好的Windows版本库可以用于Mac上的mingw使用吗？

都是win版本，都可以兼容的，顶多就是vc/mingw gcc下runtime哭依赖的差异，具体是否可以，你试试就知道了。

> 2.我看了vcpkg的openssl版本较低，所以想自己下载编译官网最新版本的话，应该在mingw平台上编译是吗。

可以，如何通过mingw编译，这个你网上找找好了，资料挺多的
