### ISSUE TITLE
没有从PATH变量寻找编译器的问题

### ISSUE THREAD

**Issue by hyqhyq3** [tboox/xmake#321]
在CentOS 6系统上，安装了devtoolset-7（gcc-7编译器套件）。然后在shell执行 source /opt/rh/devtoolset-7/enable，这时候环境变量PATH里面有了/opt/rh/devtoolset-7/root/usr/bin，但是执行xmake的时候，不能找到这个目录下的gcc和g++，xmake f -c清除缓存也没有作用。

**Comment by waruqi** [comment]
dev分支，我已修复，详情见：89271a60c4b4e56e9801dc11241b5d67cd3b2a2b

之前由于传入指定搜索目录去探测gcc，还是去优先找了$PATH中的gcc，所以我修改了find_program的逻辑，优先探测全路径下的gcc

不过这样就引出了你这边的问题，主要原因是find_program开头添加了两个/usr/bin/的系统搜索目录，导致也去优先查找了，对于系统默认路径的探测移动到$PATH检测之后就行了。
