### ISSUE TITLE
目前啟用多個rule 之後的on_install 會被覆蓋，有辦法組合嗎?

### ISSUE THREAD

**Issue by orzuk-lmj** [tboox/xmake#323]
- 希望可以拼裝組合 on_install 的腳本，會把多種腳本拆分到不同 rule 中，然後希望他們全都被執行。
- 部分狀況希望能保留原本的覆蓋行為。

**Comment by waruqi** [comment]
目前rule的before_install和after_install就是叠加的

对于on_install 语义设计上就是覆盖内置的install行为，不过rule的install是否叠加覆盖，我需要再思考下

关于原始内置的脚本行为，现在是支持在on_install的内部重新调用的，你可以试试

```lua
on_install(function (target, opt)
    opt.origin(target, opt)
end)
```

opt.origin里面存的就是target内置的安装脚本

**Comment by waruqi** [comment]
> 希望可以拼裝組合 on_install 的腳本，會把多種腳本拆分到不同 rule 中，然後希望他們全都被執行。

我刚看了下，现在的版本，每个rule的on_install就是叠加全部执行的哈，只会覆盖target内置的安装行为，但是rule间的on_install不会覆盖。。

而且内置的install脚本也是可以通过opt.origin调用来执行的。。

```lua
on_install(function (target, opt)
    opt.origin(target)
end)
```

**Comment by orzuk-lmj** [comment]
感謝，根據先前提及的命名規則 on_ 系列會覆蓋內置行為，現在若需要同時保留 target 和rule 安裝內容的狀況，我改用 target:on_install 搭配 rule:after_install，以確保同時安裝都被執行

之前的誤解在於，誤把 rule:on_install 作為父層，把 target:on_install 作為子層，直覺以為是巢狀關係，子層可以覆蓋父層
