### ISSUE TITLE
請問如何在target已經設置警告視同錯誤之後，個別關閉asm檔案的警告?

### ISSUE THREAD

**Issue by orzuk-lmj** [tboox/xmake#324]
- 已經在 target 中啟用 `target:set("warnings", {"all", "error"})`

- 添加個別的asm檔案時，若希望能單檔關閉警告該如何設置?
    ``` lua
    target:add("files", "asm/masmx86/inffas32.asm", {warnings = {"none"}})
    ```
- 目前我用上面這個無效，產生出來的指令是 同時帶有 `-W3 -WX` 和 `-w`

- 若去除 `{warnings = {"none"}}` 參數，則產生的指令僅剩下 `-W3 -WX` 。結論看起來它決定了是否添加 `-w`

**Comment by waruqi** [comment]
目前对单文件设置flags，仅支持追加，不支持覆盖模式。。
