### ISSUE TITLE
links 的相關設置，可以容許使用絕對路徑嗎?

### ISSUE THREAD

**Issue by orzuk-lmj** [tboox/xmake#326]
- 例如說自定義 find_xxx 之後傳回 { links = { "some_absolute_path" } }  ，設置好讓vc可以編譯，卻會讓 mingw/ ndk 失敗

- 雖然機會不高，但有可能會遇到 -lxxx 重名，這時候處理起來有些麻煩，會需要自己排 linkdirs 設置的順序或是乾脆直接連接指定位置的庫

**Comment by waruqi** [comment]
links对应 add_links 只用于设置 link name 例如 -lxxx ，xxx.lib，libxxx.a中的 xxx，不用于绝对路径设置

自定义的find_xxx 自己通过返回linkdirs 控制链接顺序 选择链接哪个库
