### ISSUE TITLE
Integrate with Conan package manager

### ISSUE THREAD

**Issue by solvingj** [tboox/xmake#327]
Per @waruqi request, opening this ticket to track an effort to add support for Conan packages. 

Ideally, each build system would not need to support each package manager, but this is not a solved problem yet.  Until then, custom support must be added to find Conan packages installed on the local machine.

**Comment by waruqi** [comment]
Ok, I will support it.

**Comment by yssource** [comment]
xmake is going to work as a generator in Conan, isn't it?

**Comment by waruqi** [comment]
I have supported to find conan packages using `lib.detect.find_package`

```console
$ xmake l lib.detect.find_package bzip2

{
    links = 
    {
        bz2
    }
,   linkdirs = 
    {
        /Users/ruki/.conan/data/bzip2/1.0.6/conan/stable/package/534dcc368c999e07e81f146b3466b8f656ef1f55/lib
    }
,   includedirs = 
    {
        /Users/ruki/.conan/data/bzip2/1.0.6/conan/stable/package/534dcc368c999e07e81f146b3466b8f656ef1f55/include
    }
}
```

**Comment by waruqi** [comment]
@yssource Yes, we are planning to do it.

**Comment by solvingj** [comment]
Thanks!  Can you tell me how it finds packages?

**Comment by waruqi** [comment]
Ok, I will improve it.

**Comment by solvingj** [comment]
Great, thanks!  See #331 for the working draft of the `xmake_generator`.

**Comment by solvingj** [comment]
this is looking very good, amazing progress as usual. it seems you have learned a great deal about Conan, and now have plans on how to improve your support for it in the future.  I think continued improvement on this integration will be sufficiently tracked in #339 along with the other package managers in a general way. Overall, there is a mostly-working integration now, so I will close this ticket.

**Comment by waruqi** [comment]
A simple example

```lua
add_requires("CONAN::zlib/1.2.11@conan/stable", {alias = "zlib", debug = true}})
add_requires("CONAN::OpenSSL/1.0.2n@conan/stable", {alias = "openssl", 
    configs = {options = "OpenSSL:shared=True"}})

target("test")
    set_kind("binary")
    add_files("src/*.c") 
    add_packages("openssl", "zlib")
```

**Comment by waruqi** [comment]
@solvingj It seems that the new version of conan 2.x breaks a lot of things.
How should I better integrate conan?

[issues](https://github.com/xmake-io/xmake/issues/3633)

**Comment by solvingj** [comment]
Your current quandary is a very difficult consequence of adding integration and support with multiple other tool/ecosystems like Conan, VCPKG, Cmake, and others. Each one is likely to make breaking changes at some point, And it's rarely easy to deal with four "wrapper tools" like Xmake. Now you have to decide how much time and complexity you want to devote to continue supporting the subset of xmake users who also use Conan, and use them together. It's been a few years since initial support was added. Now maybe you have some idea of whether or not a substantial number of people are even doing that. You added a native package manager into xmake, so if I were using Xmake for anything serious, I would probably want to use only xmake packages. Having some dependencies come from one package manager, and others come from another seems completely chaotic and unmanageable. 

If you decide to continue support, Conan integration, you probably have two choices: 

1. version lock Xmake and Conan, saying that Xmake currentVersion and earlier support only Conan 1x, and after Xmake nextVersion, only Conan 2x is supported. Then update all your code to support Conan 2.
2. Add a global Conan Version "mode" in Xmake which toggles all the behaviors in Xmake to use Conan1 or Conan2 semantics. And then write all the new implementation details you need to support that.

Of note, I only really consider the needs of professional software development teams in my comments. Hobbyists, and open source projects have different wants/needs. I don't know which user base you focus on more with Xmake.

In any case, things are going to get difficult end messy for you and/or any affected users for a while, so I wish you the best of luck.

**Comment by waruqi** [comment]
Can I integrate xmake into https://github.com/conan-io/conan/tree/release/2.0/conan/tools? Wouldn't that be better?

**Comment by solvingj** [comment]
> Can I integrate xmake into https://github.com/conan-io/conan/tree/release/2.0/conan/tools? Wouldn't that be better?

That folder contains mostly generators for build systems like the `xmake-generator` we worked on previously, and is still effectively done.  There are some other helper functions in there for special cases like CMake, but that's all to help `conan` invoke and integrate with `toolchains` and/or `build systems` which are extremely widespread (`cmake`, `msvc`, etc). I don't think they'll want to accept any specific support for `xmake` into the core codebase, and it's really not necessary.  Using the generator from a package is super commonplace.  The majority of professional dev teams using Conan have custom generators in packages.

But again, all that is separate from what broke and what you asked about.  The topic at hand is the details of how `xmake` does/should integrate with `conan`.  XMake tries to be a `build system`, `package manager`, `meta build system` and `meta package manager`.  Because it has functionality spanning multiple layers of the vertical tool stack, so it's hard to talk about in simple terms.  There is a similar quandry with CMake. 

The `xmake` feature that broke is that `xmake` is it's `meta package management` with `conan v2`.  `xmake` can no longer orchestrate the Conan commands to use it as a external package manager successfully with `conan v2` because the CLI structure has changed.  The surface problem is simple to fix.  Just fix the CLI invocations to format/pass the appropriate args according to the new CLI documentation.  But, as I alluded to, you probably want to support both `conan v1` and `conan v2` CLI and related behaviors.  So, you'll need to add a whole new `conan v2` support layer and the necessary logic to toggle between them for users.  Many users will be stuck on `conan v1` client and recipes and packages for a long time, some forever.  Many will use `conan v2`.  So, while the surface problem is simple to fix, the long-term maintenance and reliability problem is much more difficult.

**Comment by SirLynix** [comment]
I may have missed something but can't this be simply solved by querying Conan version before using its CLI, like `conan -v`?

**Comment by solvingj** [comment]
> I may have missed something but can't this be simply solved by querying Conan version before using its CLI, like `conan -v`?

Which problem are you suggesting that solves specifically?

**Comment by waruqi** [comment]
I'm trying to write a new generator for xmake, but I'm having some problems. https://github.com/conan-io/conan/issues/13709

**Comment by solvingj** [comment]
You're almost there, they'll get you the rest of the way.

**Comment by waruqi** [comment]
conan 2.0.5 re-supports the export of global generators. https://github.com/conan-io/conan/pull/13718

xmake/dev now also supports conan 2.0.5 https://github.com/xmake-io/xmake/pull/3703

**Comment by Jeordanis** [comment]
I'm having an issue trying to use the conan support. I'm trying to use a package that is already downloaded in the conan cache: ```"/Users/user/.conan2"```. In my xmake.lua file I have:

```lua
add_requires("conan::qtmaya/2024", {alias = "qt"})
target("UILibrary")
  set_kind("static")
  add_files("MyWidget.cpp")
  add_packages("qt")
  ```
  
  When I run ```xmake``` I get:
  ```quote
  note: install or modify (m) these packages (pass -y to skip confirm)?
in conan:
  -> conan::qtmaya/2024 latest 
please input: y (y/n/m)
```

xmake seems to be trying to download them from a conan remote repository instead of looking for it in the local conan cache. Is this not supported?
