### ISSUE TITLE
自定義的 find_xxx ，只要在使用 find_package(xxx) 的時候傳入 version ，就會導致錯誤。

### ISSUE THREAD

**Issue by orzuk-lmj** [tboox/xmake#328]
- 自定義了 find_xxx 提供給 find_package("xxx") 使用，且確認正常運作。
- 可是一旦添加 find_package("xxx", `{version="1.2.3"}`) 就會讓尋找失敗。
- 添加的 {version="1.2.3"} 確認可以在 find_xxx.lua 腳本中正確 `print(opt.version)` 出來
- 使用 version 的目的是為了自定義路徑尋找規則
- 目前的解決方法暫時使用別的變數名稱替代，貌似version有做額外處理判斷。

**Comment by waruqi** [comment]
设置版本查找，会严格约束仅找对应版本的库，如果找不到对应版本就会返回失败，目前仅对homebrew vcpkg 以及 xmake repo中的包 会检测到版本号，有些系统库，可能目前无法准确获取到版本号，就会匹配失败了

你可以不带version去find_package去尝试获取下，看看有没有检测到版本号，xmake l lib.detect.find_package xxx

如果获取到了版本号，但是跟你指定的version不匹配，也会返回失败，这种情况下，你可以放宽版本限制，find_package是支持语义版本匹配的，例如 version = "1.2.x"等

**Comment by waruqi** [comment]
如果你是自定义的find_package xxx 那么你自定义的脚本里面 需要同时返回实际的 version结果，例如 {links =, version="1.2.3"}，只有你返回了版本号，内置的find_package逻辑才会根据你传入的version来进行版本匹配

**Comment by orzuk-lmj** [comment]
> 如果获取到了版本号，但是跟你指定的version不匹配

我指定了 module 尋找路徑，且自定義了 find_xxx.lua 作為提供庫包的路徑資訊，在這樣的情況下整個查找應該是自定義的，不太理解為什麼還會需要去查找系統? 此時可以優先使用自定義的 find_xxx.lua 嗎? 

自定義的包查查找腳本 find_xxx.lua 裡面可能會有自訂的版本規則，這時候的 version 貌似全權交給客戶決定怎麼使用會比較好。

**Comment by orzuk-lmj** [comment]
> 你自定义的脚本里面 需要同时返回实际的 version结果

感謝!!!  應該就是缺這個而已，誤會了

**Comment by waruqi** [comment]
最近我重构了下lib.detect.find_package，并且内置提供了find_packages接口去快速查找多个依赖库，也不用特地每次去import find_package了，不过由于改动较大，可以测下你这是否能够正常处理

```lua
on_load(function (target)
    target:add(find_packages("zlib", "brew::pcre2/libpcre2", "vcpkg::pcre"))
end)
```

更多详情见：#339
