### ISSUE TITLE
qt的pro配置如QT += widgets在xmake如何设置

### ISSUE THREAD

**Issue by jiagushuai** [tboox/xmake#335]
我引用了QWidget，在qt的Pro配置文件如下即可
```
QT       += widgets

QT       -= gui
```
在xmake中是配置什么关键字呢?
试过`add_frameworks("QtWidgets")`无效

**Comment by waruqi** [comment]
你可以看下 https://github.com/tboox/xmake/blob/master/tests/projects/qt/widgetapp/xmake.lua

应该是有效的，不行的话 xmake -v编译，贴下编译输出给我

**Comment by jiagushuai** [comment]
我是生成qt的动态链接库中使用QWidgets，不是
widgetapp项目.
不过现在编译不知道为什么通过了，之前都报错。
