### ISSUE TITLE
xmake编译qt动态库项目添加Q_OBJECT报错如何设置

### ISSUE THREAD

**Issue by jiagushuai** [tboox/xmake#336]
+ 使用信号槽时，需要添加Q_OBJECT。在头文件加入后编译报错
+ 百度找的很多说修改pro文件重新编译或者在pro文件添加
```
OBJECTS_DIR  = tmp
MOC_DIR      = tmp
```
### 但是xmake中对应如何设置？

+ 使用模板工程创建项目编译成功
![image](https://user-images.githubusercontent.com/29997741/51653190-5ec16480-1fcd-11e9-97f1-85eeab29602d.png)
+ 加入宏定义Q_OBJECT后编译失败
![image](https://user-images.githubusercontent.com/29997741/51653275-bb248400-1fcd-11e9-8863-cf3708a5cbab.png)

**Comment by jiagushuai** [comment]
尝试过直接删除.xmake和build后再执行`xmake -r`但是结果还是报错

**Comment by waruqi** [comment]
你可以看下 官方文档说明：https://xmake.io/#/zh/?id=widgets%E5%BA%94%E7%94%A8%E7%A8%8B%E5%BA%8F

带qt meta的.h文件，不是单纯的头文件，需要添加到add_files参与编译的

![image](https://user-images.githubusercontent.com/151335/51653885-5dde0200-1fd0-11e9-977f-2a82ba40cfc2.png)

**Comment by jiagushuai** [comment]
没有注意到这个,添加后编译运行成功了
Thanks
