### ISSUE TITLE
Mac上在mingw-w64编译qt项目 实现思路？

### ISSUE THREAD

**Issue by jiagushuai** [tboox/xmake#337]
+ Mac上安装的是 qt-opensource-mac-x64-5.12.0.dmg,使用xmake编译一个弹窗界面OK
## 想用xmake编译mingw-w64平台的qt制作的弹窗
+ 实现思路我目前是:编译mingw版本的qt,然后指定mingw版本的qt路径,使用xmake编译
但是网上找的的都是Windows下安装mingw，官网5.12.0只看到Mac，Windows和Linux的
![image](https://user-images.githubusercontent.com/29997741/51737424-872d8980-20c7-11e9-8f87-3dc9de8c863c.png)
### 不像openssl一样我可以在github的issues提出疑问。请问有什么建议吗

**Comment by waruqi** [comment]
需要qt官方提供 mac下 mingw版本的sdk才行，目前我只知道win上有提供mingw的库，mac上不清楚 你找找

**Comment by ratio-dd** [comment]
解决了吗，我也想在mac上编译windows可用的exe文件
