### ISSUE TITLE
windows上设置qt编译目录但是结果不对

### ISSUE THREAD

**Issue by jiagushuai** [tboox/xmake#338]
Windows10电脑上安装了qt在C盘，然后我静态编译了另一个版本在D盘，
+ 使用`xmake f --qt="D盘目录"`
+ 但是我用`xmake -r -v`查看还是使用C盘下的qt编译
![image](https://user-images.githubusercontent.com/29997741/51889905-aa14b200-23d5-11e9-9f4c-712dbcfcfd3d.png)

**Comment by jiagushuai** [comment]
我该如何修改呢

**Comment by jiagushuai** [comment]
执行之后没有设置D盘的，还是默认的C盘qt
![image](https://user-images.githubusercontent.com/29997741/51956789-0504e280-2484-11e9-944f-77aa01f88cf8.png)

**Comment by waruqi** [comment]
哦，回头我看下

**Comment by waruqi** [comment]
看了下，应该是你指定的 D盘qt sdk 不满足检测结构，检测失败后，重新去探测注册表的 C盘默认qt路径了。。。

目前的检测逻辑是：xmake f --qt=C:\Qt\Qt5.6.3

然后检测其下面的 qt_sdk_dir\version\compiler\bin 目录，也就是 5.6.3\msvc2015\bin

而你指定的qt5.6-static-vs2015目录下面，有可能不满足 qt5.6-static-vs2015\[qtversion]\[compiler]\bin 结构，你可以确认下，不满足的话，你可以重命名调整下。

如果无法自己通过调整目录名和根目录结构的话，可以把你这的qt5.6-static-vs2015目录结构发我看下。。

**Comment by jiagushuai** [comment]
对照之后发现目录少了version这个文件夹，补充之后设置D盘的编译ok了

**Comment by jiagushuai** [comment]
可以不修改我本身的目录 修改检测条件吗，因为我发现我修改目录会影响，需要重新用新的目录编译

**Comment by waruqi** [comment]
暂时不能，因为还要检测qt sdk version，尽量保持qt官方的打包结构吧。目前我看qt的官方安装包 结构都是很规范的。。

**Comment by jiagushuai** [comment]
嗯嗯 那我重新编译一下
