### ISSUE TITLE
xmake c 在win上出现错误 日志如下

### ISSUE THREAD

**Issue by ranwei1025** [tboox/xmake#341]
error: C:\Program Files (x86)\xmake/core/language/language.lua:621: bad argument
 #1 to 'pairs' (table expected, got nil)
stack traceback:
    [C]: in function 'pairs'
    [C:\Program Files (x86)\xmake/core/language/language.lua:621]: in function '
linkerinfos_of'
    [C:\Program Files (x86)\xmake/core/tool/linker.lua:122]: in function 'load'
    [C:\Program Files (x86)\xmake/core/project/target.lua:409]: in function 'lin
ker'
    [C:\Program Files (x86)\xmake/core/project/target.lua:657]: in function 'tar
getfile'
    [C:\Program Files (x86)\xmake\actions\clean\main.lua:56]: in function '_do_c
lean_target'
    [C:\Program Files (x86)\xmake\actions\clean\main.lua:106]: in function 'scri
pt'
    [C:\Program Files (x86)\xmake\actions\clean\main.lua:154]: in function '_cle
an_target'
    [C:\Program Files (x86)\xmake\actions\clean\main.lua:168]: in function '_cle
an_target_and_deps'
    [C:\Program Files (x86)\xmake\actions\clean\main.lua:188]: in function '_cle
an'
    [C:\Program Files (x86)\xmake\actions\clean\main.lua:216]:
    [C]: in function 'load'
    [C:\Program Files (x86)\xmake/core/base/task.lua:506]: in function 'run'
    [C:\Program Files (x86)\xmake/core/main.lua:229]:

**Comment by waruqi** [comment]
你可以确认下你的 xmake.lua 里面 有没有 target.set_kind 设置除了 static/binary/shared以外未知类型的 kind

或者下载 https://github.com/tboox/xmake/releases/download/v2.2.3/xmake-master.exe 再试试

**Comment by ranwei1025** [comment]
更新后的错误 如下：
error: C:\Program Files (x86)\xmake/core/language/language.lua:630: bad argument
 #1 to 'pairs' (table expected, got nil)
stack traceback:
    [C]: in function 'pairs'
    [C:\Program Files (x86)\xmake/core/language/language.lua:630]: in function '
linkerinfos_of'
    [C:\Program Files (x86)\xmake/core/tool/linker.lua:103]: in function '_load_
tool'
    [C:\Program Files (x86)\xmake/core/tool/linker.lua:160]: in function 'load'
    [C:\Program Files (x86)\xmake/core/project/target.lua:512]: in function 'lin
ker'
    [C:\Program Files (x86)\xmake/core/project/target.lua:806]: in function 'tar
getfile'
    [C:\Program Files (x86)\xmake\actions\clean\main.lua:56]: in function '_do_c
lean_target'
    [C:\Program Files (x86)\xmake\actions\clean\main.lua:106]: in function 'scri
pt'
    [C:\Program Files (x86)\xmake\actions\clean\main.lua:154]: in function '_cle
an_target'
    [C:\Program Files (x86)\xmake\actions\clean\main.lua:168]: in function '_cle
an_target_and_deps'
    [C:\Program Files (x86)\xmake\actions\clean\main.lua:188]: in function '_cle
an'
    [C:\Program Files (x86)\xmake\actions\clean\main.lua:216]:
    [C]: in function 'load'
    [C:\Program Files (x86)\xmake/core/base/task.lua:512]: in function 'run'
    [C:\Program Files (x86)\xmake/core/main.lua:246]:

**Comment by waruqi** [comment]
https://github.com/tboox/xmake/blob/17c9dbc7d234dafcff6fcf0d20d016472fcc9061/xmake/core/project/target.lua#L427-L431

请在这个开头 加个print，打印下  target kind 值。。`print(self:name(), self:targetkind())` 给我看下

**Comment by ranwei1025** [comment]
找到原因了 有个target 这样写导致的
target("test")
    on_build("windows", function (target)
        os.exec("$(projectdir)\\shell\\bl.bat")
    end)

**Comment by waruqi** [comment]
你没设置kind，如果没有源文件。你可以设置成 set_kind("phony") 就行了

**Comment by waruqi** [comment]
我改好了。你可以xmake update dev更新下 再试试。。

**Comment by ranwei1025** [comment]
还是有问题 用最新版本 还是出现下面错误
error: bad argument #1 to 'pairs' (table expected, got nil)

**Comment by ranwei1025** [comment]
error: C:\Program Files (x86)\xmake/core/language/language.lua:631: bad argument
 #1 to 'pairs' (table expected, got nil)
stack traceback:
    [C]: in function 'pairs'
    [C:\Program Files (x86)\xmake/core/language/language.lua:631]: in function '
linkerinfos_of'
    [C:\Program Files (x86)\xmake/core/tool/linker.lua:103]: in function '_load_
tool'
    [C:\Program Files (x86)\xmake/core/tool/linker.lua:160]: in function 'load'
    [C:\Program Files (x86)\xmake/core/project/target.lua:537]: in function 'lin
ker'
    [C:\Program Files (x86)\xmake/core/project/target.lua:829]: in function 'tar
getfile'
    [C:\Program Files (x86)\xmake\actions\clean\main.lua:56]: in function '_do_c
lean_target'
    [C:\Program Files (x86)\xmake\actions\clean\main.lua:106]: in function 'scri
pt'
    [C:\Program Files (x86)\xmake\actions\clean\main.lua:154]: in function '_cle
an_target'
    [C:\Program Files (x86)\xmake\actions\clean\main.lua:168]: in function '_cle
an_target_and_deps'
    [C:\Program Files (x86)\xmake\actions\clean\main.lua:188]: in function '_cle
an'
    [C:\Program Files (x86)\xmake\actions\clean\main.lua:216]:
    [C]: in function 'load'
    [C:\Program Files (x86)\xmake/core/base/task.lua:512]: in function 'run'
    [C:\Program Files (x86)\xmake/core/main.lua:246]:

**Comment by waruqi** [comment]
可以了 你再试试
