### ISSUE TITLE
Linux Building breaks

### ISSUE THREAD

**Issue by avaicode** [tboox/xmake#46]
It seems your upgrade to tbox caused a serious problem.
Log here:
>installing to /usr/local ...
plat: linux
arch: x86_64
compiling xmake-core ...
=============================================================================
compile:
    plat:		linux
    arch:		x86_64
    host:		linux
    demo:		y
    prof:		n
    debug:		n
    small:		n
    ccache:		
    distcc:		
packages:
    tbox:		y
    luajit:		y
    base:		y
directories:
    install:		
    package:		
toolchains:
    bin:		
    pre:		
    sdk:		
flags:
    cflag:		
    ccflag:		
    cxflag:		
    mflag:		
    mmflag:		
    mxflag:		
    ldflag:		
    asflag:		
    arflag:		
    shflag:		
clean xmake
clean xmake
clean demo
make xmake
make xmake
compile.r machine.c
compile.r os/chdir.c
compile.r os/cpdir.c
compile.r os/cpfile.c
compile.r os/curdir.c
compile.r os/emptydir.c
compile.r os/exists.c
compile.r os/find.c
compile.r os/getenv.c
compile.r os/isdir.c
compile.r os/isfile.c
compile.r os/mclock.c
compile.r os/mkdir.c
compile.r os/mtime.c
compile.r os/rename.c
compile.r os/rmdir.c
compile.r os/rmfile.c
compile.r os/setenv.c
compile.r os/strerror.c
compile.r os/tmpdir.c
compile.r os/uuid.c
compile.r path/absolute.c
compile.r path/is_absolute.c
compile.r path/relative.c
compile.r path/translate.c
compile.r process/close.c
compile.r process/open.c
compile.r process/openv.c
compile.r process/wait.c
compile.r process/waitlist.c
compile.r string/endswith.c
compile.r string/startswith.c
compile.r string/strcmp.c
compile.r xmake.c
link libxmaker.a
make demo
compile.r xmake.c
link demo.b
/home/darksun/xmake/core/suffix.mak:302: recipe for target 'demo.b' failed
make[2]: *** [demo.b] Error 1
/home/darksun/xmake/core/suffix.mak:303: recipe for target 'SUB_PROS_demo_all' failed
make[1]: *** [SUB_PROS_demo_all] Error 2
makefile:39: recipe for target 'all' failed
make: *** [all] Error 2
output xmake
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(math.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(stdlib.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(printf_object.c.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(singleton.c.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(trace.c.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(network.c.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(ipv6.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(server.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(cache.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(remove_if.c.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(vector.c.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(mem.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(hash.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(str.c.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(hash_map.c.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(mem.c.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(ptr.c.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(isqrti.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(path.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(ifaddrs.c.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(socket.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(directory.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(thread.c.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(dns.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(uuid.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(random.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(vsnprintf.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(native_allocator.c.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(data.c.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(stream.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(url.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(ipaddr.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(ipv4.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(hwaddr.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(heap_sort.c.o): relocation R_X86_64_32 against hidden symbol `tb_iterator_comp' can not be used when making a shared object
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(quick_sort.c.o): relocation R_X86_64_32 against hidden symbol `tb_iterator_comp' can not be used when making a shared object
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(bubble_sort.c.o): relocation R_X86_64_32 against hidden symbol `tb_iterator_comp' can not be used when making a shared object
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(list.c.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(list_entry.c.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(hash_set.c.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(idivi8.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(thread_local.c.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(base64.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(fixed_pool.c.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(http.c.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(file.c.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(sock.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(http.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(method.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(cookies.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(binary_find.c.o): relocation R_X86_64_32 against hidden symbol `tb_iterator_comp' can not be used when making a shared object
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(true.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(single_list_entry.c.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(addrinfo.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(url.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(filter.c.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(chunked.c.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(cache.c.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(date.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/tbox.pkg/lib/release/linux/x86_64/libtbox.a(size.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_err.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_str.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_debug.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_state.o): relocation R_X86_64_32S against hidden symbol `lj_alloc_f' can not be used when making a shared object
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_dispatch.o): relocation R_X86_64_32S against hidden symbol `lj_bc_ofs' can not be used when making a shared object
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_api.o): relocation R_X86_64_32S against hidden symbol `lj_obj_typename' can not be used when making a shared object
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_lex.o): relocation R_X86_64_32S against hidden symbol `lj_char_bits' can not be used when making a shared object
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_parse.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_load.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_trace.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_ctype.o): relocation R_X86_64_32S against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_ccallback.o): relocation R_X86_64_32S against hidden symbol `lj_vm_ffi_callback' can not be used when making a shared object
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lib_aux.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lib_ffi.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lib_init.o): relocation R_X86_64_32 against symbol `luaopen_base' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_gc.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_meta.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_vmevent.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_strscan.o): relocation R_X86_64_32S against hidden symbol `lj_char_bits' can not be used when making a shared object
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_bcread.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_bcwrite.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_ir.o): relocation R_X86_64_32S against hidden symbol `lj_ir_callinfo' can not be used when making a shared object
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_opt_fold.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_opt_dce.o): relocation R_X86_64_32S against hidden symbol `lj_ir_mode' can not be used when making a shared object
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_opt_loop.o): relocation R_X86_64_32S against hidden symbol `lj_ir_mode' can not be used when making a shared object
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_opt_sink.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_mcode.o): relocation R_X86_64_32 against hidden symbol `lj_vm_exit_handler' can not be used when making a shared object
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_snap.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_record.o): relocation R_X86_64_32S against hidden symbol `lj_vm_asm_begin' can not be used when making a shared object
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_ffrecord.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_asm.o): relocation R_X86_64_32S against hidden symbol `lj_ir_mode' can not be used when making a shared object
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_cconv.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_carith.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_clib.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_cparse.o): relocation R_X86_64_32S against hidden symbol `lj_char_bits' can not be used when making a shared object
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_lib.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lib_base.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lib_math.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lib_bit.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lib_string.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lib_table.o): relocation R_X86_64_32S against hidden symbol `lj_obj_itypename' can not be used when making a shared object
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lib_io.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lib_os.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lib_package.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lib_debug.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lib_jit.o): relocation R_X86_64_32S against hidden symbol `lj_ir_callinfo' can not be used when making a shared object
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_opt_mem.o): relocation R_X86_64_32S against hidden symbol `lj_ir_type_size' can not be used when making a shared object
/usr/bin/ld: /home/darksun/xmake/core/pkg/luajit.pkg/lib/release/linux/x86_64/libluajit.a(lj_crecord.o): relocation R_X86_64_32S against hidden symbol `lj_ir_type_size' can not be used when making a shared object
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status

**Comment by waruqi** [comment]
Please tell me your gcc's version and os info.

Thanks!

**Comment by avaicode** [comment]
My OS is lubuntu
> ➜  ~ uname -a
Linux darksun 4.8.0-32-generic # 34-Ubuntu SMP Tue Dec 13 14:30:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
➜  ~ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 6.2.0-5ubuntu12' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.2.0 20161005 (Ubuntu 6.2.0-5ubuntu12)

**Comment by waruqi** [comment]
I have fixed this link error.

Please checkout dev branch and reinstall xmake.

Thanks.

**Comment by avaicode** [comment]
Well,I can install it now.
Cheers
