### ISSUE TITLE
wiki中 "Introduction (中文)" 的 "中文" 这个链接错了

### ISSUE THREAD

**Issue by guyskk** [tboox/xmake#48]
wiki页面: https://github.com/tboox/xmake/wiki
正确的链接应该是: https://github.com/tboox/xmake/wiki/目录

**Comment by guyskk** [comment]
发现我可以编辑wiki，就直接修改了

**Comment by waruqi** [comment]
额。。好吧。。

其实那个中文， 是指 中文版本的 项目介绍。。跟项目中的README.md内容是完全一样的，我直接copy过去的，之后如果README更新了，也许还会被覆盖掉。。= =

实际的文档，可以直接看右侧：侧边栏，有分 中文文档。和  英文文档的。。

**Comment by guyskk** [comment]
明白了，从项目首页点击 “中文” 链接就是正常的

**Comment by waruqi** [comment]
哦哦 可能是我直接从README上copy到 wiki，这个中文路径设置 有点问题，之前确实没考虑到这个。。

谢谢哈。。
