### ISSUE TITLE
adb shell /data/local/tmp/demo error: only position independent executables (PIE) are supported.

### ISSUE THREAD

**Issue by 1491163117** [tboox/xmake#50]

**Comment by waruqi** [comment]
Can you give me more verbose info?  

Thank!

**Comment by waruqi** [comment]
This is the problem on android > 5.x, and you can add the following flags to `xmake.lua` for fixing it.

```lua
if is_plat("android") then
    add_cxflags("-fPIE", "-pie")
    add_ldflags("-fPIE", "-pie")
end
```

Thanks!

**Comment by waruqi** [comment]
I have fixed this problem, please try the lastest commit from dev branch.

Thanks!
