### ISSUE TITLE
[FEATURE REQUEST] pacman support

### ISSUE THREAD

**Issue by silvioprog** [tboox/xmake#51]
Hello masters,

It would by nice to install `xmake` via `pacman` on mingw.

(I installed mingw setup `msys2-i686-20161025.exe` available at http://www.msys2.org, `xmake` can't be found via `pacman -Ss xmake` :-/)

**Comment by waruqi** [comment]
You can download `xmake.exe` windows installer to install it from [releases](https://github.com/tboox/xmake/releases)

**Comment by waruqi** [comment]
[Install Documents](http://xmake.io/#/home?id=installation)

**Comment by silvioprog** [comment]
Perfect! :-)
