### ISSUE TITLE
是否有考虑打包成单文件

### ISSUE THREAD

**Issue by zhangzpap** [tboox/xmake#56]
是否有考虑打包成单文件运行或者将[.lua]文件打包成一个文件

我把xmake放在跟随项目，这样方便版本维护和更新我自己写的插件，但是xmake的.lua文件比我项目的文件还多， 虽然不影响什么东西，但是对项目的管理还是比较不好的

**Comment by waruqi** [comment]
可以像我的 tbox的那样，在makefile里面，自动下载指定版本xmake的zip包，在工程本地目录安装运行，来实现跟随编译。。

或者直接内置zip包来跟随工程，整个zip也就几百k

**Comment by waruqi** [comment]
可以参考：https://github.com/tboox/tbox/blob/master/makefile
