### ISSUE TITLE
"add_headers" generate header files with executable permission

### ISSUE THREAD

**Issue by TitanSnow** [tboox/xmake#57]
My <code>xmake.lua</code> is:

```lua
-- something else --
target("bg")
    set_options("default")
    set_kind("$(kind)")
    add_files("src/bigint.cpp")
    add_headers("src/bigint.h")    -- HERE "add_headers"
    add_defines("BIGINT_FFT_TRIGGER=0x1000000")
target_end()
```

<code>src/bigint.h</code> is with normal permission, <code>-rw-r--r--</code>, aka <code>100644</code> in git.

After building I got <code>build/bigint.h</code> but it is with executable permission, <code>-rwxr-xr-x</code>, aka <code>100755</code> in git.

Why the permission has been changed? I do not think header files should be executable. Or it has its special meanings?

The whole repository can be seen at [TitanSnow/libBG:xmake](https://github.com/TitanSnow/libBG/tree/xmake)

**Comment by waruqi** [comment]
I have fixed this bug, please checkout the lastest master commit and try it again.

Thanks!
