### ISSUE TITLE
360报毒什么鬼？

### ISSUE THREAD

**Issue by junhwong** [tboox/xmake#58]
windows 上 360报毒：安装包，和卸载程序

**Comment by waruqi** [comment]
我是使用 nsis 制作的安装包。。360如果要报毒的 也正常。没能力放到他们的白名单中去。。

之前我有windows上编译安装的bat脚本，后来制作了安装包后我删了，如果你需要的话，我后两天再放上去，你从源码安装。。

**Comment by junhwong** [comment]
@waruqi 好的。我看了觉得可以放个zip包，好像报毒的就是那个打包程序（安装包和卸载程序）。

**Comment by waruqi** [comment]
我放置了个安装包的zip 到 release 上，你试试？
