### ISSUE TITLE
couldn't self-build

### ISSUE THREAD

**Issue by TitanSnow** [tboox/xmake#60]
```console
~/xmake/core$ xmake
error: /usr/local/share/xmake/core/base/option.lua:94: assertion failed!
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/xmake/core/base/option.lua:94: in function '_context'
	/usr/local/share/xmake/core/base/option.lua:787: in function 'options'
	/usr/local/share/xmake/core/base/option.lua:745: in function 'get'
	/usr/local/share/xmake/core/base/utils.lua:37: in function '_print'
	/usr/local/share/xmake/core/base/utils.lua:78: in function 'cprint'
	/usr/local/share/xmake/core/base/utils.lua:118: in function 'error'
	/usr/local/share/xmake/core/main.lua:113: in function </usr/local/share/xmake/core/main.lua:105>
```

Is there any other work needed to do to self-build?

**Comment by waruqi** [comment]
It works here.

Can you run `xmake --version` to tell me your xmake version? 

And run `xmake -v --backtrace` to get more verbose backtrace info, or please attempt to update the newest version.

Thanks!

**Comment by TitanSnow** [comment]
Sorry, my mistake

**Comment by waruqi** [comment]
Ok, I push a patch to master and improve error tips in order to locate problem more quickly in future.

**Comment by TitanSnow** [comment]
I'm trying to let xmake self-build on CIs. But it seems that only Linux could do this.

Branch: [TitanSnow:self_build](https://github.com/TitanSnow/xmake/tree/self_build)

[Build on travisCI](https://travis-ci.org/TitanSnow/xmake/builds/215363101), Linux succeeded but Mac OS failed.

[Build on appveyor](https://ci.appveyor.com/project/TitanSnow/xmake/build/1.0.15), failed on Windows

**Comment by waruqi** [comment]
I have fixed self-build on macOS, you can see thee patch [d3865a3](https://github.com/tboox/xmake/commit/f9ff6e5e50c26501964a3b35279aa4881d3865a3) from dev branch.

I need modify and rebuild libluajit.a to support vs201x compiler and it only support vs200x compiler now.

Please wait some time. I will fix it in future.

Thanks!

**Comment by TitanSnow** [comment]
It seems that xmake uses binary library file to satisfy dependencies. Will it be better to build dependencies from source together?

**Comment by waruqi** [comment]
I will consider this suggestion.

Thanks

**Comment by waruqi** [comment]
I have fixed it on appveyor, please try the lastest commit from dev branch.

And it build luajit from source codes now.

**Comment by TitanSnow** [comment]
Looks nice. You have a quick action:smiley:
