### ISSUE TITLE
今天刚刚换了台电脑，编译出了点问题，请问是什么引起？

### ISSUE THREAD

**Issue by bnq4ever** [tboox/xmake#70]
我已经配好NDK了，弄了半天没看出什么问题

PedestrianStateW git:(develop) ✗ xmake --verbose
configure
{
    ccache = false
,   ndk = "/Users/benson/android-ndk-r10e"
,   toolchains_ver = "4.8"
,   host = "macosx"
,   ar = "/Users/benson/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-ar"
,   buildir = "build"
,   toolchains = "/Users/benson/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin"
,   ndk_sdkver = 21
,   arch = "armv7-a"
,   mode = "release"
,   cc = "gcc"
,   xcode_dir = "/Applications/Xcode.app"
,   kind = "static"
,   ld = "g++"
,   cxx = "g++"
,   plat = "android"
,   sh = "g++"
}
[00%]: compiling.release PedestrianStateW/EscalatorDetect.cpp
g++ -c -I/Users/benson/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.8/include -I/Users/benson/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a/include -march=armv7-a -mthumb --sysroot=/Users/benson/android-ndk-r10e/platforms/android-21/arch-arm -o build/.objs/PedestrianStateW/PedestrianStateW/EscalatorDetect.cpp.o PedestrianStateW/EscalatorDetect.cpp
/usr/local/Cellar/xmake/2.1.3/share/xmake/core/base/os.lua:569: clang: warning: argument unused during compilation: '-mthumb' [-Wunused-command-line-argument]
error: unknown target CPU 'armv7-a'
stack traceback:
    [C]: in function 'error'
    [/usr/local/Cellar/xmake/2.1.3/share/xmake/core/base/os.lua:569]: in function 'raise'
    [...llar/xmake/2.1.3/share/xmake/core/sandbox/modules/os.lua:258]: in function 'iorun'
    [/usr/local/Cellar/xmake/2.1.3/share/xmake/tools/gcc.lua:318]:
error: /usr/local/Cellar/xmake/2.1.3/share/xmake/core/base/os.lua:569: clang: warning: argument unused during compilation: '-mthumb' [-Wunused-command-line-argument]
error: unknown target CPU 'armv7-a'

stack traceback:
    [C]: in function 'error'
    [/usr/local/Cellar/xmake/2.1.3/share/xmake/core/base/os.lua:569]: in function 'raise'
    [...llar/xmake/2.1.3/share/xmake/core/sandbox/modules/os.lua:395]: in function 'raise'
    [...ake/2.1.3/share/xmake/core/sandbox/modules/coroutine.lua:59]: in function 'resume'
    [...r/xmake/2.1.3/share/xmake/actions/build/kinds/object.lua:194]: in function '_build_each_objects'
    [...r/xmake/2.1.3/share/xmake/actions/build/kinds/object.lua:323]: in function 'build'
    [...r/xmake/2.1.3/share/xmake/actions/build/kinds/static.lua:35]: in function '_build_from_objects'
    [...r/xmake/2.1.3/share/xmake/actions/build/kinds/static.lua:132]: in function 'build'
    [...Cellar/xmake/2.1.3/share/xmake/actions/build/builder.lua:38]: in function 'script'
    [...Cellar/xmake/2.1.3/share/xmake/actions/build/builder.lua:56]: in function '_build_target'
    [...Cellar/xmake/2.1.3/share/xmake/actions/build/builder.lua:78]: in function '_build_target_and_deps'
    [...Cellar/xmake/2.1.3/share/xmake/actions/build/builder.lua:150]: in function 'build'
    [...al/Cellar/xmake/2.1.3/share/xmake/actions/build/main.lua:73]:

**Comment by waruqi** [comment]
这个是最近新版本 我修改了检测机制 引出的问题，正在修复中，你可以尝试回退到上一个版本 来编译 android 程序。

谢谢

**Comment by waruqi** [comment]
我修复了这个问题，请更新到最新的master版本，再试下，谢谢。。
