### ISSUE TITLE
automatic linker detection

### ISSUE THREAD

**Issue by TitanSnow** [tboox/xmake#71]
[travis ci log](https://travis-ci.org/TitanSnow/libBG/jobs/221207662)

In short, when environment var $CXX==clang++ (build with clang++ on travis-ci), xmake uses clang++ to compile but g++ to link.

In common situation, it will not cause problems. But it fails when compiling with code coverage (flag `-coverage`).

By the way, is there a easy way in xmake to compile with code coverage?

**Comment by waruqi** [comment]
You need set environment var $LD==clang++ if $CXX==clang++ .

And you can write a mode named `coverage` in `xmake.lua`:

```
if is_mode("coverage") then
        add_cxflags("--coverage")
        add_ldflags("--coverage")
end
```

Then run:

```bash
$ xmake f -m coverage
$ xmake
```

**Comment by TitanSnow** [comment]
Sounds right. So you mean travis-ci does wrong with environment var setting?

**Comment by TitanSnow** [comment]
By the way, is `-coverage` cross-platform? Will xmake set it smartly?

**Comment by waruqi** [comment]
travis-ci only modify $CXX and did not tell xmake which linker to choose, so xmake will use the default linker if cannot get $(LD).

I'm sorry, xmake do not support to adjust the linker's detection order automatically according to $CXX now. I will improve it in the future.

You can modify travis-ci setting to export LD=clang++ now.

**Comment by waruqi** [comment]
How do you need to set it smartly?  You can call `add_cxflags("-coverage")` to set it directly. If some compilers do not support this flags, xmake will check and ignore it.

**Comment by TitanSnow** [comment]
What I mean is that sometimes just simply ignore flags that not supported sounds not good enough. I found you map `-fomit-frame-pointer` to `-Oy` on VS

**Comment by waruqi** [comment]
xmake support to map flags to other compilers. (.e.g vs, ..)  you can see https://github.com/tboox/xmake/blob/master/xmake/tools/cl.lua

xmake takes the gcc flags as the standard and will map to other compiler flags smartly.

you can help me to contribute some patches to the following `mapflags` ff the option you need does not provide a mapping yet

```lua
    _g.mapflags = 
    {
        -- optimize
        ["-O0"]                     = "-Od"
    ,   ["-O3"]                     = "-Ot"
    ,   ["-Ofast"]                  = "-Ox"
    ,   ["-fomit-frame-pointer"]    = "-Oy"
    ,   ["-g"]                      = "-Z7"
    ,   ["-fvisibility=.*"]         = ""
```

**Comment by TitanSnow** [comment]
I see :smile_cat:

**Comment by TitanSnow** [comment]
> update title to "automatic linker detection"

**Comment by TitanSnow** [comment]
I have looked up in msdn. I think optimize flags should be mapped as this:

```diff
diff --git a/xmake/tools/cl.lua b/xmake/tools/cl.lua
index 6888199..07a1b98 100644
--- a/xmake/tools/cl.lua
+++ b/xmake/tools/cl.lua
@@ -42,8 +42,10 @@ function init(shellname, kind)
     {
         -- optimize
         ["-O0"]                     = "-Od"
-    ,   ["-O3"]                     = "-Ot"
-    ,   ["-Ofast"]                  = "-Ox"
+    ,   ["-O1"]                     = ""
+    ,   ["-Os"]                     = "-O1"
+    ,   ["-O3"]                     = "-Ox"
+    ,   ["-Ofast"]                  = "-Ox -fp:fast"
     ,   ["-fomit-frame-pointer"]    = "-Oy"
 
         -- symbols
```

[/O Options (Optimize Code) - msdn](https://msdn.microsoft.com/en-us/library/k1ack8f1.aspx)

**Comment by waruqi** [comment]
vc support `-Os` flags directly, why should change mapping `-Os` to `-O1`? Is vc's`-Os` equivalent to gcc's `-Os`?

* /Os tells the compiler to favor optimizations for size over optimizations for speed.

**Comment by TitanSnow** [comment]
`-Os` is a subset of `-O1`

> /O1 (Minimize Size)    Equivalent to    /Og /Os /Oy /Ob2 /Gs /GF /Gy

And there it says:

> If you use /Os or /Ot, then you must also specify /Og to optimize the code.

**Comment by waruqi** [comment]
👍 I got it. Can you submit a patch to dev branch? I will merge it, thanks!

**Comment by TitanSnow** [comment]
But I haven't test it yet because I don't have Windows. :crying_cat_face: 

Could you quickly test to know if it could work?

**Comment by waruqi** [comment]
Ok, I will test it.

**Comment by waruqi** [comment]
I have commited this patch.

**Comment by TitanSnow** [comment]
:smiley_cat: Sorry for trouble

**Comment by waruqi** [comment]
That's nothing. 😄

**Comment by TitanSnow** [comment]
@waruqi Could give a milestone? I found automatic linker detection is important in some situation

**Comment by waruqi** [comment]
@TitanSnow Yes, I'll improve and support it in the future, but it will take some time.

**Comment by waruqi** [comment]
@TitanSnow 

> In short, when environment var $CXX==clang++ (build with clang++ on travis-ci), xmake uses clang++ to compile but g++ to link.

I have fixed it in dev branch.
