### ISSUE TITLE
repl wanted

### ISSUE THREAD

**Issue by TitanSnow** [tboox/xmake#79]
*Feature Request*

repl needed to write & test script more easily

That is, each time I wanna do something, for example have a look at `path.join()`, I have to write a simple statement to a file then use `xmake lua` to run it. That's troublesome. A repl like other script languages have is good-to-use

I tried to impl it by myself but it has trouble with sandbox

**Comment by waruqi** [comment]
This is a very nice feature, I also wanted to add this feature before. I saw the implementation of `luajit.c`, It seems not very complicated, I will attempt to implement it in this week if everything goes well.

**Comment by TitanSnow** [comment]
:+1:

**Comment by waruqi** [comment]
I have finished this feature on linux/macosx. (not yet tested it on windows)

You can run `xmake lua` to run interactive commands. for example:

```bash
$ xmake lua

> import("core.project.task")
> task.run("hello")
>
> print(path.join("/tmp", "xxx"))
>
> = 1+2+3 / 4
>
> a = 1
> print(a)
>
> for _, v in pairs({1, 2, 3}) do
>> print(v)
>> end
```

**Comment by TitanSnow** [comment]
```
> 1
stdin:1: unexpected symbol near '1'
> a=1
> a
>> 
```

I think a single val should be printed directly

like python:
```
>>> 1
1
>>> a=1
>>> a
1
```

**Comment by TitanSnow** [comment]
Anyway :+1:

**Comment by waruqi** [comment]
@TitanSnow I agree with your point, but I don't know how to distinguish them in lua.

So you need add prefix character '=' to eval expr now.

```
> = 1 + 3 +5
9
> = 1
1
```

Or you can help me improve it. [interactive.c:168](https://github.com/tboox/xmake/blob/dev/core/src/xmake/sandbox/interactive.c)

**Comment by TitanSnow** [comment]
I'd like to look into it :smiley:

**Comment by TitanSnow** [comment]
I found some info on [stackoverflow](http://stackoverflow.com/questions/20410082) that might be workable

**Comment by TitanSnow** [comment]
lua 5.3 uses pre-check to know whether a statement could `return`
```C
  const char *retline = lua_pushfstring(L, "return %s;", line);
  int status = luaL_loadbuffer(L, retline, strlen(retline), "=stdin");
  if (status == LUA_OK) {
    // ...
```
at lua.c:334 (5.3.4)

**Comment by waruqi** [comment]
@TitanSnow I tried this way before, but this method can't handle some function calls well. for example:

```bash
> import("core.project.task")
> task.run("xxx")  <------ will failed, task not found
```

These function calls can also be returned, but `return import("...")` cannot affect the scope of the outside

**Comment by TitanSnow** [comment]
@waruqi That's too bad :disappointed: I couldn't figure out why it will be so -- `return` break scope? Maybe lua is a magic language that makes me  :cyclone:

**Comment by waruqi** [comment]
@TitanSnow And it's hard to distinguish whether you want to print the return value. Any function call that has a return value will be printed
 
for example:

```lua
function test()
    -- do some thing

    -- ok
    return true
end
```

then, we run it using `return test()`

```bash
> test()
true      -- maybe I don't want to see this return value
```

**Comment by TitanSnow** [comment]
I remember in python repl any function call that has a return value will be printed

**Comment by TitanSnow** [comment]
I think now there are two thing needed to be done:
* in multiline input, I need a cancel way. `<C-C>`?
* the `readline` library itself is common in posix system but the headers might be not. On my ubuntu, unless `libreadline-dev` is installed, there's no header `readline/*`

    there are two solutions:
    * add require of `readline` development files
    * do not include the header. Declare them manually:
        ```diff
        diff --git a/core/src/xmake/sandbox/interactive.c b/core/src/xmake/sandbox/interactive.c
        index 339ab9cc..da3c7a8e 100644
        --- a/core/src/xmake/sandbox/interactive.c
        +++ b/core/src/xmake/sandbox/interactive.c
        @@ -41,8 +41,8 @@
          */
         #include "prefix.h"
         #ifndef TB_CONFIG_OS_WINDOWS
        -#   include <readline/readline.h>
        -#   include <readline/history.h>
        +    extern char* readline   (const char*);
        +    extern void  add_history(const char*);
         #endif
 
         /* //////////////////////////////////////////////////////////////////////////////////////
        ```

**Comment by waruqi** [comment]
@TitanSnow It try loading `return expr` first now. You can try it.

```bash
> 1 + 2
3

> a = 1
> a
1
```

But you need assign var manually when call `import` now.

```
> task = import("core.project.task")
> task.run("hello")
```

**Comment by waruqi** [comment]
@TitanSnow 

* in multiline input, I need a cancel way. <C-C>?

You can input `q` to cancel multiline input, for example:

```bash
> for _, v in ipairs({1, 2}) do
>> print(v)
>> q             <--  cancel multiline and clear previous input
> 1 + 2
3
```

* the readline library itself is common in posix system but the headers might be not. On my ubuntu, unless libreadline-dev is installed, there's no header readline/*

I fixed it

```c
+    extern char* readline   (const char*);
+    extern void  add_history(const char*);
```

**Comment by TitanSnow** [comment]
:+1:

**Comment by TitanSnow** [comment]
A very bad message: I tested carefully again, found that **although `libreadline` has installed, xmake couldn't build successfully even declare functions manually, `libreadline-dev` is required.** And `libreadline-dev` is not one of `build-essential` package group. So that install scripts must be modified to add this requirement @waruqi

**Comment by waruqi** [comment]
@TitanSnow But it passed on ci.Can you give me some build error info? I try to fix it and detect libreadline . If this library not found, I will continue to uses fgets when building.

**Comment by TitanSnow** [comment]
[Travis CI](https://travis-ci.org/TitanSnow/xmake_getter_tester/jobs/229359454)

**Comment by TitanSnow** [comment]
Better to install this library if not found

**Comment by waruqi** [comment]
ok, I will fix it in recent days.

**Comment by waruqi** [comment]
@TitanSnow I want to use the following two solutions:

1. Try detect libreadline.a before building, I will use `fgets` if `readline` not found. (It done)
2. Modify `get.sh` to install this library via package manager if not found (Can you help me modify it?)

**Comment by TitanSnow** [comment]
:ok_hand:

**Comment by waruqi** [comment]
@TitanSnow Thanks! 😸

**Comment by TitanSnow** [comment]
```console
$ xmake --version
XMake v2.1.4.201705081849, The Make-like Build Utility based on Lua
Copyright (C) 2015-2016 Ruki Wang, tboox.org, xmake.io
Copyright (C) 2005-2015 Mike Pall, luajit.org
$ xmake lua
> os.execv('git',{'--version'})
git version 2.11.0
> os.runv
function: 0xb71601e8
> os.runv('git',{'--version'})
/usr/local/share/xmake/core/base/os.lua:569: runv(git --version) failed(-1)!
stack traceback:
	[C]: in function 'error'
	/usr/local/share/xmake/core/base/os.lua:569: in function 'raise'
	/usr/local/share/xmake/core/sandbox/modules/os.lua:245: in function </usr/local/share/xmake/core/sandbox/modules/os.lua:237>
	[C]: in function 'interactive'
	...ake/core/sandbox/modules/import/core/sandbox/sandbox.lua:51: in function 'interactive'
	/usr/local/share/xmake/plugins/lua/xmake.lua:60: in function </usr/local/share/xmake/plugins/lua/xmake.lua:32>
	[C]: in function 'load'
	/usr/local/share/xmake/core/project/task.lua:423: in function 'run'
	/usr/local/share/xmake/core/main.lua:188: in function </usr/local/share/xmake/core/main.lua:151>
> 
```

**?**

**Comment by waruqi** [comment]
@TitanSnow I have fixed it.
