### ISSUE TITLE
.cmake Adaptor (detection modules)?

### ISSUE THREAD

**Issue by htfy96** [tboox/xmake#83]
The main reason why I still stick to CMake is its [builtin modules](https://github.com/Kitware/CMake/tree/master/Modules) which provide compiler detection/package search/etc. It is unnecessary to reinvent the wheels, so I was wondering is it possible to provide (at least kind of) `.cmake` support and wrap these modules into `xmake` utilities?

**Comment by waruqi** [comment]
xmake also provide these features, so don't intend to wrap them.

**Comment by TitanSnow** [comment]
Compiler detection of xmake is perfect

"Package search" is working on the way. You could have a look branch `repo`

Thanks for caring :smiley:

**Comment by htfy96** [comment]
Thanks for reply. I'm just a little bit worried that there might be a lot more to do than you think. Take C++ as an example, we may need:
- feature test: whether this compiler supports variadic template, or is it claimed supported but actually buggy? 
- compiler detection: we may be running clang frontend of MSVC, and many other corner cases
- compiler*platform-specific options: including sanitize/floating point accuracy/etc.

Supporting `.cmake` may reduce some kind of work, I guess.

**Comment by TitanSnow** [comment]
I'd like to have a look into it this week

**Comment by waruqi** [comment]
And you can add  `add_cxflags("-fsanitize=address", "-ftrapv")` directly.

If compiler does not support these flags, It will ignore it automatically.

**Comment by waruqi** [comment]
xmake will detect msvc on windows by default automatically. If you want to use other compiler, you can set it manually. for example:

```bash
$ xmake f --cc=clang --cxx=clang --ld=clang
$ xmake
```

**Comment by htfy96** [comment]
@waruqi 

IIUC, according to your example `xmake` currently has no plan for builtin feature detection based on compiler version, instead, it provides basic utilities like `add_cxxfuncs` to allow custom detection. The main drawbacks of the absence of builtin `has_variadic_template`/`support_cxx_11` include:
- We have to compile during configuration for many times if we have a lot of orthogonal features to detect
- Some feature detections are not as simple as `add_cfuns(sigsetjmp((void*)0, 0)` and requires heavy templates and domain knowledge

Actually I'm more willing to see something like `enable_sanitize_address` which adds proper flags for every compiler supporting this feature. Hard-coded/compiler-dependent flags are not encouraged from my perspective, and I want to completely eliminate these in my build scripts.

I'm referring to Clang/C2 frontend of MSVC. Take a look into CMake's patch set, and you'll find that checking `_MSC_VER` is not enough.

**Comment by waruqi** [comment]
@htfy96 Yes, xmake currently has no plan for builtin feature detection based on compiler version. 

> We have to compile during configuration for many times if we have a lot of orthogonal features to detect

This is only configured and detected once

> Some feature detections are not as simple as `add_cfuns(sigsetjmp((void*)0, 0)` and requires heavy templates and domain knowledge

This is not a problem, the detection rules can be improved more flexibly.

> Hard-coded/compiler-dependent flags

xmake takes the gcc flags as the standard and will map to other compiler flags smartly. 

So these flags (`-fsanitize=addres`, `-fomit-frame-pointer`) are not `hard-coded/compiler-dependent`, you can see [#71](
https://github.com/tboox/xmake/issues/71)

About `enable_sanitize_address `,  why not do the testing directly in the code?

```c
#if (defined(__has_feature) && __has_feature(address_sanitizer)) || \
        defined(__SANITIZE_ADDRESS__)
...
#endif
```

**Comment by htfy96** [comment]
@waruqi 
Thanks for detailed reply. One more question, how can I switch flags based on whether a code snippet can compile without error? For example, I want to detect constexpr support:

```
option("test_cxx11_constexpr")
    add_defines_if_ok("CXX11_CONSTEXPR")
    add_cxxfuncs("has_cxx11_constexpr{ constexpr int f(int x) { return x ? x+f(x-1) : 0; } constexpr int x = f(5); static_assert(x == 15); ")

option("test_cxx14_constexpr")
    add_defines_if_ok("CXX14_CONSTEXPR")
    add_cxxfuncs("has_cxx14_constexpr{ constexpr int f(int x) { int sum=0; for (int i=0; i<=x; ++i) sum += i; return sum; } constexpr int x = f(5);  static_assert(x == 15);")
```

This doesn't seem to work.

**Comment by TitanSnow** [comment]
> Actually I'm more willing to see something like enable_sanitize_address

Now for flags adding, xmake uses gcc flags mapping

Advantage:
* easier to remember

Disadvantage:
* Some flags are not mapped yet. See #71 I wanna to add a flag for coverage but `-coverage` is not mapped. And compilers are difficult so some flags cannot be implemented on some compiler

I agree with generic flags as what you said as a second choice

**Comment by TitanSnow** [comment]
A good problem @htfy96 

Seems that not supported yet, right? @waruqi

**Comment by htfy96** [comment]
And consider this case: user specified `-fsanitize=address` in `xmake.lua`, but actually the machine is running an older version of C2 on MSVC(e.g. Clang/C2 in MSVC14 Update 1) [which has not `sanitize` support](https://cmake.org/gitweb?p=cmake.git;a=commitdiff;h=1f913700). How do you deal with such kind of issue?

The initiative of this issue is that compatibility/detection is extremely difficult. Manual checking could be very time-consuming and complicated. It is difficult to implement your own compiler database like `CMake`  from scratch as well, since if you want to support `N` compilers, each of which has `K` versions, and you have `P` features to check, the database will soon balloons to `N * K * P`. Therefore, the best choice in this case is to adapt existing CMake databases.

**Comment by waruqi** [comment]
@htfy96 `add_cxxfuncs` and `add_cfuncs` only used to detect if the function interface exists. I will add `add_snippet()` to detect other feature support in the future, for example:

```
option("constexpr")
    add_snippet("cxx", "constexpr int f(int x) { int sum=0; for (int i=0; i<=x; ++i) sum += i; return sum; } constexpr int x = f(5);  static_assert(x == 15);")
```

**Comment by waruqi** [comment]
> And consider this case: user specified -fsanitize=address in xmake.lua, but actually the machine is running an older version of C2 on MSVC(e.g. Clang/C2 in MSVC14 Update 1) which has not sanitize support. How do you deal with such kind of issue?

If has not sanitize support, `add_cxflags("-fsanitize=addres")` will ignore it when building project

**Comment by waruqi** [comment]
> The initiative of this issue is that compatibility/detection is extremely difficult. Manual checking could be very time-consuming and complicated. It is difficult to implement your own compiler database like CMake from scratch as well, since if you want to support N compilers, each of which has K versions, and you have P features to check, the database will soon balloons to N * K * P. Therefore, the best choice in this case is to adapt existing CMake databases.

Therefore, even using the CMake database does not guarantee all compilers. The most stable way is that try to compile it to detect it

**Comment by htfy96** [comment]
@waruqi 
Validity check of snippets cannot be bulk-executed since an error in one snippet can easily affect others.

The `-fsanitize` example actually targets the underlying problem compiler detection: in order to detect whether this flag is supported, you need to compile with it during configuration instead of mapping it manually in scripts, as what you just mentioned.

Moreover, some features cannot be detected at compile-time. For example: `<regex>` in g++-4.8 defined all functions with empty implementation.

**Comment by TitanSnow** [comment]
> @htfy96 add_cxxfuncs and add_cfuncs only used to detect if the function interface exists. I will add add_snippet() to detect other feature support in the future, for example:

:+1: @waruqi 

`add_snippet()` is great. Just like my way to check if `libreadline` exists in Makefile in #80 . I'd like to try writing a first implement these days

> The initiative of this issue is that compatibility/detection is extremely difficult. Manual checking could be very time-consuming and complicated. It is difficult to implement your own compiler database like CMake from scratch as well, since if you want to support N compilers, each of which has K versions, and you have P features to check, the database will soon balloons to N * K * P. Therefore, the best choice in this case is to adapt existing CMake databases.

You're right @htfy96 

> in order to detect whether this flag is supported, you need to compile with it during configuration instead of mapping it manually in scripts, as what you just mentioned.

xmake do you say, compile with it during configuration to check whether a flag is available @htfy96 

> Moreover, some features cannot be detected at compile-time. For example: <regex> in g++-4.8 defined all functions with empty implementation.

Great example :+1: @htfy96 

Maybe best solution is
* detection first, database second
* flag mapping first, generic flags second

**Comment by waruqi** [comment]
> Validity check of snippets cannot be bulk-executed since an error in one snippet can easily affect others.

You can define one `option` with a snippet to detect only one feature.

> The -fsanitize example actually targets the underlying problem compiler detection: in order to detect whether this flag is supported, you need to compile with it during configuration instead of mapping it manually in scripts, as what you just mentioned.

You also can use option to detect flags. Although I don't support it now, I'll improve it.

```lua
option("fsanitize_address")
      add_cxflags("-fsanitize=address")  <-- I'll improve it here.
      add_ldflags("-fsanitize=address")
```

**Comment by waruqi** [comment]
@TitanSnow 

> Just like my way to check if libreadline exists in Makefile in #80 . I'd like to try writing a first implement these days

I've detected it in `xmake.lua`, just old `core/makefile` doesn't support. You can see [core/src/xmake/xmake.lua](https://github.com/tboox/xmake/blob/master/core/src/xmake/xmake.lua)

```lua
add_cfunc("API", "readline", nil, {"readline/readline.h"}, "readline")
```

**Comment by waruqi** [comment]
@htfy96 

> Moreover, some features cannot be detected at compile-time. For example: <regex> in g++-4.8 defined all functions with empty implementation.

But many vendors will modify the compiler, even the same version of the compiler does not guarantee that many implementations exist or not.

**Comment by TitanSnow** [comment]
Yep @waruqi  but this is just a example that not so exact  and other code snippets could be used

**Comment by TitanSnow** [comment]
>So there is the same problem with the database.

Database is not no use at all! @waruqi

**Comment by waruqi** [comment]
@TitanSnow  @htfy96  So I'm still more inclined to use compile detection. Perhaps xmake detection is not flexible enough, but I will improve it.

**Comment by htfy96** [comment]
@waruqi 
It is OK to just provide minimal feature detection support, I guess. Users have to deal with it something like `Boost.config`, though in many cases we don't want to introduce Boost dependency. Quite looks like the way of `premake`.

Thanks for your effort. It would be piles of work to implement proper compiler detection.

**Comment by waruqi** [comment]
@htfy96 😄

**Comment by TitanSnow** [comment]
> `add_snippet()` is great. Just like my way to check if `libreadline` exists in Makefile in #80 . I'd like to try writing a first implement these days

Sorry, but for me there's still trouble to implement `add_snippet()`

**Comment by waruqi** [comment]
@TitanSnow I will implement it in last these days.

**Comment by TitanSnow** [comment]
@htfy96 I have quickly looked through `*.cmake` in `cmake/modules`

I found that your idea is great :+1: 

Many things are useful like `findQt.cmake`

In fact trying to link with Qt in xmake might be troublesome or I don't get the way? @waruqi 

And `FindGit.cmake` might be useful for you @waruqi . I know you recently work on branch `repo` requires git

If `.cmake` adapter comes up in the future, I think things will be easier and better.

In this way, **I agree with** @htfy96 

My option is on-fly detection is *the first hand*, off-fly data & script is *the second hand*

*This idea should be minded* @waruqi

Does you have a preliminary way to implement the adapter, @htfy96 ? Or could you do some work on this and finally give a PR?

**Comment by TitanSnow** [comment]
A preliminary roadmap

- [ ] .cmake adapter
  - [ ] cmake syntax support
  - [ ] `.cmake` files include
  - [ ] compiler database support
    - [ ] work with xmake detection
  - [ ] `find_package` support
    - [ ] work with xmake-repo

**Comment by waruqi** [comment]
@TitanSnow 

> And FindGit.cmake might be useful for you @waruqi . I know you recently work on branch repo requires git

Git is a necessary component for `xmake require` action, not just looking for it. So it's not enough to use `FindGit.cmake`. xmake will install winenv with git when using `xmake require`.

xmake also support tool detection and only for internal detection. In the future I will provide public interfaces to find tools like `find_tool` , `find_package` .. 

> If .cmake adapter comes up in the future, I think things will be easier and better.

Xmake has its own design pattern, not depend on `.cmake` or wrap it. But I will provide similar functionality in the future.

**Comment by waruqi** [comment]
@htfy96 I have implemented `add_cxxsnippet` to detect compiler feature. for example: 

```lua
-- define option for detecting constexpr feature
option("constexpr")
    set_languages("cxx14")
    add_defines_if_ok("CONSTEXPR_ENABLE")
    add_cxxsnippet("constexpr", "constexpr int f(int x) { int sum=0; for (int i=0; i<=x; ++i) sum += i; return sum; } constexpr int x = f(5);  static_assert(x == 15);")

-- add target
target("test")

    -- set kind
    set_kind("binary")

    -- add files
    add_files("src/*.cpp") 

    -- need constexpr
    add_options("constexpr")
```

**Comment by waruqi** [comment]
I'll focus on improving `option` to provide more flexible detection, but now I need to finish `xmake require` first.

for example, provide some builtin options in `xmake/options` directory, like `.cmake/Modules`

```lua
option("find_qt")
      on_check(function (option)
             -- check qt ...
             -- add links, linkdirs .. to option 
      end)
```

```lua
option("xxx_interface")
      add_links("xxx")
      on_check(function (option)
             -- try compile codes
             -- try run and test codes (empty implementation?)
      end)
```

**Comment by TitanSnow** [comment]
Maybe just translate some `.cmake` files manually is enough to finish the goal

I found cmake is licensed under BSD-3 so there's no problem

**Comment by waruqi** [comment]
@TitanSnow But I don't like cmake's grammar and design, and don't want to be overly reliant on and use them.

**Comment by TitanSnow** [comment]
For grammar, I do not like cmake's as well

But at least we could quickly look through them and come up with some ideas

**Comment by waruqi** [comment]
Yes, it provides some good features and ideas. I will refer to them when I begin to improve `option`.

**Comment by waruqi** [comment]
But I don't want to parse them for fast implementation, I need design the whole architecture first. Even if it will delay some time.

**Comment by TitanSnow** [comment]
Yeah, it might be best solution

**Comment by waruqi** [comment]
I've started to implement some detection modules and 
I'll add a new interface `has_feature` to make it easier to judge all compiler features in the future. for example:

```lua
target("test")
     set_kind("binary")
     if has_feature("const_expr") then
          add_defines("-DCONST_EXPR")
          add_files("src/*.cpp")
     end
```

**Comment by waruqi** [comment]
detect modules roadmap:

- [x] basic modules (`lib.detect.*`)
  - [x] find_file
    - [x] by `os.files`
    - [ ] find from winreg
  - [x] find_path
    - [x] by `os.filedirs`
    - [ ] find from winreg
  - [ ] find_library
    - [ ] by `os.files` and `os.filedirs`
    - [ ] find from `pkg-config`
    - [ ] find from winreg
  - [x] find_program
    - [ ] find from `which`
    - [ ] find from winreg
  - [ ] find_toolchains (cross, toolchains dir, ...)
  - [ ] check_features for (compiler, linker ..)
- [x] detect tools (`detect.tool.*`)
  - [x] git
  - [x] curl
  - [x] wget
  - [x] unzip/tar/gzip/7z ..
  - [x] git
  - [x] curl
  - [x] wget
  - [ ] compilers (`detect.tool.compiler.*`)
    - [ ] gcc
    - [ ] clang
    - [ ] msvc(cl.exe)
    - [ ] dmd
    - [ ] rustc
    - [ ] go
    - [ ] cgo
  - [ ] linkers (`detect.tool.linker.*`)
    - [ ] gcc
    - [ ] clang
    - [ ] msvc(lib/link)
    - [ ] ...
- [ ] detect sdk (`detect.sdk.*`)
  - [x] xcode
  - [ ] android ndk (will handle)
  - [ ] vstudio (will handle)
- [ ] detect features (`detect.feature.*`)
   - [ ] compiler (`detect.feature.compiler.*`)
     - [ ] flags features
     - [ ] language features
       - [ ] const_expr (c++)
       - [ ] ..
    - [ ] linker (`detect.feature.linker.*`)
      - [ ] flags features
- [ ] lua api in `xmake.lua`
  - [ ] `has_features("const_expr", "..")`
  - [ ] `option.on_check()`
  - [ ] `target:add_xxx()` in `before_build()`
  - [ ] `option:add_xxx` in `on_check()`

**Comment by TitanSnow** [comment]
winreg roadmap:
- [ ] get
  - [x] path parse
  - [ ] type support
    - [ ] REG_BINARY
    - [x] REG_DWORD
    - [x] REG_EXPAND_SZ
    - [ ] REG_LINK
    - [ ] REG_MULTI_SZ
    - [ ] REG_QWORD
    - [x] REG_SZ
- [ ] set

**Comment by waruqi** [comment]
@htfy96 @TitanSnow I have implemented these features, please see: [new-features-v2.1.5](http://tboox.org/2017/07/29/new-features-v2.1.5/)
