### ISSUE TITLE
logo needed

### ISSUE THREAD

**Issue by TitanSnow** [tboox/xmake#86]
logo needed

I have only found the logo of tboox but none of xmake

**Comment by waruqi** [comment]
I have never made a satisfactory logo about xmake.

**Comment by TitanSnow** [comment]
I have considered logos based on a large single letter `X` but it'll look like the one of Xorg

**Comment by waruqi** [comment]
I also want to add an X in the logo, but do not know how to design is more nice.

**Comment by TitanSnow** [comment]
How does this like?

![logo](https://cloud.githubusercontent.com/assets/19969470/26133868/1414e578-3add-11e7-8ec1-c0abb144abae.png)

**Comment by waruqi** [comment]
Great, but the color is a little darker, I prefer a brighter style. 

Like the theme of the homepage. [xmake.io](http://xmake.io/#/)

**Comment by TitanSnow** [comment]
I opened a [repo](https://github.com/TitanSnow/ts-xmake-logo) to do this

The logo uses SVG. Maybe you could help. [I invited you to be a collaborator](https://github.com/TitanSnow/ts-xmake-logo/invitations)

**Comment by waruqi** [comment]
Ok, Thanks!
